import {
  initWindow, windowShouldClose, beginDrawing, endDrawing, clearBackground,
  setTargetFPS, getDeltaTime, getFPS, getTime,
  beginMode3D, endMode3D,
  drawCube, drawSphere, drawText, drawRect, drawCircle, measureText,
  setAmbientLight, setDirectionalLight, setEnvClearFromHdr,
  getScreenWidth, getScreenHeight,
  vec3,
  isKeyPressed, Key, Vec3, injectKeyDown, injectKeyUp,
  disableCursor, enableCursor, takeScreenshot,
  loadModel, drawModel, loadModelAnimation, updateModelAnimation,
  createMesh, createMeshExplicit, genMeshCube,
  compileMaterial, compileRefractiveMaterial, drawMeshWithMaterial,
  initAudio, loadSound, playSound, setSoundVolume,
  loadMusic, playMusic, updateMusicStream, setMusicVolume,
  setProfilerEnabled, getProfilerOverlay, getProfilerFrameHistory,
  splatImpulse, setMaterialParams,
  compileMaterialFromFile, loadMaterial,
} from 'bloom';
import {
  setVignette, setFilmGrain,
  setEnvIntensity, setAutoExposure, setFog, setSunShafts,
} from 'bloom/core';
import { addPointLight, enableShadows } from 'bloom/scene';
import {
  createWorld, step as stepPhysics,
  boxShape, heightfieldShape, createBody, MotionType, Layer,
  setLayerCollides, raycast, ALL_LAYERS_MASK, BodyHandle,
  setBodyPosition,
} from 'bloom/physics';
import { initInput, readInput } from './input';
import { createPlayer, updatePlayerController, playerPosition } from './player';
import * as W from './generated/world';
import * as T from './generated/terrain';

initWindow(1024, 640, 'Bloom Shooter');
setTargetFPS(60);
initInput();

// ---- M8 polish: audio -----------------------------------------------------
initAudio();
const sfxFire = loadSound('assets/sounds/rifle_fire.wav');
const sfxAttack = loadSound('assets/sounds/dretch_attack.wav');
const sfxPickup = loadSound('assets/sounds/pickup.wav');
setSoundVolume(sfxFire, 0.35);
setSoundVolume(sfxAttack, 0.6);
setSoundVolume(sfxPickup, 0.8);
const musicAmbient = loadMusic('assets/sounds/ambient.ogg');
setMusicVolume(musicAmbient, 0.35);
playMusic(musicAmbient);

const physics = createWorld({ gravity: vec3(0, -20, 0) });
// Make NON_MOVING (static) and MOVING (character/dynamic) collide.
setLayerCollides(physics, Layer.NON_MOVING, Layer.MOVING, true);
setLayerCollides(physics, Layer.MOVING, Layer.MOVING, true);

// ---- World: arena_02 (see src/generated/world.ts) -------------------------
// Authored in assets/worlds/arena_02.world.json; flat-array TS module is
// regenerated by tools/build-world.ts before every build. All geometry,
// lighting, spawners, pickups, and the wave plan come from that world data.
// The editor can read/write the same JSON → one source of truth.

const spawnPos: Vec3 = vec3(W.SPAWN_X, W.SPAWN_Y, W.SPAWN_Z);
const spawnYaw = W.SPAWN_YAW;

// Apply environment settings from the world file. Tier-1 visual
// quality work (see docs/visual-quality.md) layers IBL + shadows +
// fog + auto-exposure on top of the existing ambient + sun.
setAmbientLight(
  { r: Math.floor(W.ENV_AMBIENT_R * 255), g: Math.floor(W.ENV_AMBIENT_G * 255),
    b: Math.floor(W.ENV_AMBIENT_B * 255), a: 255 },
  W.ENV_AMBIENT_I);
setDirectionalLight(
  vec3(W.ENV_SUN_DIR_X, W.ENV_SUN_DIR_Y, W.ENV_SUN_DIR_Z),
  { r: Math.floor(W.ENV_SUN_R * 255), g: Math.floor(W.ENV_SUN_G * 255),
    b: Math.floor(W.ENV_SUN_B * 255), a: 255 },
  W.ENV_SUN_I);

// Tier 1.1 — load an HDR equirectangular environment. The engine
// convolves it into env_tex (specular) + env_diffuse_tex (ambient
// diffuse) at load time; refractive water + glass automatically
// pick it up via sample_env(). With nothing loaded the env binds
// are 1×1 black and PBR specular is dead.
setEnvClearFromHdr('assets/env/outdoor.hdr');
// Tier 1.2 — IBL strength. 1.0 = unit; bump up if the scene reads
// dim against the new HDR sky, pull back if it blows out.
setEnvIntensity(1.0);
// Tier 1.3 — three-cascade sun shadows. Adds ~3 ms of GPU work
// but grounds every object visually.
enableShadows();
// Tier 1.4 — auto-exposure. The HDR pipeline tonemaps to surface
// sRGB with a fixed exposure if this is off; auto follows scene
// luminance which is the right behaviour outdoors.
setAutoExposure(true);
// Tier 1.5 — pale-blue distance haze. r,g,b,density,heightRef,
// heightFalloff. Density 0.012 reads as a soft far-plane haze
// without dimming the foreground.
setFog(0.78, 0.84, 0.90, 0.012, 0.0, 200.0);
// Tier 1.7 — warm god-rays through the trees. Optional polish;
// strength 0.4 keeps it subtle.
setSunShafts(0.4, 0.96, 1.0, 0.95, 0.7);

// Static box colliders — invisible physics walls that bound the plaza
// and carry the ground plane.
for (let i = 0; i < W.COLLIDER_COUNT; i++) {
  const shape = boxShape(vec3(W.COLLIDER_HALF_X[i], W.COLLIDER_HALF_Y[i], W.COLLIDER_HALF_Z[i]));
  createBody(physics, shape, {
    motionType: MotionType.STATIC,
    position: vec3(W.COLLIDER_X[i], W.COLLIDER_Y[i], W.COLLIDER_Z[i]),
    objectLayer: Layer.NON_MOVING,
    friction: 0.9,
  });
}

// Heightfield terrain collider — matches assets/models/terrain_hills.glb.
// Samples in TERRAIN_HEIGHTS are row-major z*width+x; engine's heightfield
// shape takes an origin + scale (cellSize in X/Z, Y=1 since the heights
// are already in world units) and builds a Jolt HeightFieldShape.
{
  const shape = heightfieldShape(
    T.TERRAIN_HEIGHTS, T.TERRAIN_SAMPLE_COUNT,
    vec3(T.TERRAIN_ORIGIN_X, T.TERRAIN_ORIGIN_Y, T.TERRAIN_ORIGIN_Z),
    vec3(T.TERRAIN_CELL_SIZE, 1, T.TERRAIN_CELL_SIZE));
  createBody(physics, shape, {
    motionType: MotionType.STATIC,
    position: vec3(0, 0, 0),
    objectLayer: Layer.NON_MOVING,
    friction: 0.95,
  });
}

// Drawable meshes: each static_mesh entity references a modelRef via
// MESH_MODEL_IDX → UNIQUE_MODELS. Real GLBs are loaded once here and
// drawn via drawModel each frame. Box-placeholder entries (modelRef
// `_gizmo_box.glb`) get a coloured drawCube fallback at draw time,
// tinted by category (0 = generic, 1 = building stone, 2 = terrain
// green, 3 = prop brown).
const MESH_TINT_R = [150, 196, 120, 130];
const MESH_TINT_G = [148, 168,  90,  95];
const MESH_TINT_B = [140, 130,  70,  80];
const meshModelHandles = new Array<number>(W.UNIQUE_MODEL_COUNT);
for (let i = 0; i < W.UNIQUE_MODEL_COUNT; i++) {
  meshModelHandles[i] = W.MODEL_IS_BOX[i] === 1 ? 0 : loadModel(W.UNIQUE_MODELS[i]);
}
// Tier 3b — replace the cardboard-cutout prop_tree.glb with four
// real CC0 variants (oak, fat, detailed, default) drawn in
// rotation. Picked per-mesh by index hash so the same world
// always lays out the same trees, but adjacent trees never
// match exactly. Scale jitter via the same hash adds height
// variety. See docs/visual-quality.md.
const treeVariants: number[] = [
  loadModel('assets/models/tree_oak.glb'),
  loadModel('assets/models/tree_fat.glb'),
  loadModel('assets/models/tree_detailed.glb'),
  loadModel('assets/models/tree_default.glb'),
];
let treePropIdx = -1;
let terrainPropIdx = -1;
for (let i = 0; i < W.UNIQUE_MODEL_COUNT; i++) {
  if (W.UNIQUE_MODELS[i] === 'assets/models/prop_tree.glb')     { treePropIdx    = i; }
  if (W.UNIQUE_MODELS[i] === 'assets/models/terrain_hills.glb') { terrainPropIdx = i; }
}

// Tier 2a — terrain colour material. Compile via the file-based
// API for hot-reload, then push the param UBO via setMaterialParams
// directly (loadMaterial's array-length pass-through is unreliable
// under Perry — the FFI receives zero count for inline literals).
//   grass_dry rgb  pad   grass_mid rgb  pad   grass_deep rgb pad   dirt rgb pad
//   noise_freq, slope_threshold, ridge_height, pale_strength
const matTerrain = compileMaterialFromFile('assets/materials/terrain.wgsl', 'opaque');
const TERRAIN_PARAMS = [
  0.55, 0.62, 0.30,  0.0,
  0.20, 0.46, 0.16,  0.0,
  0.10, 0.28, 0.08,  0.0,
  0.34, 0.26, 0.18,  0.0,
  0.18, 0.78, 4.0,   0.55,
];
if (matTerrain > 0) setMaterialParams(matTerrain, TERRAIN_PARAMS);
// Per-mesh collider from userData.collider === 'box'.
for (let i = 0; i < W.MESH_COUNT; i++) {
  if (W.MESH_COLLIDER[i] === 1) {
    const shape = boxShape(vec3(W.MESH_COLLIDER_HX[i], W.MESH_COLLIDER_HY[i], W.MESH_COLLIDER_HZ[i]));
    createBody(physics, shape, {
      motionType: MotionType.STATIC,
      position: vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
      objectLayer: Layer.NON_MOVING,
      friction: 0.9,
    });
  }
}
const worldStatus = W.WORLD_NAME + ' (' + W.COLLIDER_COUNT + '+' + W.MESH_COUNT + ' bodies)';


createPlayer(physics, spawnPos);

// ---- Third-person orbit camera (inline; see perry-quirks.md) --------------
// Array-slot state because Perry 0.5.158 doesn't propagate module-scope
// `let` reassignments across function calls. Cross-module array writes
// are even more fragile; keeping everything local to main.ts so the
// compiler has no excuse to lose the writes.
//   CAM[0] yaw           CAM[5] tgtX
//   CAM[1] pitch         CAM[6] tgtY
//   CAM[2] camX          CAM[7] tgtZ
//   CAM[3] camY          CAM[8] initialised (0/1)
//   CAM[4] camZ
const CAM = [spawnYaw, 0.35, 0, 0, 0, 0, 0, 0, 0];
const TP_PITCH_MIN = -0.25;
const TP_PITCH_MAX = 1.20;
const TP_ORBIT_DIST = 6.0;
const TP_EYE_HEIGHT = 1.4;
const TP_SMOOTH = 10.0;
const TP_FOVY = 70;

// ---- Third-person player model (human_bsuit) -----------------------------
// Converted via tools/convert-aliens-anim.ts. Drawn at the physics-character
// position, facing the camera's horizontal yaw so the player always looks
// "away from the camera" (classic 3rd-person over-the-shoulder feel).
const mdlPlayer  = loadModel('assets/models/player_bsuit.glb');
const animPlayer = loadModelAnimation('assets/models/player_bsuit.glb');
// human_bsuit animation indices (IQE declaration order):
//   0 idle, 7 attack, 8 run, 12 walk.
const PLAYER_ANIM_IDLE   = 0;
const PLAYER_ANIM_WALK   = 12;
const PLAYER_ANIM_RUN    = 8;
const PLAYER_ANIM_ATTACK = 7;
const PLAYER_SCALE = 1.0;
const PLAYER_MODEL_Y_OFFSET = -0.95;    // character capsule center -> feet
let playerAnimT = 0;

// ---- Phase 1c smoke: material shader + cube mesh -------------------------
// Compiles a tiny ABI-compliant shader through the new material
// pipeline and draws a rotating colour-pulsed cube in front of the
// player spawn. First visible consumer of the material-system path;
// only exists to verify end-to-end compile → submit → dispatch works.

const MAT_TEST_WGSL = '#include "material_abi.wgsl"\n' +
  'struct VsOut { @builtin(position) pos: vec4<f32>, @location(0) n: vec3<f32>, @location(1) c: vec3<f32> };\n' +
  '@vertex fn vs_main(in: VertexInput) -> VsOut {\n' +
  '  var o: VsOut;\n' +
  '  o.pos = draw.mvp * vec4<f32>(in.position, 1.0);\n' +
  '  o.n = normalize((draw.model * vec4<f32>(in.normal, 0.0)).xyz);\n' +
  '  let p = 0.5 + 0.5 * sin(frame.time * 1.5);\n' +
  '  o.c = vec3<f32>(p, 0.4, 1.0 - p) * draw.model_tint.rgb;\n' +
  '  return o;\n' +
  '}\n' +
  '@fragment fn fs_main(in: VsOut) -> OpaqueOut {\n' +
  '  var out: OpaqueOut;\n' +
  '  let ndl = max(dot(normalize(in.n), normalize(vec3<f32>(0.3, 0.7, 0.4))), 0.0);\n' +
  '  let lit = in.c * (0.3 + 0.7 * ndl);\n' +
  '  out.hdr = vec4<f32>(lit, 1.0);\n' +
  '  out.material = vec2<f32>(0.0, 0.9);\n' +
  '  out.velocity = vec2<f32>(0.0, 0.0);\n' +
  '  out.albedo = vec4<f32>(in.c, 1.0);\n' +
  '  return out;\n' +
  '}\n';
const matTest = compileMaterial(MAT_TEST_WGSL);
// Minimal cube: 24 verts (one per face-corner so UVs / normals split
// cleanly) × 12 floats (pos, nrm, col, uv) = 288 floats. 6 faces × 2
// tris × 3 idx = 36 indices.
const MAT_TEST_VERTS: number[] = [
  // +X face (nrm = +1, 0, 0)
   0.5, -0.5, -0.5,  1,0,0,  1,1,1,1,  0,0,
   0.5, -0.5,  0.5,  1,0,0,  1,1,1,1,  1,0,
   0.5,  0.5,  0.5,  1,0,0,  1,1,1,1,  1,1,
   0.5,  0.5, -0.5,  1,0,0,  1,1,1,1,  0,1,
  // -X
  -0.5, -0.5,  0.5, -1,0,0,  1,1,1,1,  0,0,
  -0.5, -0.5, -0.5, -1,0,0,  1,1,1,1,  1,0,
  -0.5,  0.5, -0.5, -1,0,0,  1,1,1,1,  1,1,
  -0.5,  0.5,  0.5, -1,0,0,  1,1,1,1,  0,1,
  // +Y (top)
  -0.5,  0.5,  0.5,  0,1,0,  1,1,1,1,  0,0,
   0.5,  0.5,  0.5,  0,1,0,  1,1,1,1,  1,0,
   0.5,  0.5, -0.5,  0,1,0,  1,1,1,1,  1,1,
  -0.5,  0.5, -0.5,  0,1,0,  1,1,1,1,  0,1,
  // -Y
  -0.5, -0.5, -0.5,  0,-1,0, 1,1,1,1,  0,0,
   0.5, -0.5, -0.5,  0,-1,0, 1,1,1,1,  1,0,
   0.5, -0.5,  0.5,  0,-1,0, 1,1,1,1,  1,1,
  -0.5, -0.5,  0.5,  0,-1,0, 1,1,1,1,  0,1,
  // +Z
   0.5, -0.5,  0.5,  0,0,1,  1,1,1,1,  0,0,
  -0.5, -0.5,  0.5,  0,0,1,  1,1,1,1,  1,0,
  -0.5,  0.5,  0.5,  0,0,1,  1,1,1,1,  1,1,
   0.5,  0.5,  0.5,  0,0,1,  1,1,1,1,  0,1,
  // -Z
  -0.5, -0.5, -0.5,  0,0,-1, 1,1,1,1,  0,0,
   0.5, -0.5, -0.5,  0,0,-1, 1,1,1,1,  1,0,
   0.5,  0.5, -0.5,  0,0,-1, 1,1,1,1,  1,1,
  -0.5,  0.5, -0.5,  0,0,-1, 1,1,1,1,  0,1,
];
const MAT_TEST_INDS: number[] = [
   0, 1, 2,  0, 2, 3,
   4, 5, 6,  4, 6, 7,
   8, 9,10,  8,10,11,
  12,13,14, 12,14,15,
  16,17,18, 16,18,19,
  20,21,22, 20,22,23,
];
const matTestMesh = createMesh(MAT_TEST_VERTS, MAT_TEST_INDS);

// ---- Phase 9 water — real shader-based river ----------------------------
// Replaces the ~1800-cube tessellated river from earlier with a proper
// WGSL material: three Gerstner waves for vertex displacement, per-vertex
// normal from the wave derivatives, Fresnel-blended refraction (sampling
// the SceneColor snapshot) and sky reflection (from the engine's env
// cubemap), plus foam on high-slope crests. Single drawMeshWithMaterial
// call; Phase 4b handles the snapshot + translucent pass automatically.

const WATER_WGSL =
  '#include "material_abi.wgsl"\n' +
  '#include "common/pbr.wgsl"\n' +
  '\n' +
  '// Phase 5 — per-material user_params at @group(2) @binding(11).\n' +
  '// Runtime tweakable from TS via setMaterialParams(matWater, [...]).\n' +
  'struct WaterParams {\n' +
  '  tint:     vec4<f32>,  // xyz = absorption tint, w = absorption mix\n' +
  '  knobs:    vec4<f32>,  // x = foam strength, y = rim brightness, z = sky LOD, w = -\n' +
  '};\n' +
  '@group(2) @binding(11) var<uniform> water_params: WaterParams;\n' +
  '\n' +
  'struct VsOut {\n' +
  '  @builtin(position) clip_pos: vec4<f32>,\n' +
  '  @location(0) world_pos: vec3<f32>,\n' +
  '  @location(1) world_normal: vec3<f32>,\n' +
  '  @location(2) screen_uv: vec2<f32>,\n' +
  '};\n' +
  '\n' +
  'fn gerstner(\n' +
  '  pos: vec2<f32>, dir: vec2<f32>, wavelength: f32,\n' +
  '  steepness: f32, time: f32,\n' +
  '  tangent_accum:  ptr<function, vec3<f32>>,\n' +
  '  binormal_accum: ptr<function, vec3<f32>>,\n' +
  ') -> vec3<f32> {\n' +
  '  let k = 6.28318 / wavelength;\n' +
  '  let c = sqrt(9.81 / k);\n' +
  '  let f = k * (dot(dir, pos) - c * time);\n' +
  '  let a = steepness / k;\n' +
  '  let cos_f = cos(f);\n' +
  '  let sin_f = sin(f);\n' +
  '  (*tangent_accum) = (*tangent_accum) + vec3<f32>(\n' +
  '    -dir.x * dir.x * steepness * sin_f,\n' +
  '     dir.x * steepness * cos_f,\n' +
  '    -dir.x * dir.y * steepness * sin_f,\n' +
  '  );\n' +
  '  (*binormal_accum) = (*binormal_accum) + vec3<f32>(\n' +
  '    -dir.x * dir.y * steepness * sin_f,\n' +
  '     dir.y * steepness * cos_f,\n' +
  '    -dir.y * dir.y * steepness * sin_f,\n' +
  '  );\n' +
  '  return vec3<f32>(dir.x * a * cos_f, a * sin_f, dir.y * a * cos_f);\n' +
  '}\n' +
  '\n' +
  '@vertex\n' +
  'fn vs_main(in: VertexInput) -> VsOut {\n' +
  '  var out: VsOut;\n' +
  '  var local = in.position;\n' +
  '  let world_xz = (draw.model * vec4<f32>(local, 1.0)).xz;\n' +
  '  let t = frame.time;\n' +
  '  var tangent  = vec3<f32>(1.0, 0.0, 0.0);\n' +
  '  var binormal = vec3<f32>(0.0, 0.0, 1.0);\n' +
  '  local = local + gerstner(world_xz, normalize(vec2<f32>( 1.0,  0.3)), 5.0, 0.25, t, &tangent, &binormal);\n' +
  '  local = local + gerstner(world_xz, normalize(vec2<f32>( 0.4,  1.0)), 3.5, 0.20, t, &tangent, &binormal);\n' +
  '  local = local + gerstner(world_xz, normalize(vec2<f32>(-0.5,  0.8)), 2.2, 0.15, t, &tangent, &binormal);\n' +
  '  let normal = normalize(cross(binormal, tangent));\n' +
  '  let world  = draw.model * vec4<f32>(local, 1.0);\n' +
  '  out.world_pos    = world.xyz;\n' +
  '  out.world_normal = normalize((draw.model * vec4<f32>(normal, 0.0)).xyz);\n' +
  '  out.clip_pos     = view.view_proj * world;\n' +
  '  out.screen_uv    = out.clip_pos.xy / out.clip_pos.w * vec2<f32>(0.5, -0.5) + vec2<f32>(0.5);\n' +
  '  return out;\n' +
  '}\n' +
  '\n' +
  '@fragment\n' +
  'fn fs_main(in: VsOut) -> @location(0) vec4<f32> {\n' +
  '  let n = normalize(in.world_normal);\n' +
  '  let v = normalize(view.camera_pos.xyz - in.world_pos);\n' +
  '\n' +
  '  // Refraction — perturb screen UV by wave normal xz.\n' +
  '  let refract_uv = clamp(in.screen_uv + n.xz * 0.04, vec2<f32>(0.001), vec2<f32>(0.999));\n' +
  '  let refracted  = textureSampleLevel(scene_color_tex, scene_color_samp, refract_uv, 0.0).rgb;\n' +
  '\n' +
  '  // Sky reflection from the engine env — roughness-biased LOD fakes a softer highlight.\n' +
  '  let r   = reflect(-v, n);\n' +
  '  let sky = sample_env(r, water_params.knobs.z);\n' +
  '\n' +
  '  // Schlick Fresnel.\n' +
  '  let cos_theta = max(dot(n, v), 0.0);\n' +
  '  let fresnel   = 0.02 + (1.0 - 0.02) * pow(1.0 - cos_theta, 5.0);\n' +
  '\n' +
  '  // Absorption — tint + mix factor from user_params.\n' +
  '  let tinted = mix(water_params.tint.xyz, refracted, water_params.tint.w);\n' +
  '  var water  = mix(tinted, sky, fresnel);\n' +
  '\n' +
  '  // Foam on wave crests (slope proxy — high when normal tilts off +Y).\n' +
  '  let crestness = clamp(1.0 - n.y, 0.0, 1.0);\n' +
  '  let foam      = smoothstep(0.08, 0.25, crestness);\n' +
  '  water = mix(water, vec3<f32>(0.95, 0.98, 1.0), foam * water_params.knobs.x);\n' +
  '\n' +
  '  // Phase 4c — shoreline fade. Sample the opaque-depth snapshot,\n' +
  '  // linearise both that and the fragment depth to view-space Z\n' +
  '  // (metres), and fade out as the water column thins.\n' +
  '  let depth_dims = textureDimensions(scene_depth_tex);\n' +
  '  let depth_ix   = vec2<i32>(in.screen_uv * vec2<f32>(depth_dims));\n' +
  '  let scene_d    = textureLoad(scene_depth_tex, depth_ix, 0);\n' +
  '  let ndc_xy     = vec2<f32>(in.screen_uv.x * 2.0 - 1.0, 1.0 - in.screen_uv.y * 2.0);\n' +
  '  let floor_v    = view.inv_proj * vec4<f32>(ndc_xy, scene_d, 1.0);\n' +
  '  let surf_v     = view.inv_proj * vec4<f32>(ndc_xy, in.clip_pos.z, 1.0);\n' +
  '  let floor_z    = floor_v.z / floor_v.w;\n' +
  '  let surf_z     = surf_v.z / surf_v.w;\n' +
  '  // Both z are negative (wgpu looks down -Z); water column = surf - floor.\n' +
  '  let column     = max(surf_z - floor_z, 0.0);\n' +
  '  let shore_t    = smoothstep(0.0, 0.15, column);\n' +
  '  let rim        = (1.0 - shore_t) * water_params.knobs.y;\n' +
  '  water = mix(water, vec3<f32>(0.96, 0.99, 1.0), rim);\n' +
  '\n' +
  '  // Phase 7 — sample the world-space impulse field for ripples.\n' +
  '  // The engine maps the 128 m centred square to [0,1] UVs; we use\n' +
  '  // textureLoad because the field is R32Float (non-filterable).\n' +
  '  let imp_uv   = clamp(in.world_pos.xz / 128.0 + vec2<f32>(0.5), vec2<f32>(0.0), vec2<f32>(0.999));\n' +
  '  let imp_dims = textureDimensions(impulse_tex);\n' +
  '  let imp_ix   = vec2<i32>(imp_uv * vec2<f32>(imp_dims));\n' +
  '  let imp      = textureLoad(impulse_tex, imp_ix, 0).r;\n' +
  '  // Splat contributions — whiten where impulses hit, multiplied\n' +
  '  // against the existing shore rim so water already near the shore\n' +
  '  // gets an extra-bright footprint but deep water rings stay\n' +
  '  // subtle.\n' +
  '  let imp_mix = clamp(imp * 1.2, 0.0, 1.0);\n' +
  '  water = mix(water, vec3<f32>(0.96, 0.99, 1.0), imp_mix * 0.85);\n' +
  '  let alpha = mix(0.45, 0.92, shore_t);\n' +
  '  return vec4<f32>(water, alpha);\n' +
  '}\n';
// Phase 6 — water source lives in assets/materials/water.wgsl on
// disk. compileMaterialFromFile registers the path with the engine's
// hot-reload watcher; editing the file at runtime triggers an
// in-place pipeline rebuild. The inline WATER_WGSL string above is
// kept as a fallback when the file isn't readable — useful for
// shipping single-binary builds where assets aren't on disk.
// Phase 5 — file-backed compile + direct setMaterialParams. Going
// through loadMaterial would be cleaner but Perry mishandles the
// inline-array .length pass-through to the FFI right now (FFI sees
// zero), so we set the params explicitly.
//   tint rgb       absorption_mix  foam  rim   sky_lod  pad
const matWaterFromFile = compileMaterialFromFile('assets/materials/water.wgsl', 'refractive');
const matWater = matWaterFromFile > 0
  ? matWaterFromFile
  : compileRefractiveMaterial(WATER_WGSL);
// Tier 4 layout: absorption coefficient (red dies fastest, blue
// slowest), deep-water colour (greenish-teal), then knobs:
//   foam, rim, sky_lod, micro_normal_strength.
const WATER_PARAMS = [
  0.55, 0.10, 0.05,   0.0,    // absorption per metre
  0.05, 0.18, 0.28,   0.0,    // deep_tint
  0.60, 0.25,         2.0,   0.18,    // foam / rim / sky_lod / micro_strength
];
if (matWater > 0) setMaterialParams(matWater, WATER_PARAMS);

// ---- Water plane mesh — tessellated for Gerstner displacement ----------
// One flat XZ plane covering the whole river footprint in arena_02.
// Drawn at origin with scale 1, so the mesh's native dimensions are the
// visible river size. Subdivide finely enough that the longest
// Gerstner wave (~5 m wavelength) shows smooth wave peaks.
const WATER_W = 80;   // metres along X — spans the arena's boundary walls
const WATER_D = 5;    // metres along Z — river width
const WATER_CX = 0;   // world X centre
const WATER_CZ = 12;  // world Z centre (matches arena_02's river band)
const WATER_Y  = 0.05;
const WATER_COLS = 80;
const WATER_ROWS = 10;
const _wvc = (WATER_COLS + 1) * (WATER_ROWS + 1);
const _wic = WATER_COLS * WATER_ROWS * 2 * 3;
const WATER_VERTS = new Array<number>(_wvc * 12);
const WATER_INDS  = new Array<number>(_wic);
{
  let vi = 0;
  for (let r = 0; r <= WATER_ROWS; r++) {
    for (let c = 0; c <= WATER_COLS; c++) {
      const u = c / WATER_COLS;
      const vv = r / WATER_ROWS;
      // World-space positions — mesh has its own real extent.
      WATER_VERTS[vi++] = -WATER_W * 0.5 + u * WATER_W;
      WATER_VERTS[vi++] = 0;
      WATER_VERTS[vi++] = -WATER_D * 0.5 + vv * WATER_D;
      WATER_VERTS[vi++] = 0; WATER_VERTS[vi++] = 1; WATER_VERTS[vi++] = 0;
      WATER_VERTS[vi++] = 1; WATER_VERTS[vi++] = 1; WATER_VERTS[vi++] = 1; WATER_VERTS[vi++] = 1;
      WATER_VERTS[vi++] = u; WATER_VERTS[vi++] = vv;
    }
  }
  let ii = 0;
  const nc = WATER_COLS + 1;
  for (let r = 0; r < WATER_ROWS; r++) {
    for (let c = 0; c < WATER_COLS; c++) {
      const tl = r * nc + c;
      const tr = tl + 1;
      const bl = tl + nc;
      const br = bl + 1;
      // CCW-from-above so default backface culling doesn't cull them.
      WATER_INDS[ii++] = tl; WATER_INDS[ii++] = br; WATER_INDS[ii++] = bl;
      WATER_INDS[ii++] = tl; WATER_INDS[ii++] = tr; WATER_INDS[ii++] = br;
    }
  }
}
const matWaterMesh = createMeshExplicit(WATER_VERTS, _wvc, WATER_INDS, _wic);

// ---- Tier 2b grass — scattered cross-quad blades ------------------------
// Generates a single big mesh of N blades placed via deterministic RNG
// across the playfield. Each blade is a cross of two perpendicular
// quads (8 verts × 2 sides = double-sided 12 indices, total 24 indices)
// so every blade is visible from any horizontal angle without needing
// to disable backface culling at the pipeline level.
//
// Heights are sampled from the engine's TERRAIN_HEIGHTS heightmap so
// blades sit flat against the slope. Skip points that fall in the
// river band, in/under the building footprint, or on too-steep
// ground where blades would float visibly.
const matGrass = compileMaterialFromFile('assets/materials/grass.wgsl', 'opaque');
const GRASS_PARAMS = [
  // wind: dir.xz, amplitude (max sway in m), frequency (rad/s)
  0.85, 0.50,  0.10,  1.6,
  // base hue rgb, jitter amount (0..1)
  0.30, 0.46, 0.18,   0.55,
];
if (matGrass > 0) setMaterialParams(matGrass, GRASS_PARAMS);

const GRASS_BLADE_COUNT = 4000;
const GRASS_BLADE_W = 0.05;
const GRASS_BLADE_H = 0.4;
const GRASS_VERTS_PER_BLADE = 8;       // 4 verts per quad × 2 quads
const GRASS_INDS_PER_BLADE  = 24;      // 6 per quad × 2 sides × 2 quads
const _gvc = GRASS_BLADE_COUNT * GRASS_VERTS_PER_BLADE;
const _gic = GRASS_BLADE_COUNT * GRASS_INDS_PER_BLADE;
const GRASS_VERTS = new Array<number>(_gvc * 12);
const GRASS_INDS  = new Array<number>(_gic);
{
  // Building rect (matches gen-building.ts)
  const BX0 = -30, BX1 = -12, BZ0 = -19, BZ1 = -7;

  let vi = 0, ii = 0, vbase = 0, placed = 0;
  // Manual Lehmer-LCG state inline (Perry codegen quirks make
  // closures-with-captures finicky; better to keep mutating state
  // visible in the loop).
  let seed = 0x12345 | 0;
  for (let attempt = 0; attempt < GRASS_BLADE_COUNT * 3 && placed < GRASS_BLADE_COUNT; attempt++) {
    seed = ((seed * 1103515245) + 12345) & 0x7fffffff;
    const r1 = seed / 0x7fffffff;
    seed = ((seed * 1103515245) + 12345) & 0x7fffffff;
    const r2 = seed / 0x7fffffff;
    seed = ((seed * 1103515245) + 12345) & 0x7fffffff;
    const r3 = seed / 0x7fffffff;
    seed = ((seed * 1103515245) + 12345) & 0x7fffffff;
    const r4 = seed / 0x7fffffff;
    const px = -38 + r1 * 76;
    const pz = -38 + r2 * 76;
    // Reject inside building or under it.
    if (px > BX0 && px < BX1 && pz > BZ0 && pz < BZ1) continue;
    // Reject inside the river band (visual + perf cost when underwater).
    if (Math.abs(pz - 12) < 3.5 && Math.abs(px) < 40) continue;
    // Sample TERRAIN_HEIGHTS bilinearly for the blade's Y so it
    // sits flat on the heightmap. Inlined (Perry chokes on a
    // helper closure that captures the array).
    const u = (px - T.TERRAIN_ORIGIN_X) / T.TERRAIN_CELL_SIZE;
    const v = (pz - T.TERRAIN_ORIGIN_Z) / T.TERRAIN_CELL_SIZE;
    let py = 0;
    if (u >= 0 && v >= 0 && u < T.TERRAIN_SAMPLE_COUNT - 1 && v < T.TERRAIN_SAMPLE_COUNT - 1) {
      const ix = Math.floor(u), iz = Math.floor(v);
      const fx = u - ix, fz = v - iz;
      const h00 = T.TERRAIN_HEIGHTS[iz * T.TERRAIN_SAMPLE_COUNT + ix];
      const h10 = T.TERRAIN_HEIGHTS[iz * T.TERRAIN_SAMPLE_COUNT + ix + 1];
      const h01 = T.TERRAIN_HEIGHTS[(iz + 1) * T.TERRAIN_SAMPLE_COUNT + ix];
      const h11 = T.TERRAIN_HEIGHTS[(iz + 1) * T.TERRAIN_SAMPLE_COUNT + ix + 1];
      py = (h00 * (1 - fx) + h10 * fx) * (1 - fz) +
           (h01 * (1 - fx) + h11 * fx) * fz;
    }
    // Tiny per-blade height + hue jitter.
    const heightScale = 0.85 + r3 * 0.30;
    const hueJitter   = r4;
    const w = GRASS_BLADE_W;
    const h = GRASS_BLADE_H * heightScale;

    // 8 verts × 12 floats inlined (Perry caps closures at 5 args).
    // Layout: pos(3) normal(3) color(4) uv(2). color = (tip, jitter, 1, 1).
    // Quad 1 — XY plane, normal +Z.
    GRASS_VERTS[vi++] = px - w; GRASS_VERTS[vi++] = py;     GRASS_VERTS[vi++] = pz;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = px + w; GRASS_VERTS[vi++] = py;     GRASS_VERTS[vi++] = pz;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = px + w; GRASS_VERTS[vi++] = py + h; GRASS_VERTS[vi++] = pz;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = px - w; GRASS_VERTS[vi++] = py + h; GRASS_VERTS[vi++] = pz;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 1;
    // Quad 2 — YZ plane, normal +X.
    GRASS_VERTS[vi++] = px;     GRASS_VERTS[vi++] = py;     GRASS_VERTS[vi++] = pz - w;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = px;     GRASS_VERTS[vi++] = py;     GRASS_VERTS[vi++] = pz + w;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = px;     GRASS_VERTS[vi++] = py + h; GRASS_VERTS[vi++] = pz + w;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = px;     GRASS_VERTS[vi++] = py + h; GRASS_VERTS[vi++] = pz - w;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 0;
    GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = hueJitter; GRASS_VERTS[vi++] = 1; GRASS_VERTS[vi++] = 1;
    GRASS_VERTS[vi++] = 0; GRASS_VERTS[vi++] = 1;

    // Indices — front + back triangles for each quad.
    // Quad 1 front (CCW from +Z): 0,1,2  0,2,3
    GRASS_INDS[ii++] = vbase + 0; GRASS_INDS[ii++] = vbase + 1; GRASS_INDS[ii++] = vbase + 2;
    GRASS_INDS[ii++] = vbase + 0; GRASS_INDS[ii++] = vbase + 2; GRASS_INDS[ii++] = vbase + 3;
    // Quad 1 back  (CCW from -Z): 0,2,1  0,3,2
    GRASS_INDS[ii++] = vbase + 0; GRASS_INDS[ii++] = vbase + 2; GRASS_INDS[ii++] = vbase + 1;
    GRASS_INDS[ii++] = vbase + 0; GRASS_INDS[ii++] = vbase + 3; GRASS_INDS[ii++] = vbase + 2;
    // Quad 2 front: 4,5,6  4,6,7
    GRASS_INDS[ii++] = vbase + 4; GRASS_INDS[ii++] = vbase + 5; GRASS_INDS[ii++] = vbase + 6;
    GRASS_INDS[ii++] = vbase + 4; GRASS_INDS[ii++] = vbase + 6; GRASS_INDS[ii++] = vbase + 7;
    // Quad 2 back: 4,6,5  4,7,6
    GRASS_INDS[ii++] = vbase + 4; GRASS_INDS[ii++] = vbase + 6; GRASS_INDS[ii++] = vbase + 5;
    GRASS_INDS[ii++] = vbase + 4; GRASS_INDS[ii++] = vbase + 7; GRASS_INDS[ii++] = vbase + 6;

    vbase += GRASS_VERTS_PER_BLADE;
    placed++;
  }
}
const matGrassMesh = createMeshExplicit(GRASS_VERTS, _gvc, GRASS_INDS, _gic);

// ---- Building stone material — bake all box-placeholder building
// entries into a single static mesh, drawn once per frame against
// a noise + horizontal-band material. Replaces the flat-beige
// drawCube path for category-1 (building) entities.
const matBuilding = compileMaterialFromFile('assets/materials/building.wgsl', 'opaque');
const BUILDING_PARAMS = [
  // base rgb (warm sandstone)        noise mix
  0.72, 0.66, 0.55,                   0.55,
  // band rgb (darker mortar line)    band tightness (higher = sharper)
  0.40, 0.34, 0.28,                   1.4,
  // noise_freq, band_period (m), unused, unused
  0.50, 3.0,                          0.0,   0.0,
];
if (matBuilding > 0) setMaterialParams(matBuilding, BUILDING_PARAMS);

// Count the building boxes first so we can size the arrays.
let _bldgCount = 0;
for (let i = 0; i < W.MESH_COUNT; i++) {
  const mi = W.MESH_MODEL_IDX[i];
  if (W.MODEL_IS_BOX[mi] === 1 && W.MESH_CATEGORY[i] === 1) _bldgCount++;
}
const _bvc = _bldgCount * 24;     // 24 verts per cube (4 per face × 6 faces)
const _bic = _bldgCount * 36;     // 36 indices per cube (2 tris × 6 faces)
const BUILDING_VERTS = new Array<number>(_bvc * 12);
const BUILDING_INDS  = new Array<number>(_bic);
{
  let vi = 0, ii = 0, vbase = 0;
  for (let i = 0; i < W.MESH_COUNT; i++) {
    const mi = W.MESH_MODEL_IDX[i];
    if (W.MODEL_IS_BOX[mi] !== 1 || W.MESH_CATEGORY[i] !== 1) continue;
    const cx = W.MESH_X[i], cy = W.MESH_Y[i], cz = W.MESH_Z[i];
    const hx = W.MESH_COLLIDER_HX[i];
    const hy = W.MESH_COLLIDER_HY[i];
    const hz = W.MESH_COLLIDER_HZ[i];
    const xn = cx - hx, xp = cx + hx;
    const yn = cy - hy, yp = cy + hy;
    const zn = cz - hz, zp = cz + hz;
    // Six faces, 4 verts each. Vertex layout: pos(3) normal(3)
    // color(4) uv(2) — colors all white, UVs unused (material
    // samples world XY/XZ/YZ).
    // +X face (normal +X)
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1;
    // -X face
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1;
    // +Y face (top)
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1;
    // -Y face (bottom)
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1;
    // +Z face
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zp; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1;
    // -Z face
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yn; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0;
    BUILDING_VERTS[vi++] = xp; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1;
    BUILDING_VERTS[vi++] = xn; BUILDING_VERTS[vi++] = yp; BUILDING_VERTS[vi++] = zn; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = -1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 1; BUILDING_VERTS[vi++] = 0; BUILDING_VERTS[vi++] = 1;

    // 36 indices: 6 faces × 2 tris × 3, CCW from outside.
    BUILDING_INDS[ii++] = vbase +  0; BUILDING_INDS[ii++] = vbase +  1; BUILDING_INDS[ii++] = vbase +  2;
    BUILDING_INDS[ii++] = vbase +  0; BUILDING_INDS[ii++] = vbase +  2; BUILDING_INDS[ii++] = vbase +  3;
    BUILDING_INDS[ii++] = vbase +  4; BUILDING_INDS[ii++] = vbase +  5; BUILDING_INDS[ii++] = vbase +  6;
    BUILDING_INDS[ii++] = vbase +  4; BUILDING_INDS[ii++] = vbase +  6; BUILDING_INDS[ii++] = vbase +  7;
    BUILDING_INDS[ii++] = vbase +  8; BUILDING_INDS[ii++] = vbase +  9; BUILDING_INDS[ii++] = vbase + 10;
    BUILDING_INDS[ii++] = vbase +  8; BUILDING_INDS[ii++] = vbase + 10; BUILDING_INDS[ii++] = vbase + 11;
    BUILDING_INDS[ii++] = vbase + 12; BUILDING_INDS[ii++] = vbase + 13; BUILDING_INDS[ii++] = vbase + 14;
    BUILDING_INDS[ii++] = vbase + 12; BUILDING_INDS[ii++] = vbase + 14; BUILDING_INDS[ii++] = vbase + 15;
    BUILDING_INDS[ii++] = vbase + 16; BUILDING_INDS[ii++] = vbase + 17; BUILDING_INDS[ii++] = vbase + 18;
    BUILDING_INDS[ii++] = vbase + 16; BUILDING_INDS[ii++] = vbase + 18; BUILDING_INDS[ii++] = vbase + 19;
    BUILDING_INDS[ii++] = vbase + 20; BUILDING_INDS[ii++] = vbase + 21; BUILDING_INDS[ii++] = vbase + 22;
    BUILDING_INDS[ii++] = vbase + 20; BUILDING_INDS[ii++] = vbase + 22; BUILDING_INDS[ii++] = vbase + 23;
    vbase += 24;
  }
}
const matBuildingMesh = createMeshExplicit(BUILDING_VERTS, _bvc, BUILDING_INDS, _bic);

// ---- Phase 10 glass — second material consumer, proves the ABI works -----
// Second material using the Phase 4b refractive path (scene-colour snapshot
// at group 4). No Gerstner waves; flat normal, heavier Fresnel so edges
// reflect the sky and the centre of the pane stays clearest. Placed in the
// south-wall door opening of the h1 house (gap at x=-22..-20, y=0..2.4,
// z=-10) so the player can see the interior refracted through it on the
// approach. Phase 10's acceptance criterion: no engine change between
// Phase 9 and 10 — only TypeScript.

const GLASS_WGSL =
  '#include "material_abi.wgsl"\n' +
  '#include "common/pbr.wgsl"\n' +
  '\n' +
  'struct GlassVsOut {\n' +
  '  @builtin(position) clip_pos: vec4<f32>,\n' +
  '  @location(0) world_pos:    vec3<f32>,\n' +
  '  @location(1) world_normal: vec3<f32>,\n' +
  '  @location(2) screen_uv:    vec2<f32>,\n' +
  '};\n' +
  '\n' +
  '@vertex\n' +
  'fn vs_main(in: VertexInput) -> GlassVsOut {\n' +
  '  var out: GlassVsOut;\n' +
  '  let world  = draw.model * vec4<f32>(in.position, 1.0);\n' +
  '  out.world_pos    = world.xyz;\n' +
  '  out.world_normal = normalize((draw.model * vec4<f32>(in.normal, 0.0)).xyz);\n' +
  '  out.clip_pos     = view.view_proj * world;\n' +
  '  out.screen_uv    = out.clip_pos.xy / out.clip_pos.w * vec2<f32>(0.5, -0.5) + vec2<f32>(0.5);\n' +
  '  return out;\n' +
  '}\n' +
  '\n' +
  '@fragment\n' +
  'fn fs_main(in: GlassVsOut) -> @location(0) vec4<f32> {\n' +
  '  let n = normalize(in.world_normal);\n' +
  '  let v = normalize(view.camera_pos.xyz - in.world_pos);\n' +
  '\n' +
  '  // Subtle refraction through the pane — glass bends light far less\n' +
  '  // than water, so 0.008 gets the parallax look without distorting the\n' +
  '  // scene into abstraction.\n' +
  '  let refract_uv = clamp(in.screen_uv + n.xy * 0.008,\n' +
  '                         vec2<f32>(0.001), vec2<f32>(0.999));\n' +
  '  let refracted  = textureSampleLevel(scene_color_tex, scene_color_samp, refract_uv, 0.0).rgb;\n' +
  '\n' +
  '  // Sharp sky reflection on the front face — clear glass is nearly\n' +
  '  // mirror-smooth at grazing angles.\n' +
  '  let r   = reflect(-v, n);\n' +
  '  let sky = sample_env(r, 0.5);\n' +
  '\n' +
  '  // Glass F0 is ~0.04. Schlick Fresnel — grazing angles turn\n' +
  '  // near-mirror, face-on is ~4%.\n' +
  '  let cos_theta = max(dot(n, v), 0.0);\n' +
  '  let fresnel   = 0.04 + (1.0 - 0.04) * pow(1.0 - cos_theta, 5.0);\n' +
  '\n' +
  '  // Faint cyan tint in the transmitted colour — window glass is never\n' +
  '  // perfectly neutral.\n' +
  '  let tinted = refracted * vec3<f32>(0.92, 0.96, 0.98);\n' +
  '  let glass  = mix(tinted, sky, fresnel);\n' +
  '\n' +
  '  // Alpha follows the Fresnel curve: face-on we see mostly through,\n' +
  '  // glancing angles go opaque with reflection.\n' +
  '  // Face-on: ~25% alpha (mostly transparent, slight tint). Grazing:\n' +
  '  // near-opaque as the reflection dominates.\n' +
  '  let alpha = 0.25 + 0.75 * fresnel;\n' +
  '  return vec4<f32>(glass, alpha);\n' +
  '}\n';
// Phase 6 — glass also lives on disk + hot-reloadable. Inline WGSL
// retained as a fallback for binary-only ship builds.
const matGlassFromFile = compileMaterialFromFile(
  'assets/materials/glass.wgsl', 'refractive',
);
const matGlass = matGlassFromFile > 0
  ? matGlassFromFile
  : compileRefractiveMaterial(GLASS_WGSL);

// Glass pane mesh — a single 2m × 2.4m quad on the XY plane, normal +Z.
// Subdivided 1×1 (two triangles) because glass has no per-vertex
// displacement; the shader runs entirely in fs_main.
const GLASS_W = 2.0;   // metres along X — door opening width
const GLASS_H = 2.4;   // metres along Y — door opening height
const GLASS_VERTS: number[] = [
  // pos(3)         normal(3)   color(4)     uv(2)
  -GLASS_W*0.5, 0,        0,  0,0,1,  1,1,1,1,  0,0,
   GLASS_W*0.5, 0,        0,  0,0,1,  1,1,1,1,  1,0,
   GLASS_W*0.5, GLASS_H,  0,  0,0,1,  1,1,1,1,  1,1,
  -GLASS_W*0.5, GLASS_H,  0,  0,0,1,  1,1,1,1,  0,1,
];
// CCW from +Z so the pane is front-facing when viewed from outside.
const GLASS_INDS: number[] = [0, 1, 2, 0, 2, 3];
const matGlassMesh = createMesh(GLASS_VERTS, GLASS_INDS);

// ---- Muzzle flash — additive-bucket material (Bucket::Additive) ----------
// First consumer of the additive blend path. Fragment fakes a
// volumetric warm flash inside a unit cube via radial falloff from
// local-space centre. Per-draw tint alpha carries the flash intensity.
const matMuzzleFlash = compileMaterialFromFile(
  'assets/materials/muzzle_flash.wgsl', 'additive',
);
const matMuzzleFlashMesh = genMeshCube(1, 1, 1);

// ---- Unvanquished aliens (5 kinds, M3 model + M5 AI + M6 pool) ------------
// Each kind has its own GLB model and stat line. Kinds and models line up
// with the Unvanquished alien classes:
//   0 = dretch   — small, fast, low HP, moderate damage
//   1 = mantis   — quick, medium HP
//   2 = marauder — medium all-round
//   3 = dragoon  — heavier, slower, hits hard
//   4 = tyrant   — boss tier; rare, big, tanky
const KIND_COUNT = 5;
const KIND_NAME  = ['DRETCH', 'MANTIS', 'MARAUDER', 'DRAGOON', 'TYRANT'];
const mdlAliens  = [
  loadModel('assets/models/enemy_dretch.glb'),
  loadModel('assets/models/enemy_mantis.glb'),
  loadModel('assets/models/enemy_marauder.glb'),
  loadModel('assets/models/enemy_dragoon.glb'),
  loadModel('assets/models/enemy_tyrant.glb'),
];
const animAliens = [
  loadModelAnimation('assets/models/enemy_dretch.glb'),
  loadModelAnimation('assets/models/enemy_mantis.glb'),
  loadModelAnimation('assets/models/enemy_marauder.glb'),
  loadModelAnimation('assets/models/enemy_dragoon.glb'),
  loadModelAnimation('assets/models/enemy_tyrant.glb'),
];
// Animation indices — IQE declaration order. Dretch (and most others):
// 0 stand, 1 attack, 4 die, 14 run, 20 walk. We map gameplay -> anim idx.
const ANIM_WALK_IDX   = [14, 14, 14, 14, 14];
const ANIM_ATTACK_IDX = [1, 1, 1, 1, 1];
// Procedural motion parameters (cheap substitute for skeletal animation).
// Each enemy has a phase accumulator — sinusoids on top give a bob + side-
// sway while walking, and a forward-lunge while attacking.
const WALK_BOB_Y = 0.12;       // metres
const WALK_BOB_RATE = 9.0;     // rad/s
const WALK_TILT = 0.06;        // unused; kept for future side-sway
const ATTACK_LUNGE_AMP = 0.25; // m forward during attack
// Per-kind tuning. Collider half-extents are generous (taller than the visual
// model) so horizontal aim at any range connects.
const KIND_SCALE = [1.6, 1.6, 1.9, 2.4, 3.0];
const KIND_HX    = [1.0, 0.9, 1.2, 1.4, 1.8];
const KIND_HY    = [1.0, 1.0, 1.2, 1.5, 2.0];
const KIND_HZ    = [1.1, 1.0, 1.3, 1.6, 2.0];
const KIND_Y_OFF = [1.0, 1.0, 1.2, 1.5, 2.0];
const KIND_SPEED = [3.0, 4.5, 3.5, 2.5, 2.2];
const KIND_HP    = [3,   4,   6,   10,  20];
const KIND_DMG   = [12,  10,  16,  22,  35];
const KIND_CD    = [0.9, 0.7, 0.9, 1.1, 1.3];
const KIND_MELEE = [2.0, 2.0, 2.3, 2.6, 3.0];
const DRETCH_HIT_FLASH = 0.18;
const WHITE = { r: 255, g: 255, b: 255, a: 255 };

// Enemy pool — each slot is permanently tied to one kind because Jolt body
// shapes can't be swapped in-place. BODIES_PER_KIND dormant bodies per kind
// give us a fixed pool of MAX_ENEMIES = KIND_COUNT * BODIES_PER_KIND.
const BODIES_PER_KIND = 2;
const MAX_ENEMIES = KIND_COUNT * BODIES_PER_KIND;
const enX = new Array<number>(MAX_ENEMIES);
const enY = new Array<number>(MAX_ENEMIES);
const enZ = new Array<number>(MAX_ENEMIES);
const enHP = new Array<number>(MAX_ENEMIES);
const enAlive = new Array<number>(MAX_ENEMIES);
const enKind  = new Array<number>(MAX_ENEMIES);
const enAttackCD = new Array<number>(MAX_ENEMIES);
const enFlashT = new Array<number>(MAX_ENEMIES);
const enPhase = new Array<number>(MAX_ENEMIES);        // walk-cycle phase accumulator
const enBody: BodyHandle[] = new Array<BodyHandle>(MAX_ENEMIES);
for (let k = 0; k < KIND_COUNT; k++) {
  const shape = boxShape(vec3(KIND_HX[k], KIND_HY[k], KIND_HZ[k]));
  for (let j = 0; j < BODIES_PER_KIND; j++) {
    const i = k * BODIES_PER_KIND + j;
    enX[i] = 0; enY[i] = -100; enZ[i] = 0;
    enHP[i] = 0; enAlive[i] = 0; enAttackCD[i] = 0; enFlashT[i] = 0;
    enPhase[i] = Math.random() * Math.PI * 2;   // stagger the bob phases
    enKind[i] = k;
    enBody[i] = createBody(physics, shape, {
      motionType: MotionType.KINEMATIC,
      position: vec3(0, -100, 0),
      objectLayer: Layer.MOVING,
    });
  }
}

// Wave director — spawners, wave plan, and kind sequence all come from the
// world file (see enemy_spawner + wave_config entities in arena_02.world.json).
const spawnerX = W.SPAWNER_X;
const spawnerZ = W.SPAWNER_Z;
const wavePlan = W.WAVE_SIZE;
const WAVE_OFFS = W.WAVE_OFFS;
const WAVE_KINDS = W.WAVE_KIND;
const WAVE_SPAWN_DELAY = 1.2;
const WAVE_BREAK_DELAY = 2.5;
const MAX_CONCURRENT = 4;

let waveIdx = 0;
let waveSpawned = 0;
let waveBreakTimer = WAVE_BREAK_DELAY;
let spawnTimer = 0;
let gameWon = false;

function countAlive(): number {
  let c = 0;
  for (let i = 0; i < MAX_ENEMIES; i++) if (enAlive[i] > 0) c = c + 1;
  return c;
}

function findDormantSlot(kind: number): number {
  for (let j = 0; j < BODIES_PER_KIND; j++) {
    const i = kind * BODIES_PER_KIND + j;
    if (enAlive[i] === 0) return i;
  }
  return -1;
}

function spawnEnemy(): void {
  const kind = WAVE_KINDS[WAVE_OFFS[waveIdx] + waveSpawned];
  const slot = findDormantSlot(kind);
  if (slot < 0) return;   // all bodies of this kind busy; retry next tick
  const sp = waveSpawned % 4;
  enX[slot] = spawnerX[sp];
  enY[slot] = 0;
  enZ[slot] = spawnerZ[sp];
  enHP[slot] = KIND_HP[kind];
  enAlive[slot] = 1;
  enAttackCD[slot] = 0;
  enFlashT[slot] = 0;
  enPhase[slot] = Math.random() * Math.PI * 2;
  setBodyPosition(enBody[slot],
    vec3(enX[slot], enY[slot] + KIND_Y_OFF[kind], enZ[slot]), true);
  waveSpawned = waveSpawned + 1;
}

// ---- Weapon + combat state (M4 / M5 / M6 / M7) ----------------------------
const PLAYER_HP_MAX = 100;
const FIRE_RANGE = 60.0;

// Weapon registry
const WEAPON_RIFLE = 0;
const WEAPON_BLASTER = 1;
const WEAPON_NAMES = ['RIFLE', 'BLASTER'];
const RIFLE_MAG = 30;
const BLASTER_MAG = 20;
const RIFLE_FIRE_CD = 0.10;   // full-auto, ~600 rpm
const BLASTER_FIRE_CD = 0.35; // tap-fire
const RIFLE_DAMAGE = 1;
const BLASTER_DAMAGE = 2;
const BLASTER_PROJ_SPEED = 40.0;
const BLASTER_PROJ_LIFE = 2.5;
const BLASTER_PROJ_GRAVITY = 9.0;   // m/s^2 — lighter than world gravity for a softer arc

let currentWeapon = WEAPON_RIFLE;
let rifleAmmo = RIFLE_MAG;
let blasterAmmo = BLASTER_MAG;
let fireCD = 0;

let playerHP = PLAYER_HP_MAX;
let gameOver = false;
const MUZZLE_FLASH_DUR = 0.08;
let muzzleFlashT = 0;
let damageFlashT = 0;
let shotsFired = 0;
let shotsHit = 0;

// ---- Projectile pool (M7) -------------------------------------------------
// Fixed-size ring buffer. Each slot stores position, velocity, and
// remaining life. pLife = 0 means the slot is free. Projectiles advance
// each frame via segment-raycast so they can't tunnel through walls.
const MAX_PROJ = 16;
const pX  = new Array<number>(MAX_PROJ);
const pY  = new Array<number>(MAX_PROJ);
const pZ  = new Array<number>(MAX_PROJ);
const pVX = new Array<number>(MAX_PROJ);
const pVY = new Array<number>(MAX_PROJ);
const pVZ = new Array<number>(MAX_PROJ);
const pLife = new Array<number>(MAX_PROJ);
for (let i = 0; i < MAX_PROJ; i++) pLife[i] = 0;
let projNext = 0;

function spawnProjectile(x: number, y: number, z: number,
                         vx: number, vy: number, vz: number): void {
  pX[projNext] = x; pY[projNext] = y; pZ[projNext] = z;
  pVX[projNext] = vx; pVY[projNext] = vy; pVZ[projNext] = vz;
  pLife[projNext] = BLASTER_PROJ_LIFE;
  projNext = (projNext + 1) % MAX_PROJ;
}

// ---- Ammo pickups (M7) ----------------------------------------------------
// Fixed positions around the arena. Walk within PICKUP_RADIUS to collect;
// respawn after PICKUP_RESPAWN seconds so long runs don't starve for ammo.
const PICKUP_RIFLE = 0;
const PICKUP_BLASTER = 1;
const PICKUP_RIFLE_AMT = 15;
const PICKUP_BLASTER_AMT = 8;
const PICKUP_RADIUS = 1.4;
const PICKUP_RESPAWN = 18.0;
const pickupKind = W.PICKUP_KIND;      // 0 = rifle, 1 = blaster (see build-world.ts)
const pickupX    = W.PICKUP_X;
const pickupZ    = W.PICKUP_Z;
const PICKUP_COUNT = W.PICKUP_COUNT;
const pickupActive   = new Array<number>(PICKUP_COUNT);
const pickupRespawnT = new Array<number>(PICKUP_COUNT);
for (let i = 0; i < PICKUP_COUNT; i++) { pickupActive[i] = 1; pickupRespawnT[i] = 0; }

function despawnAllEnemies(): void {
  for (let i = 0; i < MAX_ENEMIES; i++) {
    enAlive[i] = 0;
    enHP[i] = 0;
    enAttackCD[i] = 0;
    enFlashT[i] = 0;
    enPhase[i] = Math.random() * Math.PI * 2;
    enX[i] = 0; enY[i] = -100; enZ[i] = 0;
    setBodyPosition(enBody[i], vec3(0, -100, 0), false);
  }
}

function resetRun(): void {
  currentWeapon = WEAPON_RIFLE;
  rifleAmmo = RIFLE_MAG;
  blasterAmmo = BLASTER_MAG;
  fireCD = 0;
  playerHP = PLAYER_HP_MAX;
  gameOver = false;
  gameWon = false;
  muzzleFlashT = 0;
  damageFlashT = 0;
  shotsFired = 0;
  shotsHit = 0;
  waveIdx = 0;
  waveSpawned = 0;
  waveBreakTimer = WAVE_BREAK_DELAY;
  spawnTimer = 0;
  for (let i = 0; i < MAX_PROJ; i++) pLife[i] = 0;
  for (let i = 0; i < PICKUP_COUNT; i++) { pickupActive[i] = 1; pickupRespawnT[i] = 0; }
  despawnAllEnemies();
}

// Impact sparks — fixed ring buffer to avoid array growth in the hot loop.
const SPARK_MAX = 16;
const sparkX  = new Array<number>(SPARK_MAX);
const sparkY  = new Array<number>(SPARK_MAX);
const sparkZ  = new Array<number>(SPARK_MAX);
const sparkT  = new Array<number>(SPARK_MAX);   // seconds of life remaining; 0 = slot free
for (let i = 0; i < SPARK_MAX; i++) sparkT[i] = 0;
let sparkNext = 0;

function spawnSpark(p: Vec3): void {
  sparkX[sparkNext] = p.x;
  sparkY[sparkNext] = p.y;
  sparkZ[sparkNext] = p.z;
  sparkT[sparkNext] = 0.35;
  sparkNext = (sparkNext + 1) % SPARK_MAX;
}

let cursorLocked = true;
let screenshotSeq = 0;
let perfOverlayOn = false;
disableCursor();

// ---- M8 polish: post-FX ---------------------------------------------------
// Called once at startup — these are cheap, always-on stylistic passes.
setVignette(0.4, 0.55);    // darken frame edges
setFilmGrain(0.06);        // very subtle noise


// ---- Self-test harness ----------------------------------------------------
// When SELFTEST is true the game auto-fires a shot on frame 30, screenshots
// the scene on frame 60, and exits on frame 90. Used while investigating the
// engine's deferred-render green-screen bug — kept dormant for future debug.
const SELFTEST = true;
let testFrame = 0;


while (!windowShouldClose()) {
  beginDrawing();
  const dt = getDeltaTime();
  const sw = getScreenWidth();
  const sh = getScreenHeight();
  updateMusicStream(musicAmbient);

  // Tab toggles cursor capture so you can free the mouse to screenshot etc.
  if (isKeyPressed(Key.TAB)) {
    cursorLocked = !cursorLocked;
    if (cursorLocked) disableCursor();
    else enableCursor();
  }
  // F12 takes a screenshot (sequential filenames)
  if (isKeyPressed(Key.F12)) {
    screenshotSeq = screenshotSeq + 1;
    takeScreenshot('shooter_' + screenshotSeq + '.png');
  }
  // F3 toggles the Phase 8 profiler overlay.
  if (isKeyPressed(Key.F3)) {
    perfOverlayOn = !perfOverlayOn;
    setProfilerEnabled(perfOverlayOn);
  }

  const input = readInput();
  testFrame = testFrame + 1;
  // Selftest: drive the player forward so screenshots can verify
  // walk direction. Runs before the player controller update so
  // the override actually reaches updatePlayerController.
  if (SELFTEST && testFrame >= 20) input.moveZ = -1;
  // Only apply mouse look when cursor is captured — avoids jumpy yaw/pitch
  // when the user is moving the mouse outside the window. The first ~10
  // frames after window creation often report giant mouse deltas (system
  // cursor settling into the captured state), which can fling the camera
  // to a useless angle before the player even sees the scene.
  if (cursorLocked && testFrame > 10) {
    CAM[0] = CAM[0] + input.lookX;
    const np = CAM[1] + input.lookY;
    CAM[1] = np < TP_PITCH_MIN ? TP_PITCH_MIN : (np > TP_PITCH_MAX ? TP_PITCH_MAX : np);
  }

  // Restart on R when the run has ended (died or won); otherwise R reloads
  // the currently-equipped weapon.
  if (isKeyPressed(Key.R)) {
    if (gameOver || gameWon) resetRun();
    else if (currentWeapon === WEAPON_RIFLE) rifleAmmo = RIFLE_MAG;
    else blasterAmmo = BLASTER_MAG;
  }
  // Weapon switching with 1/2.
  if (isKeyPressed(Key.ONE))  { currentWeapon = WEAPON_RIFLE;   fireCD = 0; }
  if (isKeyPressed(Key.TWO))  { currentWeapon = WEAPON_BLASTER; fireCD = 0; }

  // Freeze player movement while dead or after victory; physics still steps.
  if (!gameOver && !gameWon) {
    const yawNow = CAM[0];
    const fwd = vec3(Math.sin(yawNow), 0, -Math.cos(yawNow));
    const rgt = vec3(Math.cos(yawNow), 0, Math.sin(yawNow));
    updatePlayerController(dt, input.moveX, input.moveZ, fwd, rgt, input.jump);
  }
  stepPhysics(physics, dt);

  // Phase 7 — footstep / water-entry splats. When the player is
  // inside the river band, submit an impulse at their XZ every
  // frame they're moving. The compute pass decays these over ~2s
  // so the water shader can render persistent ripples.
  {
    const pp = playerPosition();
    const inRiver = pp.z > WATER_CZ - WATER_D * 0.5 &&
                    pp.z < WATER_CZ + WATER_D * 0.5 &&
                    Math.abs(pp.x) < WATER_W * 0.5;
    const moving = Math.abs(input.moveX) + Math.abs(input.moveZ) > 0.1;
    if (inRiver && moving) {
      splatImpulse(pp.x, pp.z, 1.2, 0.6);
    }
  }

  // Smooth orbit camera follow after physics step.
  // Inline orbit-camera follow.
  {
    const pp0 = playerPosition();
    const ya = CAM[0], pi = CAM[1];
    const cpi = Math.cos(pi), spi = Math.sin(pi);
    const fX = pp0.x;
    const fY = pp0.y + TP_EYE_HEIGHT;
    const fZ = pp0.z;
    const wX = fX - Math.sin(ya) * cpi * TP_ORBIT_DIST;
    const wY = fY + spi * TP_ORBIT_DIST;
    const wZ = fZ + Math.cos(ya) * cpi * TP_ORBIT_DIST;
    if (CAM[8] === 0) {
      CAM[2] = wX; CAM[3] = wY; CAM[4] = wZ;
      CAM[5] = fX; CAM[6] = fY; CAM[7] = fZ;
      CAM[8] = 1;
    } else {
      const t = 1 - Math.exp(-TP_SMOOTH * dt);
      CAM[2] = CAM[2] + (wX - CAM[2]) * t;
      CAM[3] = CAM[3] + (wY - CAM[3]) * t;
      CAM[4] = CAM[4] + (wZ - CAM[4]) * t;
      CAM[5] = CAM[5] + (fX - CAM[5]) * t;
      CAM[6] = CAM[6] + (fY - CAM[6]) * t;
      CAM[7] = CAM[7] + (fZ - CAM[7]) * t;
    }
  }
  playerAnimT = playerAnimT + dt;

  // ---- Enemy AI + wave director (M5 / M6) -------------------------------
  if (!gameOver && !gameWon) {
    const pp = playerPosition();
    for (let i = 0; i < MAX_ENEMIES; i++) {
      if (enAlive[i] === 0) continue;
      const k = enKind[i];
      const dx = pp.x - enX[i];
      const dz = pp.z - enZ[i];
      const dist = Math.sqrt(dx * dx + dz * dz);
      if (dist > KIND_MELEE[k]) {
        const step = KIND_SPEED[k] * dt;
        const move = step < dist ? step : dist;
        enX[i] = enX[i] + (dx / dist) * move;
        enZ[i] = enZ[i] + (dz / dist) * move;
        setBodyPosition(enBody[i],
          vec3(enX[i], enY[i] + KIND_Y_OFF[k], enZ[i]), true);
      } else if (enAttackCD[i] <= 0) {
        playerHP = playerHP - KIND_DMG[k];
        damageFlashT = 0.5;
        enAttackCD[i] = KIND_CD[k];
        playSound(sfxAttack);
        if (playerHP <= 0) { playerHP = 0; gameOver = true; }
      }
      if (enAttackCD[i] > 0) enAttackCD[i] = enAttackCD[i] - dt;
      if (enFlashT[i]   > 0) enFlashT[i]   = enFlashT[i]   - dt;
      enPhase[i] = enPhase[i] + dt;   // seconds into current animation
    }

    // Pickups — proximity collect, respawn after delay.
    for (let i = 0; i < PICKUP_COUNT; i++) {
      if (pickupActive[i] === 0) {
        pickupRespawnT[i] = pickupRespawnT[i] - dt;
        if (pickupRespawnT[i] <= 0) pickupActive[i] = 1;
        continue;
      }
      const pdx = pp.x - pickupX[i];
      const pdz = pp.z - pickupZ[i];
      if (pdx * pdx + pdz * pdz < PICKUP_RADIUS * PICKUP_RADIUS) {
        if (pickupKind[i] === PICKUP_RIFLE) {
          rifleAmmo = Math.min(RIFLE_MAG, rifleAmmo + PICKUP_RIFLE_AMT);
        } else {
          blasterAmmo = Math.min(BLASTER_MAG, blasterAmmo + PICKUP_BLASTER_AMT);
        }
        pickupActive[i] = 0;
        pickupRespawnT[i] = PICKUP_RESPAWN;
        playSound(sfxPickup);
      }
    }

    // Wave director
    const alive = countAlive();
    if (waveIdx < wavePlan.length) {
      if (waveBreakTimer > 0) {
        waveBreakTimer = waveBreakTimer - dt;
      } else {
        const waveSize = wavePlan[waveIdx];
        if (waveSpawned < waveSize && alive < MAX_CONCURRENT) {
          spawnTimer = spawnTimer - dt;
          if (spawnTimer <= 0) {
            spawnEnemy();
            spawnTimer = WAVE_SPAWN_DELAY;
          }
        }
        if (waveSpawned >= waveSize && alive === 0) {
          waveIdx = waveIdx + 1;
          waveSpawned = 0;
          waveBreakTimer = WAVE_BREAK_DELAY;
          if (waveIdx >= wavePlan.length) gameWon = true;
        }
      }
    }
  }

  // testFrame is incremented above the input block so the mouse-settle
  // grace period uses the same counter.
  let forceFire = false;
  if (SELFTEST) {
    waveBreakTimer = 9999;
    if (testFrame < 5) { CAM[0] = 0; CAM[1] = 0.35; CAM[8] = 0; }
    if (testFrame === 5) {
      // Manually spawn ONE dretch off to the side, stays idle.
      enX[0] = -6; enY[0] = 0; enZ[0] = -6;
      enHP[0] = 3; enAlive[0] = 1; enAttackCD[0] = 999;
      setBodyPosition(enBody[0], vec3(-6, KIND_Y_OFF[0], -6), true);
    }
    if (testFrame === 30)  { screenshotSeq++; takeScreenshot('shooter_selftest_' + screenshotSeq + '_t0_5s.png'); }
    if (testFrame === 180) { screenshotSeq++; takeScreenshot('shooter_selftest_' + screenshotSeq + '_t3_0s.png'); }
    if (testFrame === 185) { break; }
  }

  // ---- Fire (M4 / M7) ---------------------------------------------------
  if (fireCD > 0) fireCD = fireCD - dt;
  const combatActive = !gameOver && !gameWon && cursorLocked;
  const isRifle    = currentWeapon === WEAPON_RIFLE;
  const haveAmmo   = isRifle ? rifleAmmo > 0 : blasterAmmo > 0;
  // Rifle = full-auto (mouse held); blaster = tap (press edge only).
  const fireIntent = combatActive && haveAmmo && fireCD <= 0 &&
                     (isRifle ? input.fireDown : input.firePressed);
  if (fireIntent || (forceFire && haveAmmo && combatActive)) {
    shotsFired = shotsFired + 1;
    muzzleFlashT = MUZZLE_FLASH_DUR;
    playSound(sfxFire);
    // Third-person aiming: the crosshair is at screen centre, so
    // trace the camera-forward line out to a far point, treat that
    // as the aim target, and fire from the player's shoulder toward
    // it. This way visible tracers / sparks line up with the gun
    // barrel in the world, not with the orbit-camera position. The
    // parallax between camera ray and muzzle ray is tiny at normal
    // engagement ranges and is what gives the shot its "from the
    // player" feel.
    const camOriginV = vec3(CAM[2], CAM[3], CAM[4]);
    const adx = CAM[5] - CAM[2], ady = CAM[6] - CAM[3], adz = CAM[7] - CAM[4];
    const alen = Math.sqrt(adx*adx + ady*ady + adz*adz);
    const camFwd = alen > 0 ? vec3(adx/alen, ady/alen, adz/alen) : vec3(0, 0, -1);
    const aimTargetFar = 200;
    const tgtX = camOriginV.x + camFwd.x * aimTargetFar;
    const tgtY = camOriginV.y + camFwd.y * aimTargetFar;
    const tgtZ = camOriginV.z + camFwd.z * aimTargetFar;
    // Muzzle = player shoulder offset (matches the drawn weapon).
    const ppF = playerPosition();
    const sy = Math.sin(CAM[0]), cy = Math.cos(CAM[0]);
    const originX = ppF.x + cy * 0.30 + sy * 0.60;
    const originY = ppF.y + 0.95;
    const originZ = ppF.z + sy * 0.30 + (-cy) * 0.60;
    const mdx = tgtX - originX, mdy = tgtY - originY, mdz = tgtZ - originZ;
    const mlen = Math.sqrt(mdx*mdx + mdy*mdy + mdz*mdz);
    const aim = mlen > 0 ? vec3(mdx/mlen, mdy/mlen, mdz/mlen) : camFwd;

    if (isRifle) {
      rifleAmmo = rifleAmmo - 1;
      fireCD = RIFLE_FIRE_CD;
      const hit = raycast(physics, vec3(originX, originY, originZ), aim,
                          FIRE_RANGE, ALL_LAYERS_MASK);
      if (hit) {
        shotsHit = shotsHit + 1;
        spawnSpark(hit.point);
        for (let i = 0; i < MAX_ENEMIES; i++) {
          if (enAlive[i] > 0 && hit.body === enBody[i]) {
            enHP[i] = enHP[i] - RIFLE_DAMAGE;
            enFlashT[i] = DRETCH_HIT_FLASH;
            if (enHP[i] <= 0) {
              enAlive[i] = 0;
              enY[i] = -100;
              setBodyPosition(enBody[i], vec3(enX[i], -100, enZ[i]), false);
              playSound(sfxAttack);   // reuse clank as death thud
            }
            break;
          }
        }
      }
    } else {
      blasterAmmo = blasterAmmo - 1;
      fireCD = BLASTER_FIRE_CD;
      spawnProjectile(originX, originY, originZ,
                      aim.x * BLASTER_PROJ_SPEED,
                      aim.y * BLASTER_PROJ_SPEED,
                      aim.z * BLASTER_PROJ_SPEED);
    }
  }

  // ---- Projectile update (M7) -------------------------------------------
  // Apply gravity, then segment-raycast from old pos to new pos so fast or
  // arcing shots can't tunnel through walls or enemy colliders.
  for (let i = 0; i < MAX_PROJ; i++) {
    if (pLife[i] <= 0) continue;
    pVY[i] = pVY[i] - BLASTER_PROJ_GRAVITY * dt;
    const ox = pX[i], oy = pY[i], oz = pZ[i];
    const nx = ox + pVX[i] * dt;
    const ny = oy + pVY[i] * dt;
    const nz = oz + pVZ[i] * dt;
    const sx = nx - ox, sy = ny - oy, sz = nz - oz;
    const segLen = Math.sqrt(sx * sx + sy * sy + sz * sz);
    const inv = segLen > 0 ? 1 / segLen : 0;
    const hit = raycast(physics, vec3(ox, oy, oz),
                        vec3(sx * inv, sy * inv, sz * inv),
                        segLen, ALL_LAYERS_MASK);
    if (hit) {
      spawnSpark(hit.point);
      for (let j = 0; j < MAX_ENEMIES; j++) {
        if (enAlive[j] > 0 && hit.body === enBody[j]) {
          enHP[j] = enHP[j] - BLASTER_DAMAGE;
          enFlashT[j] = DRETCH_HIT_FLASH;
          shotsHit = shotsHit + 1;
          if (enHP[j] <= 0) {
            enAlive[j] = 0;
            enY[j] = -100;
            setBodyPosition(enBody[j], vec3(enX[j], -100, enZ[j]), false);
            playSound(sfxAttack);
          }
          break;
        }
      }
      pLife[i] = 0;
    } else {
      pX[i] = nx; pY[i] = ny; pZ[i] = nz;
      pLife[i] = pLife[i] - dt;
    }
  }
  if (muzzleFlashT > 0) muzzleFlashT = muzzleFlashT - dt;
  if (damageFlashT > 0) damageFlashT = damageFlashT - dt;
  for (let i = 0; i < SPARK_MAX; i++) {
    if (sparkT[i] > 0) sparkT[i] = sparkT[i] - dt;
  }

  // The HDR sky pass overrides the clear colour, but leave this in
  // as a fallback when the HDR file is missing.
  clearBackground({ r: Math.floor(W.ENV_SKY_R * 255),
                    g: Math.floor(W.ENV_SKY_G * 255),
                    b: Math.floor(W.ENV_SKY_B * 255), a: 255 });
  // Per-frame light overrides removed — they were hardcoded values
  // that masked the world-data setAmbientLight/setDirectionalLight
  // run at startup, and IBL now provides the ambient diffuse anyway.

  beginMode3D({
    position: vec3(CAM[2], CAM[3], CAM[4]),
    target:   vec3(CAM[5], CAM[6], CAM[7]),
    up: vec3(0, 1, 0),
    fovy: TP_FOVY,
    projection: 0,
  });

  // Muzzle flare point light — sits just past the barrel tip so
  // the warm splash of light hits the gun body and the floor in
  // front of the player when firing.
  if (muzzleFlashT > 0) {
    const pp = playerPosition();
    const sy = Math.sin(CAM[0]), cy = Math.cos(CAM[0]);
    const tipOffset = currentWeapon === WEAPON_RIFLE ? 0.78 : 0.43;
    const mx = pp.x + cy * 0.30 + sy * tipOffset;
    const my = pp.y + 0.95;
    const mz = pp.z + sy * 0.30 + (-cy) * tipOffset;
    const k = muzzleFlashT / MUZZLE_FLASH_DUR;
    addPointLight(mx, my, mz, 6, 1.0, 0.85, 0.5, 4.0 * k);
  }

  // ---- World: static meshes + water + lights (all from generated/world.ts) -
  // Ground plate — big drawCube beneath the terrain mesh so the full
  // 80×80 collider floor reads as a solid plane even where the hills
  // haven't lifted anything off it. Matches COLLIDER[0] (the plaza floor).
  drawCube(vec3(W.COLLIDER_X[0], W.COLLIDER_Y[0], W.COLLIDER_Z[0]),
           W.COLLIDER_HALF_X[0] * 2, W.COLLIDER_HALF_Y[0] * 2, W.COLLIDER_HALF_Z[0] * 2,
           { r: 85, g: 95, b: 75, a: 255 });

  // Phase 9 — real river. Single drawMeshWithMaterial replaces the old
  // 1800-cube tessellated grid. Shader handles Gerstner-wave
  // displacement, per-vertex normal, Fresnel-blended refraction (from
  // the scene-colour snapshot), sky reflection, and foam on crests.
  if (matWater > 0) {
    drawMeshWithMaterial(matWater, matWaterMesh,
      vec3(WATER_CX, WATER_Y, WATER_CZ), 1.0,
      { r: 255, g: 255, b: 255, a: 255 });
  }
  // Phase 10 — glass pane in the south-wall door opening of house h1.
  // Second consumer of the material ABI, proves the infrastructure
  // works for a different shader without any engine change.
  if (matGlass > 0) {
    drawMeshWithMaterial(matGlass, matGlassMesh,
      vec3(-21, 0, -10), 1.0,
      { r: 255, g: 255, b: 255, a: 255 });
  }
  // Tier 2b — grass scatter. One drawMeshWithMaterial covers all
  // ~4000 blades; wind sway happens in the vertex shader from
  // frame.time + per-blade world XZ.
  if (matGrass > 0) {
    drawMeshWithMaterial(matGrass, matGrassMesh,
      vec3(0, 0, 0), 1.0,
      { r: 255, g: 255, b: 255, a: 255 });
  }
  // Building stone — single drawMeshWithMaterial covers all
  // category-1 boxes; the noise + horizontal-band material in
  // the fragment turns them from flat beige into something that
  // reads as plastered stone.
  if (matBuilding > 0) {
    drawMeshWithMaterial(matBuilding, matBuildingMesh,
      vec3(0, 0, 0), 1.0,
      { r: 255, g: 255, b: 255, a: 255 });
  }
  // Static meshes — either drawModel for real GLBs, or coloured drawCube
  // for placeholder _gizmo_box.glb entries. MESH_CATEGORY drives the cube
  // tint (0 generic / 1 building / 2 terrain / 3 prop).
  for (let i = 0; i < W.MESH_COUNT; i++) {
    const mi = W.MESH_MODEL_IDX[i];
    if (W.MODEL_IS_BOX[mi] === 1) {
      // Buildings (category 1) are rendered through the baked
      // matBuilding mesh below — skip here to avoid double-draw.
      if (W.MESH_CATEGORY[i] === 1 && matBuilding > 0) continue;
      const c = W.MESH_CATEGORY[i];
      const col = { r: MESH_TINT_R[c], g: MESH_TINT_G[c], b: MESH_TINT_B[c], a: 255 };
      drawCube(vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
               W.MESH_COLLIDER_HX[i] * 2, W.MESH_COLLIDER_HY[i] * 2, W.MESH_COLLIDER_HZ[i] * 2,
               col);
    } else if (mi === terrainPropIdx && matTerrain > 0) {
      // Tier 2a — terrain via the colour-variation material. The
      // material runs in the opaque pass; passes Lambert against
      // PerView's directional sun + ambient, then writes both
      // albedo and hdr.
      drawMeshWithMaterial(matTerrain, meshModelHandles[mi] as any,
                vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
                W.MESH_SCALE[i], WHITE);
    } else if (mi === treePropIdx) {
      // Tier 3b — pick a tree variant + scale jitter from a stable
      // index hash. The Kenney tree GLBs have a much smaller
      // native size than the old prop_tree.glb cardboard, so the
      // world MESH_SCALE values (≈1.0) get a 2.5× multiplier on
      // top to reach garden-scale (~2.0–2.5 m tall trees).
      const v = treeVariants[i & 3];
      const scaleJitter = 0.85 + ((i * 17) & 31) / 100.0;  // 0.85 .. 1.16
      drawModel(v,
                vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
                W.MESH_SCALE[i] * scaleJitter * 2.5, WHITE);
    } else {
      drawModel(meshModelHandles[mi],
                vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
                W.MESH_SCALE[i], WHITE);
    }
  }
  // (Water rendering moved up — Phase 9 drawMeshWithMaterial replaces
  // the old cube-grid loop that used to live here.)
  // Point lights from the world file — static scene lights.
  for (let i = 0; i < W.LIGHT_COUNT; i++) {
    addPointLight(W.LIGHT_X[i], W.LIGHT_Y[i], W.LIGHT_Z[i],
                  W.LIGHT_RANGE[i],
                  W.LIGHT_R[i], W.LIGHT_G[i], W.LIGHT_B[i],
                  W.LIGHT_INT[i]);
  }

  // Player: skinned + animated. Face the camera's horizontal yaw (so the
  // character always looks "away from the camera"). Walk if input is
  // nonzero, idle otherwise. A debug sphere at the capsule centre is
  // always drawn as a fallback so the player's position is visible even
  // if the skinned model fails to render.
  {
    const pp = playerPosition();
    const moving = input.moveX !== 0 || input.moveZ !== 0;
    const camYaw = CAM[0];
    // Player_bsuit's rest pose faces +X in model space (Unvanquished
    // convention, preserved through our X90 Z-up→Y-up root fix).
    // Camera-yaw forward at yaw=0 is -Z, so rotate the model by
    // +π/2 about Y to line the character's front with the camera
    // direction. The bsuit's only "attack" animation is a melee
    // swing — a ranged shooter shouldn't use it; keep the walk/idle
    // pose and fake recoil + muzzle flash on the weapon itself.
    const modelYaw = camYaw + Math.PI / 2;
    const fsin = Math.sin(modelYaw);
    const fcos = -Math.cos(modelYaw);
    const panim = moving ? PLAYER_ANIM_WALK : PLAYER_ANIM_IDLE;
    updateModelAnimation(animPlayer, panim, playerAnimT, PLAYER_SCALE,
      pp.x, pp.y + PLAYER_MODEL_Y_OFFSET, pp.z, fsin, fcos);
    drawModel(mdlPlayer, vec3(pp.x, pp.y + PLAYER_MODEL_Y_OFFSET, pp.z),
              PLAYER_SCALE, WHITE);

    // Held weapon — sketched from cubes since we don't yet have a
    // converted tpweapon GLB. Rifle is a long grey body + thin
    // barrel; blaster is a short stubby pistol. Positioned at the
    // character's right shoulder. On fire the weapon recoils
    // backward for one MUZZLE_FLASH_DUR tick (≈0.08s) and a warm
    // flash sprite appears at the barrel tip — the exponential
    // falloff on recoilT reads as a snap-back rather than a slide.
    const shy = Math.sin(camYaw), chy = Math.cos(camYaw);
    const fx = shy;         // camera forward (horizontal) at this yaw
    const fz = -chy;
    const rx = chy;         // camera right
    const rz = shy;
    const recoilT = muzzleFlashT > 0 ? muzzleFlashT / MUZZLE_FLASH_DUR : 0;
    const recoilK = recoilT * recoilT;        // snappier than linear
    const recoilBack = recoilK * 0.18;        // metres pulled toward shooter
    const shoulder = vec3(
      pp.x + rx * 0.30 + fx * (0.15 - recoilBack),
      pp.y + 0.95,
      pp.z + rz * 0.30 + fz * (0.15 - recoilBack),
    );
    const bodyDark = { r: 55, g: 55, b: 60, a: 255 };
    const bodyMid  = { r: 90, g: 90, b: 100, a: 255 };
    let muzzleX = shoulder.x, muzzleY = shoulder.y, muzzleZ = shoulder.z;
    if (currentWeapon === WEAPON_RIFLE) {
      drawCube(shoulder, 0.12, 0.10, 0.55, bodyMid);
      const barrelLen = 0.45;
      const barrelX = shoulder.x + fx * barrelLen;
      const barrelY = shoulder.y;
      const barrelZ = shoulder.z + fz * barrelLen;
      drawCube(vec3(barrelX, barrelY, barrelZ), 0.06, 0.06, 0.35, bodyDark);
      muzzleX = shoulder.x + fx * (barrelLen + 0.18);
      muzzleY = shoulder.y;
      muzzleZ = shoulder.z + fz * (barrelLen + 0.18);
    } else {
      drawCube(shoulder, 0.10, 0.14, 0.22, bodyMid);
      const bx = shoulder.x + fx * 0.18;
      const bz = shoulder.z + fz * 0.18;
      drawCube(vec3(bx, shoulder.y + 0.02, bz), 0.05, 0.05, 0.15, bodyDark);
      muzzleX = shoulder.x + fx * 0.28;
      muzzleY = shoulder.y + 0.02;
      muzzleZ = shoulder.z + fz * 0.28;
    }

    // Muzzle flash — additive material via Bucket::Additive. The
    // shader builds a radial warm-yellow flash inside a unit cube;
    // per-draw tint alpha is the flash intensity that the shader
    // multiplies through. One drawMeshWithMaterial replaces the two
    // alpha-blended drawSphere calls — better HDR + tonemap response,
    // and a real test of the additive-bucket pipeline path.
    if (muzzleFlashT > 0 && matMuzzleFlash > 0) {
      const k = muzzleFlashT / MUZZLE_FLASH_DUR;
      // Quick puff-out: scale grows from 0.40 to ~0.55 m as the flash fades.
      const flashScale = 0.40 + (1 - k) * 0.18;
      const intensity255 = Math.min(255, Math.floor(k * 255));
      drawMeshWithMaterial(matMuzzleFlash, matMuzzleFlashMesh,
        vec3(muzzleX, muzzleY, muzzleZ), flashScale,
        { r: 255, g: 200, b: 120, a: intensity255 });
    }
  }
  // Per-enemy: drive the skinned skeleton via updateModelAnimation (picks
  // attack vs walk anim), then drawModel renders with the pose from the
  // joint matrices set by the update. Both calls use the same position so
  // non-skinned fallbacks still sit in the right place.
  const ppAim = playerPosition();
  for (let i = 0; i < MAX_ENEMIES; i++) {
    if (enAlive[i] === 0) continue;
    const k = enKind[i];
    const dxA = ppAim.x - enX[i];
    const dzA = ppAim.z - enZ[i];
    const distA = Math.sqrt(dxA * dxA + dzA * dzA);
    const faceSin = distA > 0.001 ? dxA / distA : 0;
    const faceCos = distA > 0.001 ? -dzA / distA : -1;
    const attacking = distA <= KIND_MELEE[k];
    const animIdx = attacking ? ANIM_ATTACK_IDX[k] : ANIM_WALK_IDX[k];
    updateModelAnimation(animAliens[k], animIdx, enPhase[i], KIND_SCALE[k],
      enX[i], enY[i], enZ[i], faceSin, faceCos);
    const f = enFlashT[i] > 0 ? enFlashT[i] / DRETCH_HIT_FLASH : 0;
    const tint = f > 0
      ? { r: 255,
          g: Math.floor(255 * (1 - f)),
          b: Math.floor(255 * (1 - f)),
          a: 255 }
      : WHITE;
    drawModel(mdlAliens[k], vec3(enX[i], enY[i], enZ[i]), KIND_SCALE[k], tint);
  }
  // Pickups — bobbing cubes, color-coded per kind.
  const tNow = getTime();
  for (let i = 0; i < PICKUP_COUNT; i++) {
    if (pickupActive[i] === 0) continue;
    const bob = 0.8 + Math.sin(tNow * 3.0 + i) * 0.15;
    const isRifleKind = pickupKind[i] === PICKUP_RIFLE;
    const col = isRifleKind
      ? { r: 240, g: 200, b: 80,  a: 255 }    // gold = rifle
      : { r: 120, g: 220, b: 240, a: 255 };   // cyan = blaster
    drawCube(vec3(pickupX[i], bob, pickupZ[i]), 0.4, 0.4, 0.4, col);
    // Glow sphere around the cube for visibility.
    drawSphere(vec3(pickupX[i], bob, pickupZ[i]), 0.55,
      { r: col.r, g: col.g, b: col.b, a: 60 });
  }
  // Impact sparks — small yellow puffs that fade over 0.35s.
  for (let i = 0; i < SPARK_MAX; i++) {
    if (sparkT[i] > 0) {
      const t = sparkT[i] / 0.35;
      const a = Math.min(255, Math.floor(t * 255));
      drawSphere(vec3(sparkX[i], sparkY[i], sparkZ[i]), 0.25 * t + 0.05,
        { r: 255, g: 240, b: 140, a });
    }
  }
  // Blaster projectiles — glowing cyan spheres.
  for (let i = 0; i < MAX_PROJ; i++) {
    if (pLife[i] > 0) {
      drawSphere(vec3(pX[i], pY[i], pZ[i]), 0.16,
        { r: 140, g: 220, b: 255, a: 255 });
    }
  }
  endMode3D();

  // Crosshair — brighten while firing
  const crossA = muzzleFlashT > 0 ? 240 : 160;
  drawCircle(sw / 2, sh / 2, 3, { r: 255, g: 255, b: 255, a: crossA });
  // Muzzle flash — small warm smudge near the crosshair, not full-screen.
  if (muzzleFlashT > 0) {
    const fa = Math.floor((muzzleFlashT / MUZZLE_FLASH_DUR) * 180);
    drawCircle(sw / 2, sh / 2 + 4, 14, { r: 255, g: 220, b: 120, a: fa });
  }

  // Damage vignette — red screen edges when the player takes a hit.
  if (damageFlashT > 0) {
    const fa = Math.floor((damageFlashT / 0.5) * 120);
    drawRect(0, 0, sw, 60, { r: 200, g: 20, b: 20, a: fa });
    drawRect(0, sh - 60, sw, 60, { r: 200, g: 20, b: 20, a: fa });
    drawRect(0, 0, 60, sh, { r: 200, g: 20, b: 20, a: fa });
    drawRect(sw - 60, 0, 60, sh, { r: 200, g: 20, b: 20, a: fa });
  }

  // Player HP bar — bottom-left.
  const phpW = 220;
  const phpFill = Math.max(0, Math.floor(phpW * (playerHP / PLAYER_HP_MAX)));
  drawRect(10, sh - 68, phpW, 18, { r: 30, g: 10, b: 10, a: 180 });
  drawRect(10, sh - 68, phpFill, 18, { r: 180, g: 60, b: 50, a: 230 });
  drawText('HP ' + playerHP, 18, sh - 65, 14, { r: 240, g: 240, b: 240, a: 255 });

  // Weapon + ammo — bottom-right.
  const isRifleHud = currentWeapon === WEAPON_RIFLE;
  const curAmmo = isRifleHud ? rifleAmmo : blasterAmmo;
  const curMag  = isRifleHud ? RIFLE_MAG : BLASTER_MAG;
  const wtxt = WEAPON_NAMES[currentWeapon] + '  ' + curAmmo + ' / ' + curMag;
  drawRect(sw - 260, sh - 68, 250, 18, { r: 0, g: 0, b: 0, a: 150 });
  drawText(wtxt + '   [1/2 switch  R reload]',
           sw - 252, sh - 65, 13, { r: 240, g: 230, b: 180, a: 255 });

  // Wave HUD — top-center. Shows "WAVE X — enemies K/N" while spawning,
  // or a "NEXT WAVE IN ..." countdown between waves.
  const aliveNow = countAlive();
  if (!gameOver && !gameWon) {
    if (waveBreakTimer > 0 && waveIdx < wavePlan.length) {
      const label = 'WAVE ' + (waveIdx + 1) + ' IN ' + waveBreakTimer.toFixed(1) + 's';
      const lw = measureText(label, 22);
      drawText(label, (sw - lw) / 2, 18, 22, { r: 230, g: 220, b: 160, a: 230 });
    } else if (waveIdx < wavePlan.length) {
      const waveSize = wavePlan[waveIdx];
      const remaining = (waveSize - waveSpawned) + aliveNow;
      const label = 'WAVE ' + (waveIdx + 1) + ' — ' + remaining + ' / ' + waveSize;
      const lw = measureText(label, 20);
      drawText(label, (sw - lw) / 2, 18, 20, { r: 230, g: 220, b: 160, a: 230 });
    }
  }

  // Game over overlay.
  if (gameOver) {
    drawRect(0, 0, sw, sh, { r: 0, g: 0, b: 0, a: 170 });
    const msg = 'YOU DIED';
    const mw = measureText(msg, 56);
    drawText(msg, (sw - mw) / 2, sh * 0.35, 56, { r: 220, g: 60, b: 50, a: 255 });
    const sub = 'Reached wave ' + (waveIdx + 1) + ' — press R to restart';
    const sww = measureText(sub, 22);
    drawText(sub, (sw - sww) / 2, sh * 0.35 + 72, 22, { r: 220, g: 220, b: 220, a: 230 });
  }

  // Victory overlay.
  if (gameWon) {
    drawRect(0, 0, sw, sh, { r: 0, g: 0, b: 0, a: 170 });
    const msg = 'ARENA CLEARED';
    const mw = measureText(msg, 52);
    drawText(msg, (sw - mw) / 2, sh * 0.33, 52, { r: 180, g: 230, b: 180, a: 255 });
    const sub = 'Survived all ' + wavePlan.length + ' waves — press R to play again';
    const sww = measureText(sub, 22);
    drawText(sub, (sw - sww) / 2, sh * 0.33 + 70, 22, { r: 220, g: 220, b: 220, a: 230 });
  }

  // Diagnostic HUD — helps verify input is reaching the game
  const pp = playerPosition();
  const diag1 = 'FPS ' + Math.floor(getFPS())
    + '  world: ' + worldStatus
    + '  WASD:' + input.moveX.toFixed(1) + ',' + input.moveZ.toFixed(1)
    + '  jump:' + (input.jump ? '1' : '0')
    + '  fire:' + (input.fireDown ? '1' : '0')
    + '  mouse:' + (cursorLocked ? 'locked (Tab to free)' : 'free (Tab to lock)');
  const diag2 = 'pos ' + pp.x.toFixed(1) + ',' + pp.y.toFixed(1) + ',' + pp.z.toFixed(1)
    + '  yaw ' + CAM[0].toFixed(2) + '  pitch ' + CAM[1].toFixed(2)
    + '  cam ' + CAM[2].toFixed(1) + ',' + CAM[3].toFixed(1) + ',' + CAM[4].toFixed(1)
    + '  shots ' + shotsHit + '/' + shotsFired;

  drawRect(0, sh - 44, sw, 44, { r: 0, g: 0, b: 0, a: 150 });
  drawText(diag1, 10, sh - 40, 13, { r: 200, g: 210, b: 230, a: 220 });
  drawText(diag2, 10, sh - 20, 13, { r: 180, g: 200, b: 220, a: 220 });

  // Phase 8 — profiler overlay (F3). Lists every engine pass with
  // CPU and GPU (µs) averaged over the profiler's 120-frame rolling
  // window, sorted by CPU time descending.
  if (perfOverlayOn) {
    const rows = getProfilerOverlay();
    const rowH = 16;
    const ox = sw - 360;
    // Phase 8 — frame-time histogram on top of the pass list so it
    // stays visible regardless of how many passes are running. Each
    // bar is one frame; height = total CPU+GPU time scaled to a
    // 16.7 ms (60 fps) reference. Bars over full height = dropped
    // frames (drawn red).
    const hist = getProfilerFrameHistory();
    const histY = 60;
    const histH = 56;
    const barW = 2;
    const histW = Math.min(hist.length * barW, 360 - 16);
    const refMs = 16.667;
    drawRect(ox - 8, histY - 8, 360, histH + 32, { r: 0, g: 0, b: 0, a: 180 });
    drawText('frame total ms (cpu+gpu, scale = 60 fps)',
             ox, histY, 12, { r: 220, g: 220, b: 255, a: 230 });
    drawRect(ox, histY + 18 + histH - 1, histW, 1,
             { r: 100, g: 200, b: 100, a: 180 });
    for (let i = 0; i < hist.length && i * barW < histW; i++) {
      const totalMs = (hist[i].cpuUs + hist[i].gpuUs) / 1000;
      const h = Math.max(1, Math.min(histH, Math.floor(totalMs / refMs * histH)));
      const overBudget = totalMs > refMs;
      const col = overBudget
        ? { r: 230, g: 100, b:  90, a: 220 }
        : { r:  90, g: 180, b: 230, a: 200 };
      drawRect(ox + i * barW, histY + 18 + histH - h, barW - 1, h, col);
    }

    // Per-pass table below the histogram.
    const oy = histY + histH + 36;
    drawRect(ox - 8, oy - 8, 360, rowH * (rows.length + 2) + 12,
             { r: 0, g: 0, b: 0, a: 180 });
    drawText('pass                    cpu µs    gpu µs',
             ox, oy, 13, { r: 220, g: 220, b: 255, a: 255 });
    for (let i = 0; i < rows.length; i++) {
      const r = rows[i];
      const gpuStr = r.gpuUs < 0 ? '     -' : r.gpuUs.toFixed(1);
      const line = r.label.padEnd(22, ' ') + r.cpuUs.toFixed(1).padStart(9, ' ') +
                   '  ' + gpuStr.padStart(8, ' ');
      drawText(line, ox, oy + rowH * (i + 1), 13,
               { r: 200, g: 210, b: 230, a: 230 });
    }
  }

  if (isKeyPressed(Key.ESCAPE)) break;
  endDrawing();
}
