import {
  initWindow, windowShouldClose, beginDrawing, endDrawing, clearBackground,
  setTargetFPS, getDeltaTime, getFPS, getTime,
  beginMode3D, endMode3D,
  drawCube, drawSphere, drawText, drawRect, drawCircle, measureText,
  setAmbientLight, setDirectionalLight,
  getScreenWidth, getScreenHeight,
  vec3,
  isKeyPressed, Key, Vec3, injectKeyDown, injectKeyUp,
  disableCursor, enableCursor, takeScreenshot,
  loadModel, drawModel, drawModelRotated, loadModelAnimation, updateModelAnimation,
  createMesh, compileMaterial, compileRefractiveMaterial, drawMeshWithMaterial,
  genMeshCube, createPlanarReflection, setMaterialReflectionProbe,
  initAudio, loadSound, playSound, setSoundVolume,
  loadMusic, playMusic, updateMusicStream, setMusicVolume,
} from 'bloom';
import {
  setVignette, setFilmGrain,
  setQualityPreset, QualityPreset,
  setShadowsEnabled, setSsaoEnabled, setSsaoIntensity, setSsaoRadius,
  setBloomEnabled, setBloomIntensity, setTaaEnabled, setRenderScale,
  setAutoExposure, setManualExposure, setAutoExposureKey, setEnvIntensity,
  setSsrEnabled, setSsgiEnabled, setSsgiIntensity, setFog, setSunShafts,
  setTonemap, Tonemap, setWind,
} from 'bloom/core';
import { setProceduralSky, setSunDirection } from 'bloom';
import { addPointLight } from 'bloom/scene';
import {
  createWorld, step as stepPhysics,
  boxShape, heightfieldShape, createBody, MotionType, Layer,
  setLayerCollides, raycast, ALL_LAYERS_MASK, BodyHandle,
  setBodyPosition,
} from 'bloom/physics';
import { initInput, readInput } from './input';
import { createPlayer, updatePlayerController, playerPosition } from './player';
import * as W from './generated/world';
import * as T from './generated/terrain';

initWindow(1024, 640, 'Bloom Shooter');
setTargetFPS(60);
initInput();

// ---- Loading screen -------------------------------------------------------
// The heavy startup work (GLB model parse/upload, the tessellated water-mesh
// scratch upload, audio decode) runs synchronously before the game loop, so
// the window would otherwise sit frozen-black for several seconds. Render a
// progress frame between the major steps so startup shows a bar.
function drawLoading(progress: number, label: string): void {
  beginDrawing();
  clearBackground({ r: 16, g: 18, b: 26, a: 255 });
  const sw = getScreenWidth(), sh = getScreenHeight();
  const title = 'BLOOM SHOOTER';
  drawText(title, (sw - measureText(title, 34)) / 2, sh * 0.30, 34,
           { r: 222, g: 232, b: 244, a: 255 });
  const bw = 440, bh = 22, bx = (sw - bw) / 2, by = sh * 0.55;
  const p = progress < 0 ? 0 : (progress > 1 ? 1 : progress);
  drawText(label, bx, by - 26, 15, { r: 165, g: 178, b: 196, a: 255 });
  drawRect(bx - 2, by - 2, bw + 4, bh + 4, { r: 70, g: 78, b: 92, a: 255 });
  drawRect(bx, by, bw, bh, { r: 28, g: 31, b: 40, a: 255 });
  drawRect(bx, by, bw * p, bh, { r: 96, g: 176, b: 226, a: 255 });
  endDrawing();
}
drawLoading(0.05, 'Starting up…');

// ---- M8 polish: audio -----------------------------------------------------
initAudio();
const sfxFire = loadSound('assets/sounds/rifle_fire.wav');
const sfxAttack = loadSound('assets/sounds/dretch_attack.wav');
const sfxPickup = loadSound('assets/sounds/pickup.wav');
setSoundVolume(sfxFire, 0.35);
setSoundVolume(sfxAttack, 0.6);
setSoundVolume(sfxPickup, 0.8);
const musicAmbient = loadMusic('assets/sounds/ambient.ogg');
setMusicVolume(musicAmbient, 0.35);
playMusic(musicAmbient);
drawLoading(0.20, 'Building world…');

const physics = createWorld({ gravity: vec3(0, -20, 0) });
// Make NON_MOVING (static) and MOVING (character/dynamic) collide.
setLayerCollides(physics, Layer.NON_MOVING, Layer.MOVING, true);
setLayerCollides(physics, Layer.MOVING, Layer.MOVING, true);

// ---- World: arena_02 (see src/generated/world.ts) -------------------------
// Authored in assets/worlds/arena_02.world.json; flat-array TS module is
// regenerated by tools/build-world.ts before every build. All geometry,
// lighting, spawners, pickups, and the wave plan come from that world data.
// The editor can read/write the same JSON → one source of truth.

const spawnPos: Vec3 = vec3(W.SPAWN_X, W.SPAWN_Y, W.SPAWN_Z);
const spawnYaw = W.SPAWN_YAW;

// Apply environment settings from the world file.
setAmbientLight(
  { r: Math.floor(W.ENV_AMBIENT_R * 255), g: Math.floor(W.ENV_AMBIENT_G * 255),
    b: Math.floor(W.ENV_AMBIENT_B * 255), a: 255 },
  W.ENV_AMBIENT_I);
setDirectionalLight(
  vec3(W.ENV_SUN_DIR_X, W.ENV_SUN_DIR_Y, W.ENV_SUN_DIR_Z),
  { r: Math.floor(W.ENV_SUN_R * 255), g: Math.floor(W.ENV_SUN_G * 255),
    b: Math.floor(W.ENV_SUN_B * 255), a: 255 },
  W.ENV_SUN_I);

// Static box colliders — invisible physics walls that bound the plaza
// and carry the ground plane.
for (let i = 0; i < W.COLLIDER_COUNT; i++) {
  const shape = boxShape(vec3(W.COLLIDER_HALF_X[i], W.COLLIDER_HALF_Y[i], W.COLLIDER_HALF_Z[i]));
  createBody(physics, shape, {
    motionType: MotionType.STATIC,
    position: vec3(W.COLLIDER_X[i], W.COLLIDER_Y[i], W.COLLIDER_Z[i]),
    objectLayer: Layer.NON_MOVING,
    friction: 0.9,
  });
}

// Heightfield terrain collider — matches assets/models/terrain_hills.glb.
// Samples in TERRAIN_HEIGHTS are row-major z*width+x; engine's heightfield
// shape takes an origin + scale (cellSize in X/Z, Y=1 since the heights
// are already in world units) and builds a Jolt HeightFieldShape.
{
  const shape = heightfieldShape(
    T.TERRAIN_HEIGHTS, T.TERRAIN_SAMPLE_COUNT,
    vec3(T.TERRAIN_ORIGIN_X, T.TERRAIN_ORIGIN_Y, T.TERRAIN_ORIGIN_Z),
    vec3(T.TERRAIN_CELL_SIZE, 1, T.TERRAIN_CELL_SIZE));
  createBody(physics, shape, {
    motionType: MotionType.STATIC,
    position: vec3(0, 0, 0),
    objectLayer: Layer.NON_MOVING,
    friction: 0.95,
  });
}

// Drawable meshes: each static_mesh entity references a modelRef via
// MESH_MODEL_IDX → UNIQUE_MODELS. Real GLBs are loaded once here and
// drawn via drawModel each frame. Box-placeholder entries (modelRef
// `_gizmo_box.glb`) get a coloured drawCube fallback at draw time,
// tinted by category (0 = generic, 1 = building stone, 2 = terrain
// green, 3 = prop brown).
const MESH_TINT_R = [150, 196, 120, 130];
const MESH_TINT_G = [148, 168,  90,  95];
const MESH_TINT_B = [140, 130,  70,  80];
drawLoading(0.35, 'Loading models…');
const meshModelHandles = new Array<number>(W.UNIQUE_MODEL_COUNT);
for (let i = 0; i < W.UNIQUE_MODEL_COUNT; i++) {
  meshModelHandles[i] = W.MODEL_IS_BOX[i] === 1 ? 0 : loadModel(W.UNIQUE_MODELS[i]);
}
// Per-mesh collider from userData.collider === 'box'.
for (let i = 0; i < W.MESH_COUNT; i++) {
  if (W.MESH_COLLIDER[i] === 1) {
    const shape = boxShape(vec3(W.MESH_COLLIDER_HX[i], W.MESH_COLLIDER_HY[i], W.MESH_COLLIDER_HZ[i]));
    createBody(physics, shape, {
      motionType: MotionType.STATIC,
      position: vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
      objectLayer: Layer.NON_MOVING,
      friction: 0.9,
    });
  }
}
const worldStatus = W.WORLD_NAME + ' (' + W.COLLIDER_COUNT + '+' + W.MESH_COUNT + ' bodies)';


createPlayer(physics, spawnPos);

// ---- Third-person orbit camera (inline; see perry-quirks.md) --------------
// Array-slot state because Perry 0.5.158 doesn't propagate module-scope
// `let` reassignments across function calls. Cross-module array writes
// are even more fragile; keeping everything local to main.ts so the
// compiler has no excuse to lose the writes.
//   CAM[0] yaw           CAM[5] tgtX
//   CAM[1] pitch         CAM[6] tgtY
//   CAM[2] camX          CAM[7] tgtZ
//   CAM[3] camY          CAM[8] initialised (0/1)
//   CAM[4] camZ
const CAM = [spawnYaw, 0.3, 0, 0, 0, 0, 0, 0, 0];
// Third-person orbit pitch limits (camera elevation about the player).
const TP_PITCH_MIN = -0.35;
const TP_PITCH_MAX = 1.05;
const TP_ORBIT_DIST = 6.0;   // (unused in first-person)
const TP_EYE_HEIGHT = 1.4;
const FP_EYE_HEIGHT = 0.6;   // eye above the capsule centre (playerPosition)
const TP_SMOOTH = 10.0;
const TP_FOVY = 70;

// ---- Third-person player model (human_bsuit) -----------------------------
// Converted via tools/convert-aliens-anim.ts. Drawn at the physics-character
// position, facing the camera's horizontal yaw so the player always looks
// "away from the camera" (classic 3rd-person over-the-shoulder feel).
const mdlPlayer  = loadModel('assets/models/player_bsuit.glb');
const animPlayer = loadModelAnimation('assets/models/player_bsuit.glb');
// The house: all "building"-tagged box colliders baked into ONE stone-textured
// mesh (tools/build-props.ts makeHouse), vertices already in world space — so
// it draws with a single drawModel at the origin. Replaces the flat-grey
// drawCube placeholders; the boxes remain invisible physics colliders.
const mdlHouse   = loadModel('assets/models/house.glb');
// PBR calibration rig (grey-albedo / roughness / metallic sphere grid). Only
// drawn + framed when VERIFY_CALIB is on, for objective exposure/BRDF checks.
const VERIFY_CALIB = false;
const CALIB_AT = vec3(0, 6, 0);
const mdlCalib   = loadModel('assets/models/calib_rig.glb');
// human_bsuit animation indices (IQE declaration order):
//   0 idle, 7 attack, 8 run, 12 walk.
const PLAYER_ANIM_IDLE   = 0;
const PLAYER_ANIM_WALK   = 12;
const PLAYER_ANIM_RUN    = 8;
const PLAYER_ANIM_ATTACK = 7;
const PLAYER_SCALE = 1.0;
const PLAYER_MODEL_Y_OFFSET = -0.95;    // character capsule center -> feet
let playerAnimT = 0;

// ---- Phase 1c smoke: material shader + cube mesh -------------------------
// Compiles a tiny ABI-compliant shader through the new material
// pipeline and draws a rotating colour-pulsed cube in front of the
// player spawn. First visible consumer of the material-system path;
// only exists to verify end-to-end compile → submit → dispatch works.

const MAT_TEST_WGSL = '#include "material_abi.wgsl"\n' +
  'struct VsOut { @builtin(position) pos: vec4<f32>, @location(0) n: vec3<f32>, @location(1) c: vec3<f32> };\n' +
  '@vertex fn vs_main(in: VertexInput) -> VsOut {\n' +
  '  var o: VsOut;\n' +
  '  o.pos = draw.mvp * vec4<f32>(in.position, 1.0);\n' +
  '  o.n = normalize((draw.model * vec4<f32>(in.normal, 0.0)).xyz);\n' +
  '  let p = 0.5 + 0.5 * sin(frame.time * 1.5);\n' +
  '  o.c = vec3<f32>(p, 0.4, 1.0 - p) * draw.model_tint.rgb;\n' +
  '  return o;\n' +
  '}\n' +
  '@fragment fn fs_main(in: VsOut) -> OpaqueOut {\n' +
  '  var out: OpaqueOut;\n' +
  '  let ndl = max(dot(normalize(in.n), normalize(vec3<f32>(0.3, 0.7, 0.4))), 0.0);\n' +
  '  let lit = in.c * (0.3 + 0.7 * ndl);\n' +
  '  out.hdr = vec4<f32>(lit, 1.0);\n' +
  '  out.material = vec2<f32>(0.0, 0.9);\n' +
  '  out.velocity = vec2<f32>(0.0, 0.0);\n' +
  '  out.albedo = vec4<f32>(in.c, 1.0);\n' +
  '  return out;\n' +
  '}\n';
const matTest = compileMaterial(MAT_TEST_WGSL);
// Minimal cube: 24 verts (one per face-corner so UVs / normals split
// cleanly) × 12 floats (pos, nrm, col, uv) = 288 floats. 6 faces × 2
// tris × 3 idx = 36 indices.
const MAT_TEST_VERTS: number[] = [
  // +X face (nrm = +1, 0, 0)
   0.5, -0.5, -0.5,  1,0,0,  1,1,1,1,  0,0,
   0.5, -0.5,  0.5,  1,0,0,  1,1,1,1,  1,0,
   0.5,  0.5,  0.5,  1,0,0,  1,1,1,1,  1,1,
   0.5,  0.5, -0.5,  1,0,0,  1,1,1,1,  0,1,
  // -X
  -0.5, -0.5,  0.5, -1,0,0,  1,1,1,1,  0,0,
  -0.5, -0.5, -0.5, -1,0,0,  1,1,1,1,  1,0,
  -0.5,  0.5, -0.5, -1,0,0,  1,1,1,1,  1,1,
  -0.5,  0.5,  0.5, -1,0,0,  1,1,1,1,  0,1,
  // +Y (top)
  -0.5,  0.5,  0.5,  0,1,0,  1,1,1,1,  0,0,
   0.5,  0.5,  0.5,  0,1,0,  1,1,1,1,  1,0,
   0.5,  0.5, -0.5,  0,1,0,  1,1,1,1,  1,1,
  -0.5,  0.5, -0.5,  0,1,0,  1,1,1,1,  0,1,
  // -Y
  -0.5, -0.5, -0.5,  0,-1,0, 1,1,1,1,  0,0,
   0.5, -0.5, -0.5,  0,-1,0, 1,1,1,1,  1,0,
   0.5, -0.5,  0.5,  0,-1,0, 1,1,1,1,  1,1,
  -0.5, -0.5,  0.5,  0,-1,0, 1,1,1,1,  0,1,
  // +Z
   0.5, -0.5,  0.5,  0,0,1,  1,1,1,1,  0,0,
  -0.5, -0.5,  0.5,  0,0,1,  1,1,1,1,  1,0,
  -0.5,  0.5,  0.5,  0,0,1,  1,1,1,1,  1,1,
   0.5,  0.5,  0.5,  0,0,1,  1,1,1,1,  0,1,
  // -Z
  -0.5, -0.5, -0.5,  0,0,-1, 1,1,1,1,  0,0,
   0.5, -0.5, -0.5,  0,0,-1, 1,1,1,1,  1,0,
   0.5,  0.5, -0.5,  0,0,-1, 1,1,1,1,  1,1,
  -0.5,  0.5, -0.5,  0,0,-1, 1,1,1,1,  0,1,
];
const MAT_TEST_INDS: number[] = [
   0, 1, 2,  0, 2, 3,
   4, 5, 6,  4, 6, 7,
   8, 9,10,  8,10,11,
  12,13,14, 12,14,15,
  16,17,18, 16,18,19,
  20,21,22, 20,22,23,
];
// Phase 1c material smoke-test cube. Disabled on the Windows/Perry-0.5.1171
// path: `createMesh` passes a number[] straight into `bloom_create_mesh`'s
// `i64` vertex/index-pointer params, but Perry 0.5.1171 tightened the native
// ABI so an `i64` parameter must be a safe-integer number, not an array
// (TypeError: "Expected safe integer for native i64 parameter"). The engine
// needs to migrate this FFI to Perry's `buffer+len` descriptor (or the
// physics-style scratch-buffer push) before the material path works again.
// The cube is a dev bring-up artifact, not gameplay — gate it off.
const MAT_SMOKE = false;
const matTestMesh = MAT_SMOKE ? createMesh(MAT_TEST_VERTS, MAT_TEST_INDS) : 0;

// Build a tessellated flat grid plane (sx × sz, centred at origin, y=0) for
// the water surface. The grid is dense enough for the vertex shader to
// displace it into real waves (fixing the flat-silhouette look). 12 floats
// per vertex: pos3, nrm3, col4, uv2. Uses the (now array-free) createMesh.
function buildWaterGrid(sx: number, sz: number) {
  const NX = Math.max(2, Math.ceil(sx / 0.55));
  const NZ = Math.max(2, Math.ceil(sz / 0.55));
  const VX = NX + 1, VZ = NZ + 1;
  const verts = new Array<number>(VX * VZ * 12);
  let o = 0;
  for (let iz = 0; iz < VZ; iz++) {
    for (let ix = 0; ix < VX; ix++) {
      const u = ix / NX, v = iz / NZ;
      verts[o] = (u - 0.5) * sx; verts[o + 1] = 0; verts[o + 2] = (v - 0.5) * sz;
      verts[o + 3] = 0; verts[o + 4] = 1; verts[o + 5] = 0;
      verts[o + 6] = 1; verts[o + 7] = 1; verts[o + 8] = 1; verts[o + 9] = 1;
      verts[o + 10] = u; verts[o + 11] = v;
      o = o + 12;
    }
  }
  const inds = new Array<number>(NX * NZ * 6);
  let io = 0;
  for (let iz = 0; iz < NZ; iz++) {
    for (let ix = 0; ix < NX; ix++) {
      const a = iz * VX + ix, b = a + 1, c = a + VX, d = c + 1;
      inds[io] = a; inds[io + 1] = c; inds[io + 2] = b;
      inds[io + 3] = b; inds[io + 4] = c; inds[io + 5] = d;
      io = io + 6;
    }
  }
  return createMesh(verts, inds);
}

// ---- Reflective water (planar-reflection material) ------------------------
// Replaces the ~1800-cube procedural river with one flat plane per segment,
// shaded by a custom WGSL material that samples a planar-reflection probe (the
// engine's per-frame mirror render of the world above the surface) with
// Fresnel blending, procedural wave normals, and a sun glint. The plane mesh
// comes from genMeshCube (scalar args — avoids the createMesh i64 ABI issue),
// and drawMeshWithMaterial submits it (all-f64 ABI).
const WATER_WGSL =
  '#include "material_abi.wgsl"\n' +
  'struct VsOut { @builtin(position) pos: vec4<f32>, @location(0) wpos: vec3<f32>, @location(1) uv: vec2<f32> };\n' +
  // Macro wave height (metres) — three directional swells. Displaces the
  // tessellated grid vertices so the surface physically undulates (wavy
  // silhouette + moving edges), not just a normal-mapped flat plane.
  'fn wheight(p: vec2<f32>, t: f32) -> f32 {\n' +
  '  return 0.12 * sin(p.x * 0.5 + t * 1.1)\n' +
  '       + 0.06 * sin((p.x * 0.9 + p.y * 0.6) + t * 1.9)\n' +
  '       + 0.035 * sin((p.x * 2.3 - p.y * 1.1) + t * 3.3);\n' +
  '}\n' +
  '@vertex fn vs_main(in: VertexInput) -> VsOut {\n' +
  '  var o: VsOut;\n' +
  '  let wflat = (draw.model * vec4<f32>(in.position, 1.0)).xyz;\n' +
  '  let disp = vec3<f32>(in.position.x, in.position.y + wheight(wflat.xz, frame.time), in.position.z);\n' +
  '  let wd = draw.model * vec4<f32>(disp, 1.0);\n' +
  '  o.wpos = wd.xyz;\n' +
  '  o.uv = in.uv;\n' +
  '  o.pos = draw.mvp * vec4<f32>(disp, 1.0);\n' +
  '  return o;\n' +
  '}\n' +
  // Procedural surface normal from summed directional sine waves (analytic
  // derivative -> perturbed normal; cheap, no normal-map texture needed).
  'fn wnorm(p: vec2<f32>, t: f32) -> vec3<f32> {\n' +
  // Three octaves: slow swell + medium chop + fine fast ripple. Strong
  // slope (×0.30) so the surface reads as lively water on a flat plane.
  '  let dx = 0.5 * cos(p.x * 0.5 + t * 1.1) + 0.7 * cos((p.x * 0.9 + p.y * 0.6) + t * 1.9) + 0.5 * cos((p.x * 2.3 - p.y * 1.1) + t * 3.3);\n' +
  '  let dz = 0.5 * cos(p.y * 0.7 - t * 1.3) + 0.7 * cos((p.x * 0.6 + p.y * 0.9) + t * 1.9) + 0.5 * cos((p.x * 1.1 + p.y * 2.3) + t * 3.0);\n' +
  '  return normalize(vec3<f32>(-dx * 0.30, 1.0, -dz * 0.30));\n' +
  '}\n' +
  // Analytic sky reflection. The engine's procedural sky renders via a
  // separate LUT pass and never lands in env_tex, and the planar-reflection
  // probe only captures material-system draws (this game is immediate-mode),
  // so there is nothing real to mirror. Instead we reflect a believable sky
  // dome built from the reflected ray R: zenith→horizon gradient + a sharp
  // sun disk + soft glow, tinted by the engine's actual sun colour/intensity.
  'fn sky_refl(R: vec3<f32>, sun_dir: vec3<f32>, sun_col: vec3<f32>, sun_int: f32) -> vec3<f32> {\n' +
  '  let up = clamp(R.y, 0.0, 1.0);\n' +
  '  let zenith  = vec3<f32>(0.11, 0.22, 0.42);\n' +
  '  let horizon = vec3<f32>(0.38, 0.50, 0.64);\n' +
  '  var sky = mix(horizon, zenith, pow(up, 0.55));\n' +
  '  let sd = max(dot(R, normalize(sun_dir)), 0.0);\n' +
  '  sky = sky + sun_col * (pow(sd, 900.0) * 2.5 + pow(sd, 12.0) * 0.15) * max(sun_int, 0.4);\n' +
  '  return sky;\n' +
  '}\n' +
  // Refractive profile: sample the scene (riverbed) BEHIND the surface and
  // distort it by the wave normal — real refraction (the bottom wobbles).
  // Tint it by water depth (scene-depth → Beer-Lambert: shallow clear, deep
  // murky blue), then blend a Fresnel planar reflection + sun glint + foam.
  // Composited in-shader (opaque output) → reads as real water, not a flat
  // tinted pane.
  '@fragment fn fs_main(in: VsOut) -> TranslucentOut {\n' +
  '  var out: TranslucentOut;\n' +
  '  let t = frame.time;\n' +
  '  let N = wnorm(in.wpos.xz, t);\n' +
  '  let V = normalize(view.camera_pos.xyz - in.wpos);\n' +
  '  let ndv = max(dot(N, V), 0.0001);\n' +
  '  let screen_uv = in.pos.xy / vec2<f32>(frame.screen_resolution);\n' +
  // Refraction — the riverbed, displaced by the wave normal.
  '  let refr_uv = clamp(screen_uv + N.xz * 0.04, vec2<f32>(0.002), vec2<f32>(0.998));\n' +
  '  let bottom = textureSample(scene_color_tex, scene_color_samp, refr_uv).rgb;\n' +
  // Water column thickness from scene depth → absorption. textureLoad avoids
  // depth-sampler issues; clamp keeps it plausible if depth is imprecise.
  '  let dsz = vec2<f32>(textureDimensions(scene_depth_tex));\n' +
  '  let bz = textureLoad(scene_depth_tex, vec2<i32>(screen_uv * dsz), 0);\n' +
  '  let thick = max(0.0, linearize_depth(bz) - linearize_depth(in.pos.z));\n' +
  // Beer-Lambert: shallow water stays clear (bed visible near the banks),
  // deep water tints toward murky green-blue. Floor near 0 so the refracted
  // riverbed reads through; ceiling < 1 so the deepest water keeps some bed.
  '  let absorb = clamp(1.0 - exp(-thick * 0.85), 0.04, 0.88);\n' +
  '  let deep = vec3<f32>(0.02, 0.11, 0.13);\n' +
  '  let body = mix(bottom, deep, absorb);\n' +
  // Reflected ray → analytic sky. Fresnel (water F0≈0.02, Schlick) ramps the
  // sky in hard at grazing angles, so the surface goes bright + sky-coloured
  // toward the far bank and stays clear/see-through looking straight down.
  '  let R = reflect(-V, N);\n' +
  '  let sky = sky_refl(R, view.sun_dir.xyz, view.sun_color.rgb, view.sun_dir.w);\n' +
  // Planar reflection probe: the actual mirrored scene (trees / house). The
  // probe clears to alpha 0 and reflected geometry writes alpha 1, so blend the
  // probe over the analytic sky by its alpha — real reflections where geometry
  // exists, the sky dome everywhere else. Wave normal perturbs the lookup.
  '  let prefl = textureSample(planar_reflection_tex, planar_reflection_samp, clamp(screen_uv + N.xz * 0.03, vec2<f32>(0.001), vec2<f32>(0.999)));\n' +
  '  let refl = mix(sky, prefl.rgb, clamp(prefl.a, 0.0, 1.0));\n' +
  // Cap Fresnel below 1 so even grazing water keeps ~30% of its body colour
  // instead of becoming a pure mirror — that full-mirror grazing reflection was
  // what turned the whole river into a blown-white sheet at eye level.
  '  let fres = clamp(0.02 + 0.98 * pow(1.0 - ndv, 5.0), 0.0, 0.70);\n' +
  // Tight specular sun glint on top of the Fresnel sky reflection.
  // view.sun_dir is direction-TO-sun, so L = +sun_dir (was negated to
  // compensate for the old below-horizon SUN_DIR; fixed now).
  '  let L = normalize(view.sun_dir.xyz);\n' +
  '  let H = normalize(L + V);\n' +
  '  let spec = pow(max(dot(N, H), 0.0), 400.0) * max(view.sun_dir.w, 0.6) * 0.6;\n' +
  '  var color = mix(body, refl, fres) + vec3<f32>(1.0, 0.97, 0.9) * spec;\n' +
  // Shoreline foam.
  '  let edge = min(min(in.uv.x, 1.0 - in.uv.x), min(in.uv.y, 1.0 - in.uv.y));\n' +
  '  let foam_band = smoothstep(0.07, 0.0, edge);\n' +
  '  let foam = foam_band * foam_band * (0.6 + 0.4 * sin(in.wpos.x * 6.0 + in.wpos.z * 5.0 + t * 3.0));\n' +
  '  color = mix(color, vec3<f32>(0.80, 0.87, 0.92), foam * 0.42);\n' +
  '  out.hdr = vec4<f32>(color, 1.0);\n' +
  '  return out;\n' +
  '}\n';
const waterMat = compileRefractiveMaterial(WATER_WGSL);
// ONE continuous river plane spanning all segments + the carved channel. The
// authored world has 6 short segments at alternating z (11/13) which rendered
// as disconnected rectangles with gaps; a single plane over their bounding
// span reads as one connected ribbon that fills the carved channel.
let riverMinX = 1e9, riverMaxX = -1e9, waterYSum = 0;
for (let i = 0; i < W.WATER_COUNT; i++) {
  const lo = W.WATER_CX[i] - W.WATER_SX[i] * 0.5;
  const hi = W.WATER_CX[i] + W.WATER_SX[i] * 0.5;
  if (lo < riverMinX) riverMinX = lo;
  if (hi > riverMaxX) riverMaxX = hi;
  waterYSum = waterYSum + W.WATER_CY[i];
}
const waterY = W.WATER_COUNT > 0 ? waterYSum / W.WATER_COUNT : 0.05;
const RIVER_CX = (riverMinX + riverMaxX) * 0.5;
const RIVER_W = riverMaxX - riverMinX;
const RIVER_CZ = 12.0;     // carved-channel centre (see build-terrain.ts)
const RIVER_DEPTH = 5.0;   // fits the channel bed (z ≈ 9.4–14.6)
drawLoading(0.65, 'Building water…');
const waterMesh = buildWaterGrid(RIVER_W, RIVER_DEPTH);
const waterProbe = createPlanarReflection(waterY, 0, 1, 0, 512);
if (waterMat > 0) setMaterialReflectionProbe(waterMat, waterProbe);

// ---- Unvanquished aliens (5 kinds, M3 model + M5 AI + M6 pool) ------------
// Each kind has its own GLB model and stat line. Kinds and models line up
// with the Unvanquished alien classes:
//   0 = dretch   — small, fast, low HP, moderate damage
//   1 = mantis   — quick, medium HP
//   2 = marauder — medium all-round
//   3 = dragoon  — heavier, slower, hits hard
//   4 = tyrant   — boss tier; rare, big, tanky
const KIND_COUNT = 5;
const KIND_NAME  = ['DRETCH', 'MANTIS', 'MARAUDER', 'DRAGOON', 'TYRANT'];
drawLoading(0.85, 'Loading enemies…');
const mdlAliens  = [
  loadModel('assets/models/enemy_dretch.glb'),
  loadModel('assets/models/enemy_mantis.glb'),
  loadModel('assets/models/enemy_marauder.glb'),
  loadModel('assets/models/enemy_dragoon.glb'),
  loadModel('assets/models/enemy_tyrant.glb'),
];
const animAliens = [
  loadModelAnimation('assets/models/enemy_dretch.glb'),
  loadModelAnimation('assets/models/enemy_mantis.glb'),
  loadModelAnimation('assets/models/enemy_marauder.glb'),
  loadModelAnimation('assets/models/enemy_dragoon.glb'),
  loadModelAnimation('assets/models/enemy_tyrant.glb'),
];
// Animation indices — IQE declaration order. Dretch (and most others):
// 0 stand, 1 attack, 4 die, 14 run, 20 walk. We map gameplay -> anim idx.
const ANIM_WALK_IDX   = [14, 14, 14, 14, 14];
const ANIM_ATTACK_IDX = [1, 1, 1, 1, 1];
// Procedural motion parameters (cheap substitute for skeletal animation).
// Each enemy has a phase accumulator — sinusoids on top give a bob + side-
// sway while walking, and a forward-lunge while attacking.
const WALK_BOB_Y = 0.12;       // metres
const WALK_BOB_RATE = 9.0;     // rad/s
const WALK_TILT = 0.06;        // unused; kept for future side-sway
const ATTACK_LUNGE_AMP = 0.25; // m forward during attack
// Per-kind tuning. Collider half-extents are generous (taller than the visual
// model) so horizontal aim at any range connects.
const KIND_SCALE = [1.6, 1.6, 1.9, 2.4, 3.0];
const KIND_HX    = [1.0, 0.9, 1.2, 1.4, 1.8];
const KIND_HY    = [1.0, 1.0, 1.2, 1.5, 2.0];
const KIND_HZ    = [1.1, 1.0, 1.3, 1.6, 2.0];
const KIND_Y_OFF = [1.0, 1.0, 1.2, 1.5, 2.0];
const KIND_SPEED = [3.0, 4.5, 3.5, 2.5, 2.2];
const KIND_HP    = [3,   4,   6,   10,  20];
const KIND_DMG   = [12,  10,  16,  22,  35];
const KIND_CD    = [0.9, 0.7, 0.9, 1.1, 1.3];
const KIND_MELEE = [2.0, 2.0, 2.3, 2.6, 3.0];
const DRETCH_HIT_FLASH = 0.18;
const WHITE = { r: 255, g: 255, b: 255, a: 255 };

// Enemy pool — each slot is permanently tied to one kind because Jolt body
// shapes can't be swapped in-place. BODIES_PER_KIND dormant bodies per kind
// give us a fixed pool of MAX_ENEMIES = KIND_COUNT * BODIES_PER_KIND.
const BODIES_PER_KIND = 2;
const MAX_ENEMIES = KIND_COUNT * BODIES_PER_KIND;
const enX = new Array<number>(MAX_ENEMIES);
const enY = new Array<number>(MAX_ENEMIES);
const enZ = new Array<number>(MAX_ENEMIES);
const enHP = new Array<number>(MAX_ENEMIES);
const enAlive = new Array<number>(MAX_ENEMIES);
const enKind  = new Array<number>(MAX_ENEMIES);
const enAttackCD = new Array<number>(MAX_ENEMIES);
const enFlashT = new Array<number>(MAX_ENEMIES);
const enPhase = new Array<number>(MAX_ENEMIES);        // walk-cycle phase accumulator
const enBody: BodyHandle[] = new Array<BodyHandle>(MAX_ENEMIES);
for (let k = 0; k < KIND_COUNT; k++) {
  const shape = boxShape(vec3(KIND_HX[k], KIND_HY[k], KIND_HZ[k]));
  for (let j = 0; j < BODIES_PER_KIND; j++) {
    const i = k * BODIES_PER_KIND + j;
    enX[i] = 0; enY[i] = -100; enZ[i] = 0;
    enHP[i] = 0; enAlive[i] = 0; enAttackCD[i] = 0; enFlashT[i] = 0;
    enPhase[i] = Math.random() * Math.PI * 2;   // stagger the bob phases
    enKind[i] = k;
    enBody[i] = createBody(physics, shape, {
      motionType: MotionType.KINEMATIC,
      position: vec3(0, -100, 0),
      objectLayer: Layer.MOVING,
    });
  }
}

// Wave director — spawners, wave plan, and kind sequence all come from the
// world file (see enemy_spawner + wave_config entities in arena_02.world.json).
const spawnerX = W.SPAWNER_X;
const spawnerZ = W.SPAWNER_Z;
const wavePlan = W.WAVE_SIZE;
const WAVE_OFFS = W.WAVE_OFFS;
const WAVE_KINDS = W.WAVE_KIND;
const WAVE_SPAWN_DELAY = 1.2;
const WAVE_BREAK_DELAY = 2.5;
const MAX_CONCURRENT = 4;

let waveIdx = 0;
let waveSpawned = 0;
let waveBreakTimer = WAVE_BREAK_DELAY;
let spawnTimer = 0;
let gameWon = false;

function countAlive(): number {
  let c = 0;
  for (let i = 0; i < MAX_ENEMIES; i++) if (enAlive[i] > 0) c = c + 1;
  return c;
}

// Sample the terrain heightfield (same data the Jolt heightfield collider uses)
// so enemies walk ON the ground instead of a flat y=0 plane — otherwise they
// sink into hills and appear to float on top of the river. Over the carved
// river channel the result is clamped to WADE_FLOOR so crossing aliens wade at
// the water surface rather than sinking out of sight to the −0.55 bed.
const WADE_FLOOR = -0.2;
function terrainHeight(x: number, z: number): number {
  const ix = Math.round((x - T.TERRAIN_ORIGIN_X) / T.TERRAIN_CELL_SIZE);
  const iz = Math.round((z - T.TERRAIN_ORIGIN_Z) / T.TERRAIN_CELL_SIZE);
  if (ix < 0 || iz < 0 || ix >= T.TERRAIN_SAMPLE_COUNT || iz >= T.TERRAIN_SAMPLE_COUNT) return 0;
  return T.TERRAIN_HEIGHTS[iz * T.TERRAIN_SAMPLE_COUNT + ix];
}
function enemyGroundY(x: number, z: number): number {
  const h = terrainHeight(x, z);
  return h < WADE_FLOOR ? WADE_FLOOR : h;
}

// ---- Scattered ground foliage --------------------------------------------
// Deterministic grass-tuft scatter across the play field (hash-jittered grid),
// placed on the terrain surface, skipping the river channel, the house
// footprint, and a clear radius around spawn. Drawn each frame; the tufts are
// alpha-cutout foliage so they sway in the wind via the engine's scene shader.
const mdlGrassTuft = loadModel('assets/models/prop_grasstuft.glb');
const mdlFlower = loadModel('assets/models/prop_flower.glb');
const TUFT_MAX = 320;
const tuftX = new Array<number>(TUFT_MAX);
const tuftY = new Array<number>(TUFT_MAX);
const tuftZ = new Array<number>(TUFT_MAX);
const tuftS = new Array<number>(TUFT_MAX);
const tuftR = new Array<number>(TUFT_MAX);
const tuftFlower = new Array<number>(TUFT_MAX);  // 1 = wildflower, 0 = grass
let tuftCount = 0;
{
  const hashf = (a: number, b: number): number => {
    let h = ((a * 374761393 + b * 668265263) >>> 0);
    h = (((h ^ (h >>> 13)) >>> 0) * 1274126177) >>> 0;
    return ((h ^ (h >>> 16)) >>> 0) / 4294967295;
  };
  const GRID = 26;
  const SPAN = 70;            // metres across, centred on origin
  const step = SPAN / GRID;
  for (let gz = 0; gz < GRID; gz++) {
    for (let gx = 0; gx < GRID; gx++) {
      if (tuftCount >= TUFT_MAX) break;
      // ~35% thinning for natural clumping rather than a regular lawn.
      if (hashf(gx + 7, gz + 13) < 0.35) continue;
      const jx = hashf(gx, gz) - 0.5;
      const jz = hashf(gx + 101, gz + 57) - 0.5;
      const wx = -SPAN / 2 + (gx + 0.5 + jx * 0.95) * step;
      const wz = -SPAN / 2 + (gz + 0.5 + jz * 0.95) * step;
      const h = terrainHeight(wx, wz);
      if (h < 0.15) continue;                                   // river / wet ground
      if (wx > -29 && wx < -13 && wz > -19 && wz < -9) continue; // house footprint
      const sdx = wx - spawnPos.x, sdz = wz - spawnPos.z;
      if (sdx * sdx + sdz * sdz < 9) continue;                   // clear spawn
      tuftX[tuftCount] = wx; tuftY[tuftCount] = h; tuftZ[tuftCount] = wz;
      // ~1 in 6 is a wildflower clump (smaller); rest are grass tufts.
      const flower = hashf(gx + 41, gz + 83) < 0.17 ? 1 : 0;
      tuftFlower[tuftCount] = flower;
      tuftS[tuftCount] = flower
        ? 0.8 + hashf(gx + 31, gz + 19) * 0.7
        : 0.75 + hashf(gx + 31, gz + 19) * 1.15;
      tuftR[tuftCount] = hashf(gx + 5, gz + 71) * 6.2832;
      tuftCount++;
    }
  }
}

// Perimeter treeline — a ring of extra trees around the playfield to frame the
// arena, give the background depth, and hide the hard terrain edge that an open
// field otherwise ends on. Skips the river band and the house. Same hash so the
// layout is stable build-to-build.
const mdlTreeRing = loadModel('assets/models/prop_tree.glb');
const RTREE_MAX = 64;
const rtX = new Array<number>(RTREE_MAX);
const rtY = new Array<number>(RTREE_MAX);
const rtZ = new Array<number>(RTREE_MAX);
const rtS = new Array<number>(RTREE_MAX);
const rtR = new Array<number>(RTREE_MAX);
let rtCount = 0;
{
  const hashf = (a: number, b: number): number => {
    let h = ((a * 374761393 + b * 668265263) >>> 0);
    h = (((h ^ (h >>> 13)) >>> 0) * 1274126177) >>> 0;
    return ((h ^ (h >>> 16)) >>> 0) / 4294967295;
  };
  const N = 60;
  for (let i = 0; i < N; i++) {
    if (rtCount >= RTREE_MAX) break;
    const ang = (i / N) * 6.2832 + (hashf(i, 2) - 0.5) * 0.12;
    const rad = 27 + hashf(i, 3) * 9;                          // 27–36 m ring
    const wx = Math.cos(ang) * rad;
    const wz = Math.sin(ang) * rad;
    if (wz > 7 && wz < 17) continue;                           // river band
    if (wx > -31 && wx < -11 && wz > -21 && wz < -7) continue; // house
    const h = terrainHeight(wx, wz);
    rtX[rtCount] = wx; rtY[rtCount] = h > 0 ? h : 0; rtZ[rtCount] = wz;
    rtS[rtCount] = 0.9 + hashf(i, 9) * 0.8;
    rtR[rtCount] = hashf(i, 13) * 6.2832;
    rtCount++;
  }
}

function findDormantSlot(kind: number): number {
  for (let j = 0; j < BODIES_PER_KIND; j++) {
    const i = kind * BODIES_PER_KIND + j;
    if (enAlive[i] === 0) return i;
  }
  return -1;
}

function spawnEnemy(): void {
  const kind = WAVE_KINDS[WAVE_OFFS[waveIdx] + waveSpawned];
  const slot = findDormantSlot(kind);
  if (slot < 0) return;   // all bodies of this kind busy; retry next tick
  const sp = waveSpawned % 4;
  enX[slot] = spawnerX[sp];
  enZ[slot] = spawnerZ[sp];
  enY[slot] = enemyGroundY(enX[slot], enZ[slot]);
  enHP[slot] = KIND_HP[kind];
  enAlive[slot] = 1;
  enAttackCD[slot] = 0;
  enFlashT[slot] = 0;
  enPhase[slot] = Math.random() * Math.PI * 2;
  setBodyPosition(enBody[slot],
    vec3(enX[slot], enY[slot] + KIND_Y_OFF[kind], enZ[slot]), true);
  waveSpawned = waveSpawned + 1;
}

// ---- Weapon + combat state (M4 / M5 / M6 / M7) ----------------------------
const PLAYER_HP_MAX = 100;
const FIRE_RANGE = 60.0;

// Weapon registry
const WEAPON_RIFLE = 0;
const WEAPON_BLASTER = 1;
const WEAPON_NAMES = ['RIFLE', 'BLASTER'];
const RIFLE_MAG = 30;
const BLASTER_MAG = 20;
const RIFLE_FIRE_CD = 0.10;   // full-auto, ~600 rpm
const BLASTER_FIRE_CD = 0.35; // tap-fire
const RIFLE_DAMAGE = 1;
const BLASTER_DAMAGE = 2;
const BLASTER_PROJ_SPEED = 40.0;
const BLASTER_PROJ_LIFE = 2.5;
const BLASTER_PROJ_GRAVITY = 9.0;   // m/s^2 — lighter than world gravity for a softer arc

let currentWeapon = WEAPON_RIFLE;
let rifleAmmo = RIFLE_MAG;
let blasterAmmo = BLASTER_MAG;
let fireCD = 0;

let playerHP = PLAYER_HP_MAX;
let gameOver = false;
const MUZZLE_FLASH_DUR = 0.08;
let muzzleFlashT = 0;
let damageFlashT = 0;
let shotsFired = 0;
let shotsHit = 0;

// ---- Projectile pool (M7) -------------------------------------------------
// Fixed-size ring buffer. Each slot stores position, velocity, and
// remaining life. pLife = 0 means the slot is free. Projectiles advance
// each frame via segment-raycast so they can't tunnel through walls.
const MAX_PROJ = 16;
const pX  = new Array<number>(MAX_PROJ);
const pY  = new Array<number>(MAX_PROJ);
const pZ  = new Array<number>(MAX_PROJ);
const pVX = new Array<number>(MAX_PROJ);
const pVY = new Array<number>(MAX_PROJ);
const pVZ = new Array<number>(MAX_PROJ);
const pLife = new Array<number>(MAX_PROJ);
for (let i = 0; i < MAX_PROJ; i++) pLife[i] = 0;
let projNext = 0;

function spawnProjectile(x: number, y: number, z: number,
                         vx: number, vy: number, vz: number): void {
  pX[projNext] = x; pY[projNext] = y; pZ[projNext] = z;
  pVX[projNext] = vx; pVY[projNext] = vy; pVZ[projNext] = vz;
  pLife[projNext] = BLASTER_PROJ_LIFE;
  projNext = (projNext + 1) % MAX_PROJ;
}

// ---- Ammo pickups (M7) ----------------------------------------------------
// Fixed positions around the arena. Walk within PICKUP_RADIUS to collect;
// respawn after PICKUP_RESPAWN seconds so long runs don't starve for ammo.
const PICKUP_RIFLE = 0;
const PICKUP_BLASTER = 1;
const PICKUP_RIFLE_AMT = 15;
const PICKUP_BLASTER_AMT = 8;
const PICKUP_RADIUS = 1.4;
const PICKUP_RESPAWN = 18.0;
const pickupKind = W.PICKUP_KIND;      // 0 = rifle, 1 = blaster (see build-world.ts)
const pickupX    = W.PICKUP_X;
const pickupZ    = W.PICKUP_Z;
const PICKUP_COUNT = W.PICKUP_COUNT;
const pickupActive   = new Array<number>(PICKUP_COUNT);
const pickupRespawnT = new Array<number>(PICKUP_COUNT);
for (let i = 0; i < PICKUP_COUNT; i++) { pickupActive[i] = 1; pickupRespawnT[i] = 0; }

function despawnAllEnemies(): void {
  for (let i = 0; i < MAX_ENEMIES; i++) {
    enAlive[i] = 0;
    enHP[i] = 0;
    enAttackCD[i] = 0;
    enFlashT[i] = 0;
    enPhase[i] = Math.random() * Math.PI * 2;
    enX[i] = 0; enY[i] = -100; enZ[i] = 0;
    setBodyPosition(enBody[i], vec3(0, -100, 0), false);
  }
}

function resetRun(): void {
  currentWeapon = WEAPON_RIFLE;
  rifleAmmo = RIFLE_MAG;
  blasterAmmo = BLASTER_MAG;
  fireCD = 0;
  playerHP = PLAYER_HP_MAX;
  gameOver = false;
  gameWon = false;
  muzzleFlashT = 0;
  damageFlashT = 0;
  shotsFired = 0;
  shotsHit = 0;
  waveIdx = 0;
  waveSpawned = 0;
  waveBreakTimer = WAVE_BREAK_DELAY;
  spawnTimer = 0;
  for (let i = 0; i < MAX_PROJ; i++) pLife[i] = 0;
  for (let i = 0; i < PICKUP_COUNT; i++) { pickupActive[i] = 1; pickupRespawnT[i] = 0; }
  despawnAllEnemies();
}

// Impact sparks — fixed ring buffer to avoid array growth in the hot loop.
const SPARK_MAX = 16;
const sparkX  = new Array<number>(SPARK_MAX);
const sparkY  = new Array<number>(SPARK_MAX);
const sparkZ  = new Array<number>(SPARK_MAX);
const sparkT  = new Array<number>(SPARK_MAX);   // seconds of life remaining; 0 = slot free
for (let i = 0; i < SPARK_MAX; i++) sparkT[i] = 0;
let sparkNext = 0;

function spawnSpark(p: Vec3): void {
  sparkX[sparkNext] = p.x;
  sparkY[sparkNext] = p.y;
  sparkZ[sparkNext] = p.z;
  sparkT[sparkNext] = 0.35;
  sparkNext = (sparkNext + 1) % SPARK_MAX;
}

let cursorLocked = true;
let screenshotSeq = 0;
disableCursor();

// ---- M8 polish: post-FX ---------------------------------------------------
// Called once at startup — these are cheap, always-on stylistic passes.
setVignette(0.38, 0.55);   // cinematic edge darkening (gentle)
setFilmGrain(0.018);       // barely-there noise — 0.05 read as heavy speckle
                           // over the dark sky / shadowed walls.

// ---- High-end rendering pipeline (UE-class), art-directed -----------------
// Full deferred stack + procedural atmosphere. The trick to not washing the
// saturated arena out to grey: keep the sky's image-based ambient modest
// (setEnvIntensity) and a low cool fill, then let a strong WARM directional
// sun carry the lighting and cast the shadows. Manual exposure (not auto) so
// the bright sky doesn't drag the scene's exposure around.
// SUN_DIR is the DIRECTION TO THE SUN (unit-ish). The engine's scene diffuse
// (max(dot(N, light_dir),0)), shadow cascade fit (light placed at center +
// light_dir·d), and the sky-view LUT (mu_s = sun.y) ALL treat this as
// direction-to-sun, so it must point UP (y>0) for daylight. The previous value
// pointed DOWN (y=-0.30) → engine thought the sun was below the horizon: ground
// got no direct sun (flat ambient look) and shadows were fit from a grazing/
// below-horizon light ("weird shadows"). Now upper +x/+z, ~33° elevation.
const SUN_DIR_X = 0.55, SUN_DIR_Y = 0.58, SUN_DIR_Z = 0.42;
setQualityPreset(QualityPreset.High);
setShadowsEnabled(true);
setSsaoEnabled(true);
setSsaoIntensity(0.85);   // 1.15 read as grimy contact-dirt; lighter AO is
setSsaoRadius(0.9);       // more believable for an outdoor daylight scene.
setBloomEnabled(true);
// TAA on — but pin the render scale to 1.0 FIRST: the engine's legacy
// coupling silently drops render_scale to 0.5 (TSR-style half-res
// reconstruction) whenever TAA is enabled and setRenderScale was never
// called explicitly. That meant the game rendered internally at 512×320 —
// the softness and the "camera-move shadow swimming" that prompted the TAA
// bisect were the half-res reconstruction + temporal AO/GI reconverging,
// not a shadow bug. Full res + TAA = real anti-aliasing, no resolution loss.
setTaaEnabled(true);
setRenderScale(1.0);
setSsrEnabled(true);
setSsgiEnabled(true);
setSsgiIntensity(0.6);   // more colour-bounce into the shaded faces (the
                         // building's shadow side picks up warm ground GI
                         // instead of reading as a dead slab).
// Real procedural atmosphere. The earlier grey wash-out came from the sky's
// image-based ambient flooding every surface — keep env-intensity very LOW so
// the warm key sun carries the lighting and colours stay saturated, while the
// sky still provides a proper gradient + sun disc in the background. No fog /
// sun-shafts (their haze was the other half of the wash-out).
setProceduralSky(true);
setSunDirection(vec3(SUN_DIR_X, SUN_DIR_Y, SUN_DIR_Z), 1.0);
// Gentle breeze — sways the alpha-cut foliage cards (engine reads this in the
// scene vertex shader for any alpha-cutout material).
setWind(1.0, 0.4, 0.4, 1.1);
setEnvIntensity(0.50);
// MANUAL exposure (not auto): the bright sky + reflective water cover a big
// chunk of frame and were dragging auto-exposure all over the place, crushing
// the midtones to black on some frames and blowing the walls out on others.
// A fixed exposure gives a stable, art-directed daylight key that the lighting
// ratio above is tuned against.
setAutoExposure(false);
setManualExposure(2.4);
// AgX tonemap (new engine control): more filmic highlight roll-off + punchier
// colour than ACES — keeps the bright sky from greying the scene, and rolls the
// sunlit highlights off smoothly instead of clipping to white. Light touch of
// bloom on the true highlights (muzzle flash, pickups, sun glints).
setTonemap(Tonemap.AgX);
setBloomIntensity(0.05);
// Subtle scene-scale aerial haze. Matched to the sky horizon so distant
// geometry (and the far terrain edge) fades into the sky instead of ending
// on a hard line — adds depth without the grey wash-out that global fog used
// to cause (low density + ground-hugging height falloff keep near surfaces
// crisp). The engine's procedural-sky aerial LUT is km-scaled and negligible
// over this ~80 m arena, so this world-scale march carries the depth cue.
setFog(0.60, 0.71, 0.85, 0.011, 1.0, 0.10);
// (Sun-shafts tried here — even at low strength they flood this open arena
// with haze and wash the colours out, so they stay off.)


// ---- Self-test harness ----------------------------------------------------
// When SELFTEST is true the game auto-fires a shot on frame 30, screenshots
// the scene on frame 60, and exits on frame 90. Used while investigating the
// engine's deferred-render green-screen bug — kept dormant for future debug.
const SELFTEST = false;
let testFrame = 0;


drawLoading(1.0, 'Ready');
while (!windowShouldClose()) {
  beginDrawing();
  const dt = getDeltaTime();
  const sw = getScreenWidth();
  const sh = getScreenHeight();
  updateMusicStream(musicAmbient);

  // Tab toggles cursor capture so you can free the mouse to screenshot etc.
  if (isKeyPressed(Key.TAB)) {
    cursorLocked = !cursorLocked;
    if (cursorLocked) disableCursor();
    else enableCursor();
  }
  // F12 takes a screenshot (sequential filenames)
  if (isKeyPressed(Key.F12)) {
    screenshotSeq = screenshotSeq + 1;
    takeScreenshot('shooter_' + screenshotSeq + '.png');
  }

  const input = readInput();
  testFrame = testFrame + 1;
  // Selftest: drive the player forward so screenshots can verify
  // walk direction. Runs before the player controller update so
  // the override actually reaches updatePlayerController.
  if (SELFTEST && testFrame >= 20) input.moveZ = -1;
  // Only apply mouse look when cursor is captured — avoids jumpy yaw/pitch
  // when the user is moving the mouse outside the window. The first ~10
  // frames after window creation often report giant mouse deltas (system
  // cursor settling into the captured state), which can fling the camera
  // to a useless angle before the player even sees the scene.
  if (cursorLocked && testFrame > 10) {
    CAM[0] = CAM[0] + input.lookX;
    const np = CAM[1] + input.lookY;
    CAM[1] = np < TP_PITCH_MIN ? TP_PITCH_MIN : (np > TP_PITCH_MAX ? TP_PITCH_MAX : np);
  }

  // Restart on R when the run has ended (died or won); otherwise R reloads
  // the currently-equipped weapon.
  if (isKeyPressed(Key.R)) {
    if (gameOver || gameWon) resetRun();
    else if (currentWeapon === WEAPON_RIFLE) rifleAmmo = RIFLE_MAG;
    else blasterAmmo = BLASTER_MAG;
  }
  // Weapon switching with 1/2.
  if (isKeyPressed(Key.ONE))  { currentWeapon = WEAPON_RIFLE;   fireCD = 0; }
  if (isKeyPressed(Key.TWO))  { currentWeapon = WEAPON_BLASTER; fireCD = 0; }

  // Freeze player movement while dead or after victory; physics still steps.
  if (!gameOver && !gameWon) {
    const yawNow = CAM[0];
    const fwd = vec3(Math.sin(yawNow), 0, -Math.cos(yawNow));
    const rgt = vec3(Math.cos(yawNow), 0, Math.sin(yawNow));
    updatePlayerController(dt, input.moveX, input.moveZ, fwd, rgt, input.jump);
  }
  stepPhysics(physics, dt);
  // Third-person (PUBG-style) orbit camera: behind + above the player at the
  // mouse-driven yaw/pitch, smoothly following. The body (drawn below) faces
  // the same yaw, so the mouse turns both camera and character together.
  {
    const pp0 = playerPosition();
    const ya = CAM[0], pi = CAM[1];
    const cpi = Math.cos(pi), spi = Math.sin(pi);
    const fX = pp0.x;
    const fY = pp0.y + TP_EYE_HEIGHT;
    const fZ = pp0.z;
    const wX = fX - Math.sin(ya) * cpi * TP_ORBIT_DIST;
    const wY = fY + spi * TP_ORBIT_DIST;
    const wZ = fZ + Math.cos(ya) * cpi * TP_ORBIT_DIST;
    if (CAM[8] === 0) {
      CAM[2] = wX; CAM[3] = wY; CAM[4] = wZ;
      CAM[5] = fX; CAM[6] = fY; CAM[7] = fZ;
      CAM[8] = 1;
    } else {
      const t = 1 - Math.exp(-TP_SMOOTH * dt);
      CAM[2] = CAM[2] + (wX - CAM[2]) * t;
      CAM[3] = CAM[3] + (wY - CAM[3]) * t;
      CAM[4] = CAM[4] + (wZ - CAM[4]) * t;
      CAM[5] = CAM[5] + (fX - CAM[5]) * t;
      CAM[6] = CAM[6] + (fY - CAM[6]) * t;
      CAM[7] = CAM[7] + (fZ - CAM[7]) * t;
    }
  }
  playerAnimT = playerAnimT + dt;

  // ---- Enemy AI + wave director (M5 / M6) -------------------------------
  if (!gameOver && !gameWon) {
    const pp = playerPosition();
    for (let i = 0; i < MAX_ENEMIES; i++) {
      if (enAlive[i] === 0) continue;
      const k = enKind[i];
      const dx = pp.x - enX[i];
      const dz = pp.z - enZ[i];
      const dist = Math.sqrt(dx * dx + dz * dz);
      if (dist > KIND_MELEE[k]) {
        const step = KIND_SPEED[k] * dt;
        const move = step < dist ? step : dist;
        enX[i] = enX[i] + (dx / dist) * move;
        enZ[i] = enZ[i] + (dz / dist) * move;
        enY[i] = enemyGroundY(enX[i], enZ[i]);
        setBodyPosition(enBody[i],
          vec3(enX[i], enY[i] + KIND_Y_OFF[k], enZ[i]), true);
      } else if (enAttackCD[i] <= 0) {
        playerHP = playerHP - KIND_DMG[k];
        damageFlashT = 0.5;
        enAttackCD[i] = KIND_CD[k];
        playSound(sfxAttack);
        if (playerHP <= 0) { playerHP = 0; gameOver = true; }
      }
      if (enAttackCD[i] > 0) enAttackCD[i] = enAttackCD[i] - dt;
      if (enFlashT[i]   > 0) enFlashT[i]   = enFlashT[i]   - dt;
      enPhase[i] = enPhase[i] + dt;   // seconds into current animation
    }

    // Pickups — proximity collect, respawn after delay.
    for (let i = 0; i < PICKUP_COUNT; i++) {
      if (pickupActive[i] === 0) {
        pickupRespawnT[i] = pickupRespawnT[i] - dt;
        if (pickupRespawnT[i] <= 0) pickupActive[i] = 1;
        continue;
      }
      const pdx = pp.x - pickupX[i];
      const pdz = pp.z - pickupZ[i];
      if (pdx * pdx + pdz * pdz < PICKUP_RADIUS * PICKUP_RADIUS) {
        if (pickupKind[i] === PICKUP_RIFLE) {
          rifleAmmo = Math.min(RIFLE_MAG, rifleAmmo + PICKUP_RIFLE_AMT);
        } else {
          blasterAmmo = Math.min(BLASTER_MAG, blasterAmmo + PICKUP_BLASTER_AMT);
        }
        pickupActive[i] = 0;
        pickupRespawnT[i] = PICKUP_RESPAWN;
        playSound(sfxPickup);
      }
    }

    // Wave director
    const alive = countAlive();
    if (waveIdx < wavePlan.length) {
      if (waveBreakTimer > 0) {
        waveBreakTimer = waveBreakTimer - dt;
      } else {
        const waveSize = wavePlan[waveIdx];
        if (waveSpawned < waveSize && alive < MAX_CONCURRENT) {
          spawnTimer = spawnTimer - dt;
          if (spawnTimer <= 0) {
            spawnEnemy();
            spawnTimer = WAVE_SPAWN_DELAY;
          }
        }
        if (waveSpawned >= waveSize && alive === 0) {
          waveIdx = waveIdx + 1;
          waveSpawned = 0;
          waveBreakTimer = WAVE_BREAK_DELAY;
          if (waveIdx >= wavePlan.length) gameWon = true;
        }
      }
    }
  }

  // testFrame is incremented above the input block so the mouse-settle
  // grace period uses the same counter.
  let forceFire = false;
  if (SELFTEST) {
    waveBreakTimer = 9999;
    if (testFrame < 5) { CAM[0] = 0; CAM[1] = 0.35; CAM[8] = 0; }
    if (testFrame === 5) {
      // Manually spawn ONE dretch off to the side, stays idle.
      enX[0] = -6; enY[0] = 0; enZ[0] = -6;
      enHP[0] = 3; enAlive[0] = 1; enAttackCD[0] = 999;
      setBodyPosition(enBody[0], vec3(-6, KIND_Y_OFF[0], -6), true);
    }
    if (testFrame === 30)  { screenshotSeq++; takeScreenshot('shooter_selftest_' + screenshotSeq + '_t0_5s.png'); }
    if (testFrame === 180) { screenshotSeq++; takeScreenshot('shooter_selftest_' + screenshotSeq + '_t3_0s.png'); break; }
  }

  // ---- Fire (M4 / M7) ---------------------------------------------------
  if (fireCD > 0) fireCD = fireCD - dt;
  const combatActive = !gameOver && !gameWon && cursorLocked;
  const isRifle    = currentWeapon === WEAPON_RIFLE;
  const haveAmmo   = isRifle ? rifleAmmo > 0 : blasterAmmo > 0;
  // Rifle = full-auto (mouse held); blaster = tap (press edge only).
  const fireIntent = combatActive && haveAmmo && fireCD <= 0 &&
                     (isRifle ? input.fireDown : input.firePressed);
  if (fireIntent || (forceFire && haveAmmo && combatActive)) {
    shotsFired = shotsFired + 1;
    muzzleFlashT = MUZZLE_FLASH_DUR;
    playSound(sfxFire);
    // Third-person aiming: the crosshair is at screen centre, so
    // trace the camera-forward line out to a far point, treat that
    // as the aim target, and fire from the player's shoulder toward
    // it. This way visible tracers / sparks line up with the gun
    // barrel in the world, not with the orbit-camera position. The
    // parallax between camera ray and muzzle ray is tiny at normal
    // engagement ranges and is what gives the shot its "from the
    // player" feel.
    const camOriginV = vec3(CAM[2], CAM[3], CAM[4]);
    const adx = CAM[5] - CAM[2], ady = CAM[6] - CAM[3], adz = CAM[7] - CAM[4];
    const alen = Math.sqrt(adx*adx + ady*ady + adz*adz);
    const camFwd = alen > 0 ? vec3(adx/alen, ady/alen, adz/alen) : vec3(0, 0, -1);
    const aimTargetFar = 200;
    const tgtX = camOriginV.x + camFwd.x * aimTargetFar;
    const tgtY = camOriginV.y + camFwd.y * aimTargetFar;
    const tgtZ = camOriginV.z + camFwd.z * aimTargetFar;
    // Muzzle = player shoulder offset (matches the drawn weapon).
    const ppF = playerPosition();
    const sy = Math.sin(CAM[0]), cy = Math.cos(CAM[0]);
    const originX = ppF.x + cy * 0.30 + sy * 0.60;
    const originY = ppF.y + 0.95;
    const originZ = ppF.z + sy * 0.30 + (-cy) * 0.60;
    const mdx = tgtX - originX, mdy = tgtY - originY, mdz = tgtZ - originZ;
    const mlen = Math.sqrt(mdx*mdx + mdy*mdy + mdz*mdz);
    const aim = mlen > 0 ? vec3(mdx/mlen, mdy/mlen, mdz/mlen) : camFwd;

    if (isRifle) {
      rifleAmmo = rifleAmmo - 1;
      fireCD = RIFLE_FIRE_CD;
      const hit = raycast(physics, vec3(originX, originY, originZ), aim,
                          FIRE_RANGE, ALL_LAYERS_MASK);
      if (hit) {
        shotsHit = shotsHit + 1;
        spawnSpark(hit.point);
        for (let i = 0; i < MAX_ENEMIES; i++) {
          if (enAlive[i] > 0 && hit.body === enBody[i]) {
            enHP[i] = enHP[i] - RIFLE_DAMAGE;
            enFlashT[i] = DRETCH_HIT_FLASH;
            if (enHP[i] <= 0) {
              enAlive[i] = 0;
              enY[i] = -100;
              setBodyPosition(enBody[i], vec3(enX[i], -100, enZ[i]), false);
              playSound(sfxAttack);   // reuse clank as death thud
            }
            break;
          }
        }
      }
    } else {
      blasterAmmo = blasterAmmo - 1;
      fireCD = BLASTER_FIRE_CD;
      spawnProjectile(originX, originY, originZ,
                      aim.x * BLASTER_PROJ_SPEED,
                      aim.y * BLASTER_PROJ_SPEED,
                      aim.z * BLASTER_PROJ_SPEED);
    }
  }

  // ---- Projectile update (M7) -------------------------------------------
  // Apply gravity, then segment-raycast from old pos to new pos so fast or
  // arcing shots can't tunnel through walls or enemy colliders.
  for (let i = 0; i < MAX_PROJ; i++) {
    if (pLife[i] <= 0) continue;
    pVY[i] = pVY[i] - BLASTER_PROJ_GRAVITY * dt;
    const ox = pX[i], oy = pY[i], oz = pZ[i];
    const nx = ox + pVX[i] * dt;
    const ny = oy + pVY[i] * dt;
    const nz = oz + pVZ[i] * dt;
    const sx = nx - ox, sy = ny - oy, sz = nz - oz;
    const segLen = Math.sqrt(sx * sx + sy * sy + sz * sz);
    const inv = segLen > 0 ? 1 / segLen : 0;
    const hit = raycast(physics, vec3(ox, oy, oz),
                        vec3(sx * inv, sy * inv, sz * inv),
                        segLen, ALL_LAYERS_MASK);
    if (hit) {
      spawnSpark(hit.point);
      for (let j = 0; j < MAX_ENEMIES; j++) {
        if (enAlive[j] > 0 && hit.body === enBody[j]) {
          enHP[j] = enHP[j] - BLASTER_DAMAGE;
          enFlashT[j] = DRETCH_HIT_FLASH;
          shotsHit = shotsHit + 1;
          if (enHP[j] <= 0) {
            enAlive[j] = 0;
            enY[j] = -100;
            setBodyPosition(enBody[j], vec3(enX[j], -100, enZ[j]), false);
            playSound(sfxAttack);
          }
          break;
        }
      }
      pLife[i] = 0;
    } else {
      pX[i] = nx; pY[i] = ny; pZ[i] = nz;
      pLife[i] = pLife[i] - dt;
    }
  }
  if (muzzleFlashT > 0) muzzleFlashT = muzzleFlashT - dt;
  if (damageFlashT > 0) damageFlashT = damageFlashT - dt;
  for (let i = 0; i < SPARK_MAX; i++) {
    if (sparkT[i] > 0) sparkT[i] = sparkT[i] - dt;
  }

  clearBackground({ r: Math.floor(W.ENV_SKY_R * 255),
                    g: Math.floor(W.ENV_SKY_G * 255),
                    b: Math.floor(W.ENV_SKY_B * 255), a: 255 });
  // Sun + ambient MUST be set every frame: the engine's begin_frame resets
  // the whole lighting block to LightingUniforms::defaults() (immediate-mode
  // convention — renderer/mod.rs begin_frame), so anything set only at init
  // silently reverts to default lighting from frame 2 onward. Key:fill ratio
  // ~6:1 — natural outdoor daylight: shadowed faces read as blue-grey
  // daylight instead of crushed black, sunlit stone stays below clipping.
  setAmbientLight({ r: 120, g: 138, b: 168, a: 255 }, 0.40);
  setDirectionalLight(vec3(SUN_DIR_X, SUN_DIR_Y, SUN_DIR_Z),
                      { r: 255, g: 236, b: 206, a: 255 }, 2.0);
  // TEMP verification camera (off → normal third-person view).
  const VERIFY_WATER = false;
  const VERIFY_BEAUTY = false;
  beginMode3D(VERIFY_CALIB ? {
    position: vec3(3, 6.6, 9.5),
    target:   vec3(3, 6.0, -2.0),
    up: vec3(0, 1, 0),
    fovy: 58,
    projection: 0,
  } : VERIFY_BEAUTY ? {
    position: vec3(-2, 6.0, 22.0),
    target:   vec3(13, 0.6, 2.0),
    up: vec3(0, 1, 0),
    fovy: 60,
    projection: 0,
  } : VERIFY_WATER ? {
    position: vec3(6, 1.1, 16.0),
    target:   vec3(4, 0.1, 11.0),
    up: vec3(0, 1, 0),
    fovy: 60,
    projection: 0,
  } : {
    position: vec3(CAM[2], CAM[3], CAM[4]),
    target:   vec3(CAM[5], CAM[6], CAM[7]),
    up: vec3(0, 1, 0),
    fovy: TP_FOVY,
    projection: 0,
  });

  // Muzzle flare point light — sits just past the barrel tip so
  // the warm splash of light hits the gun body and the floor in
  // front of the player when firing.
  if (muzzleFlashT > 0) {
    const pp = playerPosition();
    const sy = Math.sin(CAM[0]), cy = Math.cos(CAM[0]);
    const tipOffset = currentWeapon === WEAPON_RIFLE ? 0.78 : 0.43;
    const mx = pp.x + cy * 0.30 + sy * tipOffset;
    const my = pp.y + 0.95;
    const mz = pp.z + sy * 0.30 + (-cy) * tipOffset;
    const k = muzzleFlashT / MUZZLE_FLASH_DUR;
    addPointLight(mx, my, mz, 6, 1.0, 0.85, 0.5, 4.0 * k);
  }

  // ---- World: static meshes + water + lights (all from generated/world.ts) -
  // Ground plate — big drawCube beneath the terrain mesh so the full
  // 80×80 collider floor reads as a solid plane even where the hills
  // haven't lifted anything off it. Matches COLLIDER[0] (the plaza floor).
  drawCube(vec3(W.COLLIDER_X[0], W.COLLIDER_Y[0], W.COLLIDER_Z[0]),
           W.COLLIDER_HALF_X[0] * 2, W.COLLIDER_HALF_Y[0] * 2, W.COLLIDER_HALF_Z[0] * 2,
           { r: 85, g: 95, b: 75, a: 255 });

  // Phase 1c smoke test — colour-pulsed cube in front of spawn,
  // rendered via the new material pipeline. Proves the compile →
  // submit → dispatch path works on a real frame.
  if (MAT_SMOKE && matTest > 0 && matTestMesh > 0) {
    drawMeshWithMaterial(matTest, matTestMesh,
      vec3(0, 3, 15), 3.0, { r: 255, g: 255, b: 255, a: 255 });
  }
  // Static meshes — either drawModel for real GLBs, or coloured drawCube
  // for placeholder _gizmo_box.glb entries. MESH_CATEGORY drives the cube
  // tint (0 generic / 1 building / 2 terrain / 3 prop).
  for (let i = 0; i < W.MESH_COUNT; i++) {
    const mi = W.MESH_MODEL_IDX[i];
    if (W.MODEL_IS_BOX[mi] === 1) {
      const c = W.MESH_CATEGORY[i];
      // Building boxes (category 1) are drawn collectively as the stone-textured
      // house.glb below — skip their flat-grey placeholder cubes here.
      if (c === 1) continue;
      const col = { r: MESH_TINT_R[c], g: MESH_TINT_G[c], b: MESH_TINT_B[c], a: 255 };
      drawCube(vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
               W.MESH_COLLIDER_HX[i] * 2, W.MESH_COLLIDER_HY[i] * 2, W.MESH_COLLIDER_HZ[i] * 2,
               col);
    } else {
      drawModel(meshModelHandles[mi],
                vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
                W.MESH_SCALE[i], WHITE);
    }
  }
  // The house — one stone-textured mesh baked from every building box, with
  // world-space vertices, so it draws at the origin with identity transform.
  drawModel(mdlHouse, vec3(0, 0, 0), 1.0, WHITE);
  if (VERIFY_CALIB) drawModel(mdlCalib, CALIB_AT, 1.0, WHITE);
  // Scattered ground grass tufts + wildflowers (alpha-cutout, wind-swaying).
  for (let i = 0; i < tuftCount; i++) {
    const mdl = tuftFlower[i] === 1 ? mdlFlower : mdlGrassTuft;
    drawModelRotated(mdl, vec3(tuftX[i], tuftY[i], tuftZ[i]),
                     tuftS[i], tuftR[i], WHITE);
  }
  // Perimeter treeline framing the arena.
  for (let i = 0; i < rtCount; i++) {
    drawModelRotated(mdlTreeRing, vec3(rtX[i], rtY[i], rtZ[i]),
                     rtS[i], rtR[i], WHITE);
  }
  // Water — one reflective material plane per river segment (see WATER_WGSL
  // setup near the top). The planar-reflection probe renders the mirrored
  // scene each frame; the shader blends it with Fresnel + animated wave
  // normals + a sun glint. Far cheaper than the old ~1800 cubes/frame and
  // actually reflects the world above the surface.
  if (waterMat > 0) {
    drawMeshWithMaterial(waterMat, waterMesh,
      vec3(RIVER_CX, waterY, RIVER_CZ), 1.0, WHITE);
  }
  // Point lights from the world file — static scene lights.
  for (let i = 0; i < W.LIGHT_COUNT; i++) {
    addPointLight(W.LIGHT_X[i], W.LIGHT_Y[i], W.LIGHT_Z[i],
                  W.LIGHT_RANGE[i],
                  W.LIGHT_R[i], W.LIGHT_G[i], W.LIGHT_B[i],
                  W.LIGHT_INT[i]);
  }

  // Player: skinned + animated. Face the camera's horizontal yaw (so the
  // character always looks "away from the camera"). Walk if input is
  // nonzero, idle otherwise. A debug sphere at the capsule centre is
  // always drawn as a fallback so the player's position is visible even
  // if the skinned model fails to render.
  {
    const pp = playerPosition();
    const moving = input.moveX !== 0 || input.moveZ !== 0;
    const camYaw = CAM[0];
    // Player_bsuit's rest pose faces +X in model space (Unvanquished
    // convention, preserved through our X90 Z-up→Y-up root fix).
    // Camera-yaw forward at yaw=0 is -Z, so rotate the model by
    // +π/2 about Y to line the character's front with the camera
    // direction. The bsuit's only "attack" animation is a melee
    // swing — a ranged shooter shouldn't use it; keep the walk/idle
    // pose and fake recoil + muzzle flash on the weapon itself.
    // Face the camera's look direction (PUBG/aim-style), always.
    // updateModelAnimation takes a SINGLE Y angle (radians) now — the old
    // (sin,cos) overload was removed (the extra arg was silently dropped, so the
    // body rotated by sin(camYaw) rad ≈ ±57° and "stayed looking left").
    // set_joint_matrices_scaled maps the model's +X rest-facing to
    // (cosθ,-sinθ); the camera looks along (sin camYaw, -cos camYaw), so
    // θ = π/2 - camYaw. (General: to face world dir (dx,dz), rot_y = atan2(-dz,dx).)
    const rotY = Math.PI / 2 - camYaw;
    const panim = moving ? PLAYER_ANIM_WALK : PLAYER_ANIM_IDLE;
    // Third-person (PUBG-style): render the character body.
    const FIRST_PERSON = false;
    if (!FIRST_PERSON) {
      updateModelAnimation(animPlayer, panim, playerAnimT, PLAYER_SCALE,
        pp.x, pp.y + PLAYER_MODEL_Y_OFFSET, pp.z, rotY);
      drawModel(mdlPlayer, vec3(pp.x, pp.y + PLAYER_MODEL_Y_OFFSET, pp.z),
                PLAYER_SCALE, WHITE);
    }

    // Held weapon — sketched from cubes since we don't yet have a
    // converted tpweapon GLB. Rifle is a long grey body + thin
    // barrel; blaster is a short stubby pistol. Positioned at the
    // character's right shoulder. On fire the weapon recoils
    // backward for one MUZZLE_FLASH_DUR tick (≈0.08s) and a warm
    // flash sprite appears at the barrel tip — the exponential
    // falloff on recoilT reads as a snap-back rather than a slide.
    const shy = Math.sin(camYaw), chy = Math.cos(camYaw);
    const fx = shy;         // camera forward (horizontal) at this yaw
    const fz = -chy;
    const rx = chy;         // camera right
    const rz = shy;
    const recoilT = muzzleFlashT > 0 ? muzzleFlashT / MUZZLE_FLASH_DUR : 0;
    const recoilK = recoilT * recoilT;        // snappier than linear
    const recoilBack = recoilK * 0.18;        // metres pulled toward shooter
    const shoulder = vec3(
      pp.x + rx * 0.30 + fx * (0.15 - recoilBack),
      pp.y + 0.95,
      pp.z + rz * 0.30 + fz * (0.15 - recoilBack),
    );
    const bodyDark = { r: 55, g: 55, b: 60, a: 255 };
    const bodyMid  = { r: 90, g: 90, b: 100, a: 255 };
    let muzzleX = shoulder.x, muzzleY = shoulder.y, muzzleZ = shoulder.z;
    if (currentWeapon === WEAPON_RIFLE) {
      drawCube(shoulder, 0.12, 0.10, 0.55, bodyMid);
      const barrelLen = 0.45;
      const barrelX = shoulder.x + fx * barrelLen;
      const barrelY = shoulder.y;
      const barrelZ = shoulder.z + fz * barrelLen;
      drawCube(vec3(barrelX, barrelY, barrelZ), 0.06, 0.06, 0.35, bodyDark);
      muzzleX = shoulder.x + fx * (barrelLen + 0.18);
      muzzleY = shoulder.y;
      muzzleZ = shoulder.z + fz * (barrelLen + 0.18);
    } else {
      drawCube(shoulder, 0.10, 0.14, 0.22, bodyMid);
      const bx = shoulder.x + fx * 0.18;
      const bz = shoulder.z + fz * 0.18;
      drawCube(vec3(bx, shoulder.y + 0.02, bz), 0.05, 0.05, 0.15, bodyDark);
      muzzleX = shoulder.x + fx * 0.28;
      muzzleY = shoulder.y + 0.02;
      muzzleZ = shoulder.z + fz * 0.28;
    }

    // Muzzle flash — bright yellow core + wider orange halo that
    // fades with muzzleFlashT. Two overlapping spheres read as a
    // burst of flame even at small pixel sizes.
    if (muzzleFlashT > 0) {
      const k = muzzleFlashT / MUZZLE_FLASH_DUR;
      const coreA = Math.min(255, Math.floor(k * 255));
      const haloA = Math.min(200, Math.floor(k * 170));
      const coreR = 0.10 + (1 - k) * 0.04;       // quick puff-out
      const haloR = 0.22 + (1 - k) * 0.10;
      drawSphere(vec3(muzzleX, muzzleY, muzzleZ), haloR,
        { r: 255, g: 130, b:  40, a: haloA });
      drawSphere(vec3(muzzleX, muzzleY, muzzleZ), coreR,
        { r: 255, g: 240, b: 170, a: coreA });
    }
  }
  // Per-enemy: drive the skinned skeleton via updateModelAnimation (picks
  // attack vs walk anim), then drawModel renders with the pose from the
  // joint matrices set by the update. Both calls use the same position so
  // non-skinned fallbacks still sit in the right place.
  const ppAim = playerPosition();
  for (let i = 0; i < MAX_ENEMIES; i++) {
    if (enAlive[i] === 0) continue;
    const k = enKind[i];
    const dxA = ppAim.x - enX[i];
    const dzA = ppAim.z - enZ[i];
    const distA = Math.sqrt(dxA * dxA + dzA * dzA);
    // Single Y angle (radians) — face the player. To face world dir (dx,dz):
    // rot_y = atan2(-dz, dx) (see player facing note). atan2(0,0)→0 is fine.
    const enRotY = Math.atan2(-dzA, dxA);
    const attacking = distA <= KIND_MELEE[k];
    const animIdx = attacking ? ANIM_ATTACK_IDX[k] : ANIM_WALK_IDX[k];
    updateModelAnimation(animAliens[k], animIdx, enPhase[i], KIND_SCALE[k],
      enX[i], enY[i], enZ[i], enRotY);
    const f = enFlashT[i] > 0 ? enFlashT[i] / DRETCH_HIT_FLASH : 0;
    const tint = f > 0
      ? { r: 255,
          g: Math.floor(255 * (1 - f)),
          b: Math.floor(255 * (1 - f)),
          a: 255 }
      : WHITE;
    drawModel(mdlAliens[k], vec3(enX[i], enY[i], enZ[i]), KIND_SCALE[k], tint);
  }
  // Pickups — bobbing cubes, color-coded per kind.
  const tNow = getTime();
  for (let i = 0; i < PICKUP_COUNT; i++) {
    if (pickupActive[i] === 0) continue;
    const bob = 0.8 + Math.sin(tNow * 3.0 + i) * 0.15;
    const isRifleKind = pickupKind[i] === PICKUP_RIFLE;
    const col = isRifleKind
      ? { r: 240, g: 200, b: 80,  a: 255 }    // gold = rifle
      : { r: 120, g: 220, b: 240, a: 255 };   // cyan = blaster
    drawCube(vec3(pickupX[i], bob, pickupZ[i]), 0.4, 0.4, 0.4, col);
    // Glow sphere around the cube for visibility.
    drawSphere(vec3(pickupX[i], bob, pickupZ[i]), 0.55,
      { r: col.r, g: col.g, b: col.b, a: 60 });
  }
  // Impact sparks — small yellow puffs that fade over 0.35s.
  for (let i = 0; i < SPARK_MAX; i++) {
    if (sparkT[i] > 0) {
      const t = sparkT[i] / 0.35;
      const a = Math.min(255, Math.floor(t * 255));
      drawSphere(vec3(sparkX[i], sparkY[i], sparkZ[i]), 0.25 * t + 0.05,
        { r: 255, g: 240, b: 140, a });
    }
  }
  // Blaster projectiles — glowing cyan spheres.
  for (let i = 0; i < MAX_PROJ; i++) {
    if (pLife[i] > 0) {
      drawSphere(vec3(pX[i], pY[i], pZ[i]), 0.16,
        { r: 140, g: 220, b: 255, a: 255 });
    }
  }
  endMode3D();

  // Crosshair — brighten while firing
  const crossA = muzzleFlashT > 0 ? 240 : 160;
  drawCircle(sw / 2, sh / 2, 3, { r: 255, g: 255, b: 255, a: crossA });
  // Muzzle flash — small warm smudge near the crosshair, not full-screen.
  if (muzzleFlashT > 0) {
    const fa = Math.floor((muzzleFlashT / MUZZLE_FLASH_DUR) * 180);
    drawCircle(sw / 2, sh / 2 + 4, 14, { r: 255, g: 220, b: 120, a: fa });
  }

  // Damage vignette — red screen edges when the player takes a hit.
  if (damageFlashT > 0) {
    const fa = Math.floor((damageFlashT / 0.5) * 120);
    drawRect(0, 0, sw, 60, { r: 200, g: 20, b: 20, a: fa });
    drawRect(0, sh - 60, sw, 60, { r: 200, g: 20, b: 20, a: fa });
    drawRect(0, 0, 60, sh, { r: 200, g: 20, b: 20, a: fa });
    drawRect(sw - 60, 0, 60, sh, { r: 200, g: 20, b: 20, a: fa });
  }

  // Player HP bar — bottom-left.
  const phpW = 220;
  const phpFill = Math.max(0, Math.floor(phpW * (playerHP / PLAYER_HP_MAX)));
  drawRect(10, sh - 68, phpW, 18, { r: 30, g: 10, b: 10, a: 180 });
  drawRect(10, sh - 68, phpFill, 18, { r: 180, g: 60, b: 50, a: 230 });
  drawText('HP ' + playerHP, 18, sh - 65, 14, { r: 240, g: 240, b: 240, a: 255 });

  // Weapon + ammo — bottom-right.
  const isRifleHud = currentWeapon === WEAPON_RIFLE;
  const curAmmo = isRifleHud ? rifleAmmo : blasterAmmo;
  const curMag  = isRifleHud ? RIFLE_MAG : BLASTER_MAG;
  const wtxt = WEAPON_NAMES[currentWeapon] + '  ' + curAmmo + ' / ' + curMag;
  drawRect(sw - 260, sh - 68, 250, 18, { r: 0, g: 0, b: 0, a: 150 });
  drawText(wtxt + '   [1/2 switch  R reload]',
           sw - 252, sh - 65, 13, { r: 240, g: 230, b: 180, a: 255 });

  // Wave HUD — top-center. Shows "WAVE X — enemies K/N" while spawning,
  // or a "NEXT WAVE IN ..." countdown between waves.
  const aliveNow = countAlive();
  if (!gameOver && !gameWon) {
    if (waveBreakTimer > 0 && waveIdx < wavePlan.length) {
      const label = 'WAVE ' + (waveIdx + 1) + ' IN ' + waveBreakTimer.toFixed(1) + 's';
      const lw = measureText(label, 22);
      drawText(label, (sw - lw) / 2, 18, 22, { r: 230, g: 220, b: 160, a: 230 });
    } else if (waveIdx < wavePlan.length) {
      const waveSize = wavePlan[waveIdx];
      const remaining = (waveSize - waveSpawned) + aliveNow;
      const label = 'WAVE ' + (waveIdx + 1) + ' — ' + remaining + ' / ' + waveSize;
      const lw = measureText(label, 20);
      drawText(label, (sw - lw) / 2, 18, 20, { r: 230, g: 220, b: 160, a: 230 });
    }
  }

  // Game over overlay.
  if (gameOver) {
    drawRect(0, 0, sw, sh, { r: 0, g: 0, b: 0, a: 170 });
    const msg = 'YOU DIED';
    const mw = measureText(msg, 56);
    drawText(msg, (sw - mw) / 2, sh * 0.35, 56, { r: 220, g: 60, b: 50, a: 255 });
    const sub = 'Reached wave ' + (waveIdx + 1) + ' — press R to restart';
    const sww = measureText(sub, 22);
    drawText(sub, (sw - sww) / 2, sh * 0.35 + 72, 22, { r: 220, g: 220, b: 220, a: 230 });
  }

  // Victory overlay.
  if (gameWon) {
    drawRect(0, 0, sw, sh, { r: 0, g: 0, b: 0, a: 170 });
    const msg = 'ARENA CLEARED';
    const mw = measureText(msg, 52);
    drawText(msg, (sw - mw) / 2, sh * 0.33, 52, { r: 180, g: 230, b: 180, a: 255 });
    const sub = 'Survived all ' + wavePlan.length + ' waves — press R to play again';
    const sww = measureText(sub, 22);
    drawText(sub, (sw - sww) / 2, sh * 0.33 + 70, 22, { r: 220, g: 220, b: 220, a: 230 });
  }

  // Diagnostic HUD — helps verify input is reaching the game
  const pp = playerPosition();
  const diag1 = 'FPS ' + Math.floor(getFPS())
    + '  world: ' + worldStatus
    + '  WASD:' + input.moveX.toFixed(1) + ',' + input.moveZ.toFixed(1)
    + '  jump:' + (input.jump ? '1' : '0')
    + '  fire:' + (input.fireDown ? '1' : '0')
    + '  mouse:' + (cursorLocked ? 'locked (Tab to free)' : 'free (Tab to lock)');
  const diag2 = 'pos ' + pp.x.toFixed(1) + ',' + pp.y.toFixed(1) + ',' + pp.z.toFixed(1)
    + '  yaw ' + CAM[0].toFixed(2) + '  pitch ' + CAM[1].toFixed(2)
    + '  cam ' + CAM[2].toFixed(1) + ',' + CAM[3].toFixed(1) + ',' + CAM[4].toFixed(1)
    + '  shots ' + shotsHit + '/' + shotsFired;

  drawRect(0, sh - 44, sw, 44, { r: 0, g: 0, b: 0, a: 150 });
  drawText(diag1, 10, sh - 40, 13, { r: 200, g: 210, b: 230, a: 220 });
  drawText(diag2, 10, sh - 20, 13, { r: 180, g: 200, b: 220, a: 220 });

  if (isKeyPressed(Key.ESCAPE)) break;
  endDrawing();
}
