import {
  initWindow, windowShouldClose, beginDrawing, endDrawing, clearBackground,
  setTargetFPS, getDeltaTime, getFPS, getTime,
  beginMode3D, endMode3D,
  drawCube, drawSphere, drawText, drawRect, drawCircle, measureText,
  setAmbientLight, setDirectionalLight,
  getScreenWidth, getScreenHeight,
  vec3,
  isKeyPressed, Key, Vec3, injectKeyDown, injectKeyUp,
  disableCursor, enableCursor, takeScreenshot,
  loadModel, drawModel, loadModelAnimation, updateModelAnimation,
  createMesh, compileMaterial, drawMeshWithMaterial,
  initAudio, loadSound, playSound, setSoundVolume,
  loadMusic, playMusic, updateMusicStream, setMusicVolume,
} from 'bloom';
import { setVignette, setFilmGrain } from 'bloom/core';
import { addPointLight } from 'bloom/scene';
import {
  createWorld, step as stepPhysics,
  boxShape, heightfieldShape, createBody, MotionType, Layer,
  setLayerCollides, raycast, ALL_LAYERS_MASK, BodyHandle,
  setBodyPosition,
} from 'bloom/physics';
import { initInput, readInput } from './input';
import { createPlayer, updatePlayerController, playerPosition } from './player';
import * as W from './generated/world';
import * as T from './generated/terrain';

initWindow(1024, 640, 'Bloom Shooter');
setTargetFPS(60);
initInput();

// ---- M8 polish: audio -----------------------------------------------------
initAudio();
const sfxFire = loadSound('assets/sounds/rifle_fire.wav');
const sfxAttack = loadSound('assets/sounds/dretch_attack.wav');
const sfxPickup = loadSound('assets/sounds/pickup.wav');
setSoundVolume(sfxFire, 0.35);
setSoundVolume(sfxAttack, 0.6);
setSoundVolume(sfxPickup, 0.8);
const musicAmbient = loadMusic('assets/sounds/ambient.ogg');
setMusicVolume(musicAmbient, 0.35);
playMusic(musicAmbient);

const physics = createWorld({ gravity: vec3(0, -20, 0) });
// Make NON_MOVING (static) and MOVING (character/dynamic) collide.
setLayerCollides(physics, Layer.NON_MOVING, Layer.MOVING, true);
setLayerCollides(physics, Layer.MOVING, Layer.MOVING, true);

// ---- World: arena_02 (see src/generated/world.ts) -------------------------
// Authored in assets/worlds/arena_02.world.json; flat-array TS module is
// regenerated by tools/build-world.ts before every build. All geometry,
// lighting, spawners, pickups, and the wave plan come from that world data.
// The editor can read/write the same JSON → one source of truth.

const spawnPos: Vec3 = vec3(W.SPAWN_X, W.SPAWN_Y, W.SPAWN_Z);
const spawnYaw = W.SPAWN_YAW;

// Apply environment settings from the world file.
setAmbientLight(
  { r: Math.floor(W.ENV_AMBIENT_R * 255), g: Math.floor(W.ENV_AMBIENT_G * 255),
    b: Math.floor(W.ENV_AMBIENT_B * 255), a: 255 },
  W.ENV_AMBIENT_I);
setDirectionalLight(
  vec3(W.ENV_SUN_DIR_X, W.ENV_SUN_DIR_Y, W.ENV_SUN_DIR_Z),
  { r: Math.floor(W.ENV_SUN_R * 255), g: Math.floor(W.ENV_SUN_G * 255),
    b: Math.floor(W.ENV_SUN_B * 255), a: 255 },
  W.ENV_SUN_I);

// Static box colliders — invisible physics walls that bound the plaza
// and carry the ground plane.
for (let i = 0; i < W.COLLIDER_COUNT; i++) {
  const shape = boxShape(vec3(W.COLLIDER_HALF_X[i], W.COLLIDER_HALF_Y[i], W.COLLIDER_HALF_Z[i]));
  createBody(physics, shape, {
    motionType: MotionType.STATIC,
    position: vec3(W.COLLIDER_X[i], W.COLLIDER_Y[i], W.COLLIDER_Z[i]),
    objectLayer: Layer.NON_MOVING,
    friction: 0.9,
  });
}

// Heightfield terrain collider — matches assets/models/terrain_hills.glb.
// Samples in TERRAIN_HEIGHTS are row-major z*width+x; engine's heightfield
// shape takes an origin + scale (cellSize in X/Z, Y=1 since the heights
// are already in world units) and builds a Jolt HeightFieldShape.
{
  const shape = heightfieldShape(
    T.TERRAIN_HEIGHTS, T.TERRAIN_SAMPLE_COUNT,
    vec3(T.TERRAIN_ORIGIN_X, T.TERRAIN_ORIGIN_Y, T.TERRAIN_ORIGIN_Z),
    vec3(T.TERRAIN_CELL_SIZE, 1, T.TERRAIN_CELL_SIZE));
  createBody(physics, shape, {
    motionType: MotionType.STATIC,
    position: vec3(0, 0, 0),
    objectLayer: Layer.NON_MOVING,
    friction: 0.95,
  });
}

// Drawable meshes: each static_mesh entity references a modelRef via
// MESH_MODEL_IDX → UNIQUE_MODELS. Real GLBs are loaded once here and
// drawn via drawModel each frame. Box-placeholder entries (modelRef
// `_gizmo_box.glb`) get a coloured drawCube fallback at draw time,
// tinted by category (0 = generic, 1 = building stone, 2 = terrain
// green, 3 = prop brown).
const MESH_TINT_R = [150, 196, 120, 130];
const MESH_TINT_G = [148, 168,  90,  95];
const MESH_TINT_B = [140, 130,  70,  80];
const meshModelHandles = new Array<number>(W.UNIQUE_MODEL_COUNT);
for (let i = 0; i < W.UNIQUE_MODEL_COUNT; i++) {
  meshModelHandles[i] = W.MODEL_IS_BOX[i] === 1 ? 0 : loadModel(W.UNIQUE_MODELS[i]);
}
// Per-mesh collider from userData.collider === 'box'.
for (let i = 0; i < W.MESH_COUNT; i++) {
  if (W.MESH_COLLIDER[i] === 1) {
    const shape = boxShape(vec3(W.MESH_COLLIDER_HX[i], W.MESH_COLLIDER_HY[i], W.MESH_COLLIDER_HZ[i]));
    createBody(physics, shape, {
      motionType: MotionType.STATIC,
      position: vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
      objectLayer: Layer.NON_MOVING,
      friction: 0.9,
    });
  }
}
const worldStatus = W.WORLD_NAME + ' (' + W.COLLIDER_COUNT + '+' + W.MESH_COUNT + ' bodies)';


createPlayer(physics, spawnPos);

// ---- Third-person orbit camera (inline; see perry-quirks.md) --------------
// Array-slot state because Perry 0.5.158 doesn't propagate module-scope
// `let` reassignments across function calls. Cross-module array writes
// are even more fragile; keeping everything local to main.ts so the
// compiler has no excuse to lose the writes.
//   CAM[0] yaw           CAM[5] tgtX
//   CAM[1] pitch         CAM[6] tgtY
//   CAM[2] camX          CAM[7] tgtZ
//   CAM[3] camY          CAM[8] initialised (0/1)
//   CAM[4] camZ
const CAM = [spawnYaw, 0.35, 0, 0, 0, 0, 0, 0, 0];
const TP_PITCH_MIN = -0.25;
const TP_PITCH_MAX = 1.20;
const TP_ORBIT_DIST = 6.0;
const TP_EYE_HEIGHT = 1.4;
const TP_SMOOTH = 10.0;
const TP_FOVY = 70;

// ---- Third-person player model (human_bsuit) -----------------------------
// Converted via tools/convert-aliens-anim.ts. Drawn at the physics-character
// position, facing the camera's horizontal yaw so the player always looks
// "away from the camera" (classic 3rd-person over-the-shoulder feel).
const mdlPlayer  = loadModel('assets/models/player_bsuit.glb');
const animPlayer = loadModelAnimation('assets/models/player_bsuit.glb');
// human_bsuit animation indices (IQE declaration order):
//   0 idle, 7 attack, 8 run, 12 walk.
const PLAYER_ANIM_IDLE   = 0;
const PLAYER_ANIM_WALK   = 12;
const PLAYER_ANIM_RUN    = 8;
const PLAYER_ANIM_ATTACK = 7;
const PLAYER_SCALE = 1.0;
const PLAYER_MODEL_Y_OFFSET = -0.95;    // character capsule center -> feet
let playerAnimT = 0;

// ---- Phase 1c smoke: material shader + cube mesh -------------------------
// Compiles a tiny ABI-compliant shader through the new material
// pipeline and draws a rotating colour-pulsed cube in front of the
// player spawn. First visible consumer of the material-system path;
// only exists to verify end-to-end compile → submit → dispatch works.

const MAT_TEST_WGSL = '#include "material_abi.wgsl"\n' +
  'struct VsOut { @builtin(position) pos: vec4<f32>, @location(0) n: vec3<f32>, @location(1) c: vec3<f32> };\n' +
  '@vertex fn vs_main(in: VertexInput) -> VsOut {\n' +
  '  var o: VsOut;\n' +
  '  o.pos = draw.mvp * vec4<f32>(in.position, 1.0);\n' +
  '  o.n = normalize((draw.model * vec4<f32>(in.normal, 0.0)).xyz);\n' +
  '  let p = 0.5 + 0.5 * sin(frame.time * 1.5);\n' +
  '  o.c = vec3<f32>(p, 0.4, 1.0 - p) * draw.model_tint.rgb;\n' +
  '  return o;\n' +
  '}\n' +
  '@fragment fn fs_main(in: VsOut) -> OpaqueOut {\n' +
  '  var out: OpaqueOut;\n' +
  '  let ndl = max(dot(normalize(in.n), normalize(vec3<f32>(0.3, 0.7, 0.4))), 0.0);\n' +
  '  let lit = in.c * (0.3 + 0.7 * ndl);\n' +
  '  out.hdr = vec4<f32>(lit, 1.0);\n' +
  '  out.material = vec2<f32>(0.0, 0.9);\n' +
  '  out.velocity = vec2<f32>(0.0, 0.0);\n' +
  '  out.albedo = vec4<f32>(in.c, 1.0);\n' +
  '  return out;\n' +
  '}\n';
const matTest = compileMaterial(MAT_TEST_WGSL);
// Minimal cube: 24 verts (one per face-corner so UVs / normals split
// cleanly) × 12 floats (pos, nrm, col, uv) = 288 floats. 6 faces × 2
// tris × 3 idx = 36 indices.
const MAT_TEST_VERTS: number[] = [
  // +X face (nrm = +1, 0, 0)
   0.5, -0.5, -0.5,  1,0,0,  1,1,1,1,  0,0,
   0.5, -0.5,  0.5,  1,0,0,  1,1,1,1,  1,0,
   0.5,  0.5,  0.5,  1,0,0,  1,1,1,1,  1,1,
   0.5,  0.5, -0.5,  1,0,0,  1,1,1,1,  0,1,
  // -X
  -0.5, -0.5,  0.5, -1,0,0,  1,1,1,1,  0,0,
  -0.5, -0.5, -0.5, -1,0,0,  1,1,1,1,  1,0,
  -0.5,  0.5, -0.5, -1,0,0,  1,1,1,1,  1,1,
  -0.5,  0.5,  0.5, -1,0,0,  1,1,1,1,  0,1,
  // +Y (top)
  -0.5,  0.5,  0.5,  0,1,0,  1,1,1,1,  0,0,
   0.5,  0.5,  0.5,  0,1,0,  1,1,1,1,  1,0,
   0.5,  0.5, -0.5,  0,1,0,  1,1,1,1,  1,1,
  -0.5,  0.5, -0.5,  0,1,0,  1,1,1,1,  0,1,
  // -Y
  -0.5, -0.5, -0.5,  0,-1,0, 1,1,1,1,  0,0,
   0.5, -0.5, -0.5,  0,-1,0, 1,1,1,1,  1,0,
   0.5, -0.5,  0.5,  0,-1,0, 1,1,1,1,  1,1,
  -0.5, -0.5,  0.5,  0,-1,0, 1,1,1,1,  0,1,
  // +Z
   0.5, -0.5,  0.5,  0,0,1,  1,1,1,1,  0,0,
  -0.5, -0.5,  0.5,  0,0,1,  1,1,1,1,  1,0,
  -0.5,  0.5,  0.5,  0,0,1,  1,1,1,1,  1,1,
   0.5,  0.5,  0.5,  0,0,1,  1,1,1,1,  0,1,
  // -Z
  -0.5, -0.5, -0.5,  0,0,-1, 1,1,1,1,  0,0,
   0.5, -0.5, -0.5,  0,0,-1, 1,1,1,1,  1,0,
   0.5,  0.5, -0.5,  0,0,-1, 1,1,1,1,  1,1,
  -0.5,  0.5, -0.5,  0,0,-1, 1,1,1,1,  0,1,
];
const MAT_TEST_INDS: number[] = [
   0, 1, 2,  0, 2, 3,
   4, 5, 6,  4, 6, 7,
   8, 9,10,  8,10,11,
  12,13,14, 12,14,15,
  16,17,18, 16,18,19,
  20,21,22, 20,22,23,
];
const matTestMesh = createMesh(MAT_TEST_VERTS, MAT_TEST_INDS);

// ---- Unvanquished aliens (5 kinds, M3 model + M5 AI + M6 pool) ------------
// Each kind has its own GLB model and stat line. Kinds and models line up
// with the Unvanquished alien classes:
//   0 = dretch   — small, fast, low HP, moderate damage
//   1 = mantis   — quick, medium HP
//   2 = marauder — medium all-round
//   3 = dragoon  — heavier, slower, hits hard
//   4 = tyrant   — boss tier; rare, big, tanky
const KIND_COUNT = 5;
const KIND_NAME  = ['DRETCH', 'MANTIS', 'MARAUDER', 'DRAGOON', 'TYRANT'];
const mdlAliens  = [
  loadModel('assets/models/enemy_dretch.glb'),
  loadModel('assets/models/enemy_mantis.glb'),
  loadModel('assets/models/enemy_marauder.glb'),
  loadModel('assets/models/enemy_dragoon.glb'),
  loadModel('assets/models/enemy_tyrant.glb'),
];
const animAliens = [
  loadModelAnimation('assets/models/enemy_dretch.glb'),
  loadModelAnimation('assets/models/enemy_mantis.glb'),
  loadModelAnimation('assets/models/enemy_marauder.glb'),
  loadModelAnimation('assets/models/enemy_dragoon.glb'),
  loadModelAnimation('assets/models/enemy_tyrant.glb'),
];
// Animation indices — IQE declaration order. Dretch (and most others):
// 0 stand, 1 attack, 4 die, 14 run, 20 walk. We map gameplay -> anim idx.
const ANIM_WALK_IDX   = [14, 14, 14, 14, 14];
const ANIM_ATTACK_IDX = [1, 1, 1, 1, 1];
// Procedural motion parameters (cheap substitute for skeletal animation).
// Each enemy has a phase accumulator — sinusoids on top give a bob + side-
// sway while walking, and a forward-lunge while attacking.
const WALK_BOB_Y = 0.12;       // metres
const WALK_BOB_RATE = 9.0;     // rad/s
const WALK_TILT = 0.06;        // unused; kept for future side-sway
const ATTACK_LUNGE_AMP = 0.25; // m forward during attack
// Per-kind tuning. Collider half-extents are generous (taller than the visual
// model) so horizontal aim at any range connects.
const KIND_SCALE = [1.6, 1.6, 1.9, 2.4, 3.0];
const KIND_HX    = [1.0, 0.9, 1.2, 1.4, 1.8];
const KIND_HY    = [1.0, 1.0, 1.2, 1.5, 2.0];
const KIND_HZ    = [1.1, 1.0, 1.3, 1.6, 2.0];
const KIND_Y_OFF = [1.0, 1.0, 1.2, 1.5, 2.0];
const KIND_SPEED = [3.0, 4.5, 3.5, 2.5, 2.2];
const KIND_HP    = [3,   4,   6,   10,  20];
const KIND_DMG   = [12,  10,  16,  22,  35];
const KIND_CD    = [0.9, 0.7, 0.9, 1.1, 1.3];
const KIND_MELEE = [2.0, 2.0, 2.3, 2.6, 3.0];
const DRETCH_HIT_FLASH = 0.18;
const WHITE = { r: 255, g: 255, b: 255, a: 255 };

// Enemy pool — each slot is permanently tied to one kind because Jolt body
// shapes can't be swapped in-place. BODIES_PER_KIND dormant bodies per kind
// give us a fixed pool of MAX_ENEMIES = KIND_COUNT * BODIES_PER_KIND.
const BODIES_PER_KIND = 2;
const MAX_ENEMIES = KIND_COUNT * BODIES_PER_KIND;
const enX = new Array<number>(MAX_ENEMIES);
const enY = new Array<number>(MAX_ENEMIES);
const enZ = new Array<number>(MAX_ENEMIES);
const enHP = new Array<number>(MAX_ENEMIES);
const enAlive = new Array<number>(MAX_ENEMIES);
const enKind  = new Array<number>(MAX_ENEMIES);
const enAttackCD = new Array<number>(MAX_ENEMIES);
const enFlashT = new Array<number>(MAX_ENEMIES);
const enPhase = new Array<number>(MAX_ENEMIES);        // walk-cycle phase accumulator
const enBody: BodyHandle[] = new Array<BodyHandle>(MAX_ENEMIES);
for (let k = 0; k < KIND_COUNT; k++) {
  const shape = boxShape(vec3(KIND_HX[k], KIND_HY[k], KIND_HZ[k]));
  for (let j = 0; j < BODIES_PER_KIND; j++) {
    const i = k * BODIES_PER_KIND + j;
    enX[i] = 0; enY[i] = -100; enZ[i] = 0;
    enHP[i] = 0; enAlive[i] = 0; enAttackCD[i] = 0; enFlashT[i] = 0;
    enPhase[i] = Math.random() * Math.PI * 2;   // stagger the bob phases
    enKind[i] = k;
    enBody[i] = createBody(physics, shape, {
      motionType: MotionType.KINEMATIC,
      position: vec3(0, -100, 0),
      objectLayer: Layer.MOVING,
    });
  }
}

// Wave director — spawners, wave plan, and kind sequence all come from the
// world file (see enemy_spawner + wave_config entities in arena_02.world.json).
const spawnerX = W.SPAWNER_X;
const spawnerZ = W.SPAWNER_Z;
const wavePlan = W.WAVE_SIZE;
const WAVE_OFFS = W.WAVE_OFFS;
const WAVE_KINDS = W.WAVE_KIND;
const WAVE_SPAWN_DELAY = 1.2;
const WAVE_BREAK_DELAY = 2.5;
const MAX_CONCURRENT = 4;

let waveIdx = 0;
let waveSpawned = 0;
let waveBreakTimer = WAVE_BREAK_DELAY;
let spawnTimer = 0;
let gameWon = false;

function countAlive(): number {
  let c = 0;
  for (let i = 0; i < MAX_ENEMIES; i++) if (enAlive[i] > 0) c = c + 1;
  return c;
}

function findDormantSlot(kind: number): number {
  for (let j = 0; j < BODIES_PER_KIND; j++) {
    const i = kind * BODIES_PER_KIND + j;
    if (enAlive[i] === 0) return i;
  }
  return -1;
}

function spawnEnemy(): void {
  const kind = WAVE_KINDS[WAVE_OFFS[waveIdx] + waveSpawned];
  const slot = findDormantSlot(kind);
  if (slot < 0) return;   // all bodies of this kind busy; retry next tick
  const sp = waveSpawned % 4;
  enX[slot] = spawnerX[sp];
  enY[slot] = 0;
  enZ[slot] = spawnerZ[sp];
  enHP[slot] = KIND_HP[kind];
  enAlive[slot] = 1;
  enAttackCD[slot] = 0;
  enFlashT[slot] = 0;
  enPhase[slot] = Math.random() * Math.PI * 2;
  setBodyPosition(enBody[slot],
    vec3(enX[slot], enY[slot] + KIND_Y_OFF[kind], enZ[slot]), true);
  waveSpawned = waveSpawned + 1;
}

// ---- Weapon + combat state (M4 / M5 / M6 / M7) ----------------------------
const PLAYER_HP_MAX = 100;
const FIRE_RANGE = 60.0;

// Weapon registry
const WEAPON_RIFLE = 0;
const WEAPON_BLASTER = 1;
const WEAPON_NAMES = ['RIFLE', 'BLASTER'];
const RIFLE_MAG = 30;
const BLASTER_MAG = 20;
const RIFLE_FIRE_CD = 0.10;   // full-auto, ~600 rpm
const BLASTER_FIRE_CD = 0.35; // tap-fire
const RIFLE_DAMAGE = 1;
const BLASTER_DAMAGE = 2;
const BLASTER_PROJ_SPEED = 40.0;
const BLASTER_PROJ_LIFE = 2.5;
const BLASTER_PROJ_GRAVITY = 9.0;   // m/s^2 — lighter than world gravity for a softer arc

let currentWeapon = WEAPON_RIFLE;
let rifleAmmo = RIFLE_MAG;
let blasterAmmo = BLASTER_MAG;
let fireCD = 0;

let playerHP = PLAYER_HP_MAX;
let gameOver = false;
const MUZZLE_FLASH_DUR = 0.08;
let muzzleFlashT = 0;
let damageFlashT = 0;
let shotsFired = 0;
let shotsHit = 0;

// ---- Projectile pool (M7) -------------------------------------------------
// Fixed-size ring buffer. Each slot stores position, velocity, and
// remaining life. pLife = 0 means the slot is free. Projectiles advance
// each frame via segment-raycast so they can't tunnel through walls.
const MAX_PROJ = 16;
const pX  = new Array<number>(MAX_PROJ);
const pY  = new Array<number>(MAX_PROJ);
const pZ  = new Array<number>(MAX_PROJ);
const pVX = new Array<number>(MAX_PROJ);
const pVY = new Array<number>(MAX_PROJ);
const pVZ = new Array<number>(MAX_PROJ);
const pLife = new Array<number>(MAX_PROJ);
for (let i = 0; i < MAX_PROJ; i++) pLife[i] = 0;
let projNext = 0;

function spawnProjectile(x: number, y: number, z: number,
                         vx: number, vy: number, vz: number): void {
  pX[projNext] = x; pY[projNext] = y; pZ[projNext] = z;
  pVX[projNext] = vx; pVY[projNext] = vy; pVZ[projNext] = vz;
  pLife[projNext] = BLASTER_PROJ_LIFE;
  projNext = (projNext + 1) % MAX_PROJ;
}

// ---- Ammo pickups (M7) ----------------------------------------------------
// Fixed positions around the arena. Walk within PICKUP_RADIUS to collect;
// respawn after PICKUP_RESPAWN seconds so long runs don't starve for ammo.
const PICKUP_RIFLE = 0;
const PICKUP_BLASTER = 1;
const PICKUP_RIFLE_AMT = 15;
const PICKUP_BLASTER_AMT = 8;
const PICKUP_RADIUS = 1.4;
const PICKUP_RESPAWN = 18.0;
const pickupKind = W.PICKUP_KIND;      // 0 = rifle, 1 = blaster (see build-world.ts)
const pickupX    = W.PICKUP_X;
const pickupZ    = W.PICKUP_Z;
const PICKUP_COUNT = W.PICKUP_COUNT;
const pickupActive   = new Array<number>(PICKUP_COUNT);
const pickupRespawnT = new Array<number>(PICKUP_COUNT);
for (let i = 0; i < PICKUP_COUNT; i++) { pickupActive[i] = 1; pickupRespawnT[i] = 0; }

function despawnAllEnemies(): void {
  for (let i = 0; i < MAX_ENEMIES; i++) {
    enAlive[i] = 0;
    enHP[i] = 0;
    enAttackCD[i] = 0;
    enFlashT[i] = 0;
    enPhase[i] = Math.random() * Math.PI * 2;
    enX[i] = 0; enY[i] = -100; enZ[i] = 0;
    setBodyPosition(enBody[i], vec3(0, -100, 0), false);
  }
}

function resetRun(): void {
  currentWeapon = WEAPON_RIFLE;
  rifleAmmo = RIFLE_MAG;
  blasterAmmo = BLASTER_MAG;
  fireCD = 0;
  playerHP = PLAYER_HP_MAX;
  gameOver = false;
  gameWon = false;
  muzzleFlashT = 0;
  damageFlashT = 0;
  shotsFired = 0;
  shotsHit = 0;
  waveIdx = 0;
  waveSpawned = 0;
  waveBreakTimer = WAVE_BREAK_DELAY;
  spawnTimer = 0;
  for (let i = 0; i < MAX_PROJ; i++) pLife[i] = 0;
  for (let i = 0; i < PICKUP_COUNT; i++) { pickupActive[i] = 1; pickupRespawnT[i] = 0; }
  despawnAllEnemies();
}

// Impact sparks — fixed ring buffer to avoid array growth in the hot loop.
const SPARK_MAX = 16;
const sparkX  = new Array<number>(SPARK_MAX);
const sparkY  = new Array<number>(SPARK_MAX);
const sparkZ  = new Array<number>(SPARK_MAX);
const sparkT  = new Array<number>(SPARK_MAX);   // seconds of life remaining; 0 = slot free
for (let i = 0; i < SPARK_MAX; i++) sparkT[i] = 0;
let sparkNext = 0;

function spawnSpark(p: Vec3): void {
  sparkX[sparkNext] = p.x;
  sparkY[sparkNext] = p.y;
  sparkZ[sparkNext] = p.z;
  sparkT[sparkNext] = 0.35;
  sparkNext = (sparkNext + 1) % SPARK_MAX;
}

let cursorLocked = true;
let screenshotSeq = 0;
disableCursor();

// ---- M8 polish: post-FX ---------------------------------------------------
// Called once at startup — these are cheap, always-on stylistic passes.
setVignette(0.4, 0.55);    // darken frame edges
setFilmGrain(0.06);        // very subtle noise


// ---- Self-test harness ----------------------------------------------------
// When SELFTEST is true the game auto-fires a shot on frame 30, screenshots
// the scene on frame 60, and exits on frame 90. Used while investigating the
// engine's deferred-render green-screen bug — kept dormant for future debug.
const SELFTEST = false;
let testFrame = 0;


while (!windowShouldClose()) {
  beginDrawing();
  const dt = getDeltaTime();
  const sw = getScreenWidth();
  const sh = getScreenHeight();
  updateMusicStream(musicAmbient);

  // Tab toggles cursor capture so you can free the mouse to screenshot etc.
  if (isKeyPressed(Key.TAB)) {
    cursorLocked = !cursorLocked;
    if (cursorLocked) disableCursor();
    else enableCursor();
  }
  // F12 takes a screenshot (sequential filenames)
  if (isKeyPressed(Key.F12)) {
    screenshotSeq = screenshotSeq + 1;
    takeScreenshot('shooter_' + screenshotSeq + '.png');
  }

  const input = readInput();
  testFrame = testFrame + 1;
  // Selftest: drive the player forward so screenshots can verify
  // walk direction. Runs before the player controller update so
  // the override actually reaches updatePlayerController.
  if (SELFTEST && testFrame >= 20) input.moveZ = -1;
  // Only apply mouse look when cursor is captured — avoids jumpy yaw/pitch
  // when the user is moving the mouse outside the window. The first ~10
  // frames after window creation often report giant mouse deltas (system
  // cursor settling into the captured state), which can fling the camera
  // to a useless angle before the player even sees the scene.
  if (cursorLocked && testFrame > 10) {
    CAM[0] = CAM[0] + input.lookX;
    const np = CAM[1] + input.lookY;
    CAM[1] = np < TP_PITCH_MIN ? TP_PITCH_MIN : (np > TP_PITCH_MAX ? TP_PITCH_MAX : np);
  }

  // Restart on R when the run has ended (died or won); otherwise R reloads
  // the currently-equipped weapon.
  if (isKeyPressed(Key.R)) {
    if (gameOver || gameWon) resetRun();
    else if (currentWeapon === WEAPON_RIFLE) rifleAmmo = RIFLE_MAG;
    else blasterAmmo = BLASTER_MAG;
  }
  // Weapon switching with 1/2.
  if (isKeyPressed(Key.ONE))  { currentWeapon = WEAPON_RIFLE;   fireCD = 0; }
  if (isKeyPressed(Key.TWO))  { currentWeapon = WEAPON_BLASTER; fireCD = 0; }

  // Freeze player movement while dead or after victory; physics still steps.
  if (!gameOver && !gameWon) {
    const yawNow = CAM[0];
    const fwd = vec3(Math.sin(yawNow), 0, -Math.cos(yawNow));
    const rgt = vec3(Math.cos(yawNow), 0, Math.sin(yawNow));
    updatePlayerController(dt, input.moveX, input.moveZ, fwd, rgt, input.jump);
  }
  stepPhysics(physics, dt);
  // Smooth orbit camera follow after physics step.
  // Inline orbit-camera follow.
  {
    const pp0 = playerPosition();
    const ya = CAM[0], pi = CAM[1];
    const cpi = Math.cos(pi), spi = Math.sin(pi);
    const fX = pp0.x;
    const fY = pp0.y + TP_EYE_HEIGHT;
    const fZ = pp0.z;
    const wX = fX - Math.sin(ya) * cpi * TP_ORBIT_DIST;
    const wY = fY + spi * TP_ORBIT_DIST;
    const wZ = fZ + Math.cos(ya) * cpi * TP_ORBIT_DIST;
    if (CAM[8] === 0) {
      CAM[2] = wX; CAM[3] = wY; CAM[4] = wZ;
      CAM[5] = fX; CAM[6] = fY; CAM[7] = fZ;
      CAM[8] = 1;
    } else {
      const t = 1 - Math.exp(-TP_SMOOTH * dt);
      CAM[2] = CAM[2] + (wX - CAM[2]) * t;
      CAM[3] = CAM[3] + (wY - CAM[3]) * t;
      CAM[4] = CAM[4] + (wZ - CAM[4]) * t;
      CAM[5] = CAM[5] + (fX - CAM[5]) * t;
      CAM[6] = CAM[6] + (fY - CAM[6]) * t;
      CAM[7] = CAM[7] + (fZ - CAM[7]) * t;
    }
  }
  playerAnimT = playerAnimT + dt;

  // ---- Enemy AI + wave director (M5 / M6) -------------------------------
  if (!gameOver && !gameWon) {
    const pp = playerPosition();
    for (let i = 0; i < MAX_ENEMIES; i++) {
      if (enAlive[i] === 0) continue;
      const k = enKind[i];
      const dx = pp.x - enX[i];
      const dz = pp.z - enZ[i];
      const dist = Math.sqrt(dx * dx + dz * dz);
      if (dist > KIND_MELEE[k]) {
        const step = KIND_SPEED[k] * dt;
        const move = step < dist ? step : dist;
        enX[i] = enX[i] + (dx / dist) * move;
        enZ[i] = enZ[i] + (dz / dist) * move;
        setBodyPosition(enBody[i],
          vec3(enX[i], enY[i] + KIND_Y_OFF[k], enZ[i]), true);
      } else if (enAttackCD[i] <= 0) {
        playerHP = playerHP - KIND_DMG[k];
        damageFlashT = 0.5;
        enAttackCD[i] = KIND_CD[k];
        playSound(sfxAttack);
        if (playerHP <= 0) { playerHP = 0; gameOver = true; }
      }
      if (enAttackCD[i] > 0) enAttackCD[i] = enAttackCD[i] - dt;
      if (enFlashT[i]   > 0) enFlashT[i]   = enFlashT[i]   - dt;
      enPhase[i] = enPhase[i] + dt;   // seconds into current animation
    }

    // Pickups — proximity collect, respawn after delay.
    for (let i = 0; i < PICKUP_COUNT; i++) {
      if (pickupActive[i] === 0) {
        pickupRespawnT[i] = pickupRespawnT[i] - dt;
        if (pickupRespawnT[i] <= 0) pickupActive[i] = 1;
        continue;
      }
      const pdx = pp.x - pickupX[i];
      const pdz = pp.z - pickupZ[i];
      if (pdx * pdx + pdz * pdz < PICKUP_RADIUS * PICKUP_RADIUS) {
        if (pickupKind[i] === PICKUP_RIFLE) {
          rifleAmmo = Math.min(RIFLE_MAG, rifleAmmo + PICKUP_RIFLE_AMT);
        } else {
          blasterAmmo = Math.min(BLASTER_MAG, blasterAmmo + PICKUP_BLASTER_AMT);
        }
        pickupActive[i] = 0;
        pickupRespawnT[i] = PICKUP_RESPAWN;
        playSound(sfxPickup);
      }
    }

    // Wave director
    const alive = countAlive();
    if (waveIdx < wavePlan.length) {
      if (waveBreakTimer > 0) {
        waveBreakTimer = waveBreakTimer - dt;
      } else {
        const waveSize = wavePlan[waveIdx];
        if (waveSpawned < waveSize && alive < MAX_CONCURRENT) {
          spawnTimer = spawnTimer - dt;
          if (spawnTimer <= 0) {
            spawnEnemy();
            spawnTimer = WAVE_SPAWN_DELAY;
          }
        }
        if (waveSpawned >= waveSize && alive === 0) {
          waveIdx = waveIdx + 1;
          waveSpawned = 0;
          waveBreakTimer = WAVE_BREAK_DELAY;
          if (waveIdx >= wavePlan.length) gameWon = true;
        }
      }
    }
  }

  // testFrame is incremented above the input block so the mouse-settle
  // grace period uses the same counter.
  let forceFire = false;
  if (SELFTEST) {
    waveBreakTimer = 9999;
    if (testFrame < 5) { CAM[0] = 0; CAM[1] = 0.35; CAM[8] = 0; }
    if (testFrame === 5) {
      // Manually spawn ONE dretch off to the side, stays idle.
      enX[0] = -6; enY[0] = 0; enZ[0] = -6;
      enHP[0] = 3; enAlive[0] = 1; enAttackCD[0] = 999;
      setBodyPosition(enBody[0], vec3(-6, KIND_Y_OFF[0], -6), true);
    }
    if (testFrame === 30)  { screenshotSeq++; takeScreenshot('shooter_selftest_' + screenshotSeq + '_t0_5s.png'); }
    if (testFrame === 180) { screenshotSeq++; takeScreenshot('shooter_selftest_' + screenshotSeq + '_t3_0s.png'); break; }
  }

  // ---- Fire (M4 / M7) ---------------------------------------------------
  if (fireCD > 0) fireCD = fireCD - dt;
  const combatActive = !gameOver && !gameWon && cursorLocked;
  const isRifle    = currentWeapon === WEAPON_RIFLE;
  const haveAmmo   = isRifle ? rifleAmmo > 0 : blasterAmmo > 0;
  // Rifle = full-auto (mouse held); blaster = tap (press edge only).
  const fireIntent = combatActive && haveAmmo && fireCD <= 0 &&
                     (isRifle ? input.fireDown : input.firePressed);
  if (fireIntent || (forceFire && haveAmmo && combatActive)) {
    shotsFired = shotsFired + 1;
    muzzleFlashT = MUZZLE_FLASH_DUR;
    playSound(sfxFire);
    // Third-person aiming: the crosshair is at screen centre, so
    // trace the camera-forward line out to a far point, treat that
    // as the aim target, and fire from the player's shoulder toward
    // it. This way visible tracers / sparks line up with the gun
    // barrel in the world, not with the orbit-camera position. The
    // parallax between camera ray and muzzle ray is tiny at normal
    // engagement ranges and is what gives the shot its "from the
    // player" feel.
    const camOriginV = vec3(CAM[2], CAM[3], CAM[4]);
    const adx = CAM[5] - CAM[2], ady = CAM[6] - CAM[3], adz = CAM[7] - CAM[4];
    const alen = Math.sqrt(adx*adx + ady*ady + adz*adz);
    const camFwd = alen > 0 ? vec3(adx/alen, ady/alen, adz/alen) : vec3(0, 0, -1);
    const aimTargetFar = 200;
    const tgtX = camOriginV.x + camFwd.x * aimTargetFar;
    const tgtY = camOriginV.y + camFwd.y * aimTargetFar;
    const tgtZ = camOriginV.z + camFwd.z * aimTargetFar;
    // Muzzle = player shoulder offset (matches the drawn weapon).
    const ppF = playerPosition();
    const sy = Math.sin(CAM[0]), cy = Math.cos(CAM[0]);
    const originX = ppF.x + cy * 0.30 + sy * 0.60;
    const originY = ppF.y + 0.95;
    const originZ = ppF.z + sy * 0.30 + (-cy) * 0.60;
    const mdx = tgtX - originX, mdy = tgtY - originY, mdz = tgtZ - originZ;
    const mlen = Math.sqrt(mdx*mdx + mdy*mdy + mdz*mdz);
    const aim = mlen > 0 ? vec3(mdx/mlen, mdy/mlen, mdz/mlen) : camFwd;

    if (isRifle) {
      rifleAmmo = rifleAmmo - 1;
      fireCD = RIFLE_FIRE_CD;
      const hit = raycast(physics, vec3(originX, originY, originZ), aim,
                          FIRE_RANGE, ALL_LAYERS_MASK);
      if (hit) {
        shotsHit = shotsHit + 1;
        spawnSpark(hit.point);
        for (let i = 0; i < MAX_ENEMIES; i++) {
          if (enAlive[i] > 0 && hit.body === enBody[i]) {
            enHP[i] = enHP[i] - RIFLE_DAMAGE;
            enFlashT[i] = DRETCH_HIT_FLASH;
            if (enHP[i] <= 0) {
              enAlive[i] = 0;
              enY[i] = -100;
              setBodyPosition(enBody[i], vec3(enX[i], -100, enZ[i]), false);
              playSound(sfxAttack);   // reuse clank as death thud
            }
            break;
          }
        }
      }
    } else {
      blasterAmmo = blasterAmmo - 1;
      fireCD = BLASTER_FIRE_CD;
      spawnProjectile(originX, originY, originZ,
                      aim.x * BLASTER_PROJ_SPEED,
                      aim.y * BLASTER_PROJ_SPEED,
                      aim.z * BLASTER_PROJ_SPEED);
    }
  }

  // ---- Projectile update (M7) -------------------------------------------
  // Apply gravity, then segment-raycast from old pos to new pos so fast or
  // arcing shots can't tunnel through walls or enemy colliders.
  for (let i = 0; i < MAX_PROJ; i++) {
    if (pLife[i] <= 0) continue;
    pVY[i] = pVY[i] - BLASTER_PROJ_GRAVITY * dt;
    const ox = pX[i], oy = pY[i], oz = pZ[i];
    const nx = ox + pVX[i] * dt;
    const ny = oy + pVY[i] * dt;
    const nz = oz + pVZ[i] * dt;
    const sx = nx - ox, sy = ny - oy, sz = nz - oz;
    const segLen = Math.sqrt(sx * sx + sy * sy + sz * sz);
    const inv = segLen > 0 ? 1 / segLen : 0;
    const hit = raycast(physics, vec3(ox, oy, oz),
                        vec3(sx * inv, sy * inv, sz * inv),
                        segLen, ALL_LAYERS_MASK);
    if (hit) {
      spawnSpark(hit.point);
      for (let j = 0; j < MAX_ENEMIES; j++) {
        if (enAlive[j] > 0 && hit.body === enBody[j]) {
          enHP[j] = enHP[j] - BLASTER_DAMAGE;
          enFlashT[j] = DRETCH_HIT_FLASH;
          shotsHit = shotsHit + 1;
          if (enHP[j] <= 0) {
            enAlive[j] = 0;
            enY[j] = -100;
            setBodyPosition(enBody[j], vec3(enX[j], -100, enZ[j]), false);
            playSound(sfxAttack);
          }
          break;
        }
      }
      pLife[i] = 0;
    } else {
      pX[i] = nx; pY[i] = ny; pZ[i] = nz;
      pLife[i] = pLife[i] - dt;
    }
  }
  if (muzzleFlashT > 0) muzzleFlashT = muzzleFlashT - dt;
  if (damageFlashT > 0) damageFlashT = damageFlashT - dt;
  for (let i = 0; i < SPARK_MAX; i++) {
    if (sparkT[i] > 0) sparkT[i] = sparkT[i] - dt;
  }

  clearBackground({ r: Math.floor(W.ENV_SKY_R * 255),
                    g: Math.floor(W.ENV_SKY_G * 255),
                    b: Math.floor(W.ENV_SKY_B * 255), a: 255 });
  setAmbientLight({ r: 120, g: 130, b: 160, a: 255 }, 0.35);
  setDirectionalLight(vec3(-0.3, -0.9, -0.2), { r: 255, g: 245, b: 220, a: 255 }, 0.9);

  beginMode3D({
    position: vec3(CAM[2], CAM[3], CAM[4]),
    target:   vec3(CAM[5], CAM[6], CAM[7]),
    up: vec3(0, 1, 0),
    fovy: TP_FOVY,
    projection: 0,
  });

  // Muzzle flare point light — sits just past the barrel tip so
  // the warm splash of light hits the gun body and the floor in
  // front of the player when firing.
  if (muzzleFlashT > 0) {
    const pp = playerPosition();
    const sy = Math.sin(CAM[0]), cy = Math.cos(CAM[0]);
    const tipOffset = currentWeapon === WEAPON_RIFLE ? 0.78 : 0.43;
    const mx = pp.x + cy * 0.30 + sy * tipOffset;
    const my = pp.y + 0.95;
    const mz = pp.z + sy * 0.30 + (-cy) * tipOffset;
    const k = muzzleFlashT / MUZZLE_FLASH_DUR;
    addPointLight(mx, my, mz, 6, 1.0, 0.85, 0.5, 4.0 * k);
  }

  // ---- World: static meshes + water + lights (all from generated/world.ts) -
  // Ground plate — big drawCube beneath the terrain mesh so the full
  // 80×80 collider floor reads as a solid plane even where the hills
  // haven't lifted anything off it. Matches COLLIDER[0] (the plaza floor).
  drawCube(vec3(W.COLLIDER_X[0], W.COLLIDER_Y[0], W.COLLIDER_Z[0]),
           W.COLLIDER_HALF_X[0] * 2, W.COLLIDER_HALF_Y[0] * 2, W.COLLIDER_HALF_Z[0] * 2,
           { r: 85, g: 95, b: 75, a: 255 });

  // Phase 1c smoke test — colour-pulsed cube in front of spawn,
  // rendered via the new material pipeline. Proves the compile →
  // submit → dispatch path works on a real frame.
  if (matTest > 0) {
    drawMeshWithMaterial(matTest, matTestMesh,
      vec3(0, 3, 15), 3.0, { r: 255, g: 255, b: 255, a: 255 });
  } else {
    drawText('material compile failed (handle=0)', 20, 100, 20,
             { r: 255, g: 80, b: 80, a: 255 });
  }
  // Static meshes — either drawModel for real GLBs, or coloured drawCube
  // for placeholder _gizmo_box.glb entries. MESH_CATEGORY drives the cube
  // tint (0 generic / 1 building / 2 terrain / 3 prop).
  for (let i = 0; i < W.MESH_COUNT; i++) {
    const mi = W.MESH_MODEL_IDX[i];
    if (W.MODEL_IS_BOX[mi] === 1) {
      const c = W.MESH_CATEGORY[i];
      const col = { r: MESH_TINT_R[c], g: MESH_TINT_G[c], b: MESH_TINT_B[c], a: 255 };
      drawCube(vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
               W.MESH_COLLIDER_HX[i] * 2, W.MESH_COLLIDER_HY[i] * 2, W.MESH_COLLIDER_HZ[i] * 2,
               col);
    } else {
      drawModel(meshModelHandles[mi],
                vec3(W.MESH_X[i], W.MESH_Y[i], W.MESH_Z[i]),
                W.MESH_SCALE[i], WHITE);
    }
  }
  // Water — tessellate each segment into a grid of small flat tiles
  // whose Y sits on a travelling wave. Colour blends deep-indigo trough
  // → pale cyan crest on a smooth height term. A second high-frequency
  // ripple crosses the surface. Flow is encoded as a wave phase that
  // advances in +X with time, so crests visibly travel downstream.
  // Tiles overlap their neighbours (×1.08) so the grid edges disappear
  // into the blend.
  //
  // ≈ 0.35 m tiles × 6 segments ≈ 1800 cubes/frame. Free at our
  // draw-call budget; no engine shader work required.
  {
    const tNow = getTime();
    const TILE = 0.35;
    const baseA = 205;
    const foamA = 200;
    for (let i = 0; i < W.WATER_COUNT; i++) {
      const cx = W.WATER_CX[i], cy = W.WATER_CY[i], cz = W.WATER_CZ[i];
      const sx = W.WATER_SX[i], sz = W.WATER_SZ[i];
      const amp = W.WATER_WAVE_AMP[i];
      const spd = W.WATER_WAVE_SPD[i];
      const nx = Math.max(1, Math.floor(sx / TILE));
      const nz = Math.max(1, Math.floor(sz / TILE));
      const stepX = sx / nx;
      const stepZ = sz / nz;
      // Downstream wave — long wavelength so adjacent tiles share close
      // heights and the grid reads as a continuous wave, not a checker.
      const kx = 0.45;
      const kz = 0.75;
      for (let ix = 0; ix < nx; ix++) {
        for (let iz = 0; iz < nz; iz++) {
          const x = cx - sx * 0.5 + stepX * (ix + 0.5);
          const z = cz - sz * 0.5 + stepZ * (iz + 0.5);
          const w1 = Math.sin(x * kx + tNow * spd * 1.6);
          const w2 = Math.sin(z * kz + x * 0.18 + tNow * spd * 2.1);
          const w3 = Math.sin(x * 2.1 + z * 1.7 + tNow * spd * 3.5) * 0.25;
          const waveN = (w1 + w2 + w3 * 4) * 0.25; // -1..~1
          const h01 = (waveN + 1) * 0.5;                 // 0..1
          const dy = waveN * amp;
          // Deep-water blue at troughs, pale cyan at crests.
          const r = Math.floor(18 + h01 * 55);
          const g = Math.floor(75 + h01 * 105);
          const b = Math.floor(125 + h01 * 85);
          drawCube(vec3(x, cy + dy, z),
                   stepX * 1.08, 0.03, stepZ * 1.08,
                   { r: r, g: g, b: b, a: baseA });
          // Foam: smooth falloff from h01=0.75 upward; no hard threshold.
          if (h01 > 0.75) {
            const fh = (h01 - 0.75) / 0.25;
            drawCube(vec3(x, cy + dy + 0.025, z),
                     stepX * 0.85, 0.015, stepZ * 0.85,
                     { r: 230, g: 240, b: 250,
                       a: Math.floor(foamA * fh * fh) });
          }
        }
      }
    }
  }
  // Point lights from the world file — static scene lights.
  for (let i = 0; i < W.LIGHT_COUNT; i++) {
    addPointLight(W.LIGHT_X[i], W.LIGHT_Y[i], W.LIGHT_Z[i],
                  W.LIGHT_RANGE[i],
                  W.LIGHT_R[i], W.LIGHT_G[i], W.LIGHT_B[i],
                  W.LIGHT_INT[i]);
  }

  // Player: skinned + animated. Face the camera's horizontal yaw (so the
  // character always looks "away from the camera"). Walk if input is
  // nonzero, idle otherwise. A debug sphere at the capsule centre is
  // always drawn as a fallback so the player's position is visible even
  // if the skinned model fails to render.
  {
    const pp = playerPosition();
    const moving = input.moveX !== 0 || input.moveZ !== 0;
    const camYaw = CAM[0];
    // Player_bsuit's rest pose faces +X in model space (Unvanquished
    // convention, preserved through our X90 Z-up→Y-up root fix).
    // Camera-yaw forward at yaw=0 is -Z, so rotate the model by
    // +π/2 about Y to line the character's front with the camera
    // direction. The bsuit's only "attack" animation is a melee
    // swing — a ranged shooter shouldn't use it; keep the walk/idle
    // pose and fake recoil + muzzle flash on the weapon itself.
    const modelYaw = camYaw + Math.PI / 2;
    const fsin = Math.sin(modelYaw);
    const fcos = -Math.cos(modelYaw);
    const panim = moving ? PLAYER_ANIM_WALK : PLAYER_ANIM_IDLE;
    updateModelAnimation(animPlayer, panim, playerAnimT, PLAYER_SCALE,
      pp.x, pp.y + PLAYER_MODEL_Y_OFFSET, pp.z, fsin, fcos);
    drawModel(mdlPlayer, vec3(pp.x, pp.y + PLAYER_MODEL_Y_OFFSET, pp.z),
              PLAYER_SCALE, WHITE);

    // Held weapon — sketched from cubes since we don't yet have a
    // converted tpweapon GLB. Rifle is a long grey body + thin
    // barrel; blaster is a short stubby pistol. Positioned at the
    // character's right shoulder. On fire the weapon recoils
    // backward for one MUZZLE_FLASH_DUR tick (≈0.08s) and a warm
    // flash sprite appears at the barrel tip — the exponential
    // falloff on recoilT reads as a snap-back rather than a slide.
    const shy = Math.sin(camYaw), chy = Math.cos(camYaw);
    const fx = shy;         // camera forward (horizontal) at this yaw
    const fz = -chy;
    const rx = chy;         // camera right
    const rz = shy;
    const recoilT = muzzleFlashT > 0 ? muzzleFlashT / MUZZLE_FLASH_DUR : 0;
    const recoilK = recoilT * recoilT;        // snappier than linear
    const recoilBack = recoilK * 0.18;        // metres pulled toward shooter
    const shoulder = vec3(
      pp.x + rx * 0.30 + fx * (0.15 - recoilBack),
      pp.y + 0.95,
      pp.z + rz * 0.30 + fz * (0.15 - recoilBack),
    );
    const bodyDark = { r: 55, g: 55, b: 60, a: 255 };
    const bodyMid  = { r: 90, g: 90, b: 100, a: 255 };
    let muzzleX = shoulder.x, muzzleY = shoulder.y, muzzleZ = shoulder.z;
    if (currentWeapon === WEAPON_RIFLE) {
      drawCube(shoulder, 0.12, 0.10, 0.55, bodyMid);
      const barrelLen = 0.45;
      const barrelX = shoulder.x + fx * barrelLen;
      const barrelY = shoulder.y;
      const barrelZ = shoulder.z + fz * barrelLen;
      drawCube(vec3(barrelX, barrelY, barrelZ), 0.06, 0.06, 0.35, bodyDark);
      muzzleX = shoulder.x + fx * (barrelLen + 0.18);
      muzzleY = shoulder.y;
      muzzleZ = shoulder.z + fz * (barrelLen + 0.18);
    } else {
      drawCube(shoulder, 0.10, 0.14, 0.22, bodyMid);
      const bx = shoulder.x + fx * 0.18;
      const bz = shoulder.z + fz * 0.18;
      drawCube(vec3(bx, shoulder.y + 0.02, bz), 0.05, 0.05, 0.15, bodyDark);
      muzzleX = shoulder.x + fx * 0.28;
      muzzleY = shoulder.y + 0.02;
      muzzleZ = shoulder.z + fz * 0.28;
    }

    // Muzzle flash — bright yellow core + wider orange halo that
    // fades with muzzleFlashT. Two overlapping spheres read as a
    // burst of flame even at small pixel sizes.
    if (muzzleFlashT > 0) {
      const k = muzzleFlashT / MUZZLE_FLASH_DUR;
      const coreA = Math.min(255, Math.floor(k * 255));
      const haloA = Math.min(200, Math.floor(k * 170));
      const coreR = 0.10 + (1 - k) * 0.04;       // quick puff-out
      const haloR = 0.22 + (1 - k) * 0.10;
      drawSphere(vec3(muzzleX, muzzleY, muzzleZ), haloR,
        { r: 255, g: 130, b:  40, a: haloA });
      drawSphere(vec3(muzzleX, muzzleY, muzzleZ), coreR,
        { r: 255, g: 240, b: 170, a: coreA });
    }
  }
  // Per-enemy: drive the skinned skeleton via updateModelAnimation (picks
  // attack vs walk anim), then drawModel renders with the pose from the
  // joint matrices set by the update. Both calls use the same position so
  // non-skinned fallbacks still sit in the right place.
  const ppAim = playerPosition();
  for (let i = 0; i < MAX_ENEMIES; i++) {
    if (enAlive[i] === 0) continue;
    const k = enKind[i];
    const dxA = ppAim.x - enX[i];
    const dzA = ppAim.z - enZ[i];
    const distA = Math.sqrt(dxA * dxA + dzA * dzA);
    const faceSin = distA > 0.001 ? dxA / distA : 0;
    const faceCos = distA > 0.001 ? -dzA / distA : -1;
    const attacking = distA <= KIND_MELEE[k];
    const animIdx = attacking ? ANIM_ATTACK_IDX[k] : ANIM_WALK_IDX[k];
    updateModelAnimation(animAliens[k], animIdx, enPhase[i], KIND_SCALE[k],
      enX[i], enY[i], enZ[i], faceSin, faceCos);
    const f = enFlashT[i] > 0 ? enFlashT[i] / DRETCH_HIT_FLASH : 0;
    const tint = f > 0
      ? { r: 255,
          g: Math.floor(255 * (1 - f)),
          b: Math.floor(255 * (1 - f)),
          a: 255 }
      : WHITE;
    drawModel(mdlAliens[k], vec3(enX[i], enY[i], enZ[i]), KIND_SCALE[k], tint);
  }
  // Pickups — bobbing cubes, color-coded per kind.
  const tNow = getTime();
  for (let i = 0; i < PICKUP_COUNT; i++) {
    if (pickupActive[i] === 0) continue;
    const bob = 0.8 + Math.sin(tNow * 3.0 + i) * 0.15;
    const isRifleKind = pickupKind[i] === PICKUP_RIFLE;
    const col = isRifleKind
      ? { r: 240, g: 200, b: 80,  a: 255 }    // gold = rifle
      : { r: 120, g: 220, b: 240, a: 255 };   // cyan = blaster
    drawCube(vec3(pickupX[i], bob, pickupZ[i]), 0.4, 0.4, 0.4, col);
    // Glow sphere around the cube for visibility.
    drawSphere(vec3(pickupX[i], bob, pickupZ[i]), 0.55,
      { r: col.r, g: col.g, b: col.b, a: 60 });
  }
  // Impact sparks — small yellow puffs that fade over 0.35s.
  for (let i = 0; i < SPARK_MAX; i++) {
    if (sparkT[i] > 0) {
      const t = sparkT[i] / 0.35;
      const a = Math.min(255, Math.floor(t * 255));
      drawSphere(vec3(sparkX[i], sparkY[i], sparkZ[i]), 0.25 * t + 0.05,
        { r: 255, g: 240, b: 140, a });
    }
  }
  // Blaster projectiles — glowing cyan spheres.
  for (let i = 0; i < MAX_PROJ; i++) {
    if (pLife[i] > 0) {
      drawSphere(vec3(pX[i], pY[i], pZ[i]), 0.16,
        { r: 140, g: 220, b: 255, a: 255 });
    }
  }
  endMode3D();

  // Crosshair — brighten while firing
  const crossA = muzzleFlashT > 0 ? 240 : 160;
  drawCircle(sw / 2, sh / 2, 3, { r: 255, g: 255, b: 255, a: crossA });
  // Muzzle flash — small warm smudge near the crosshair, not full-screen.
  if (muzzleFlashT > 0) {
    const fa = Math.floor((muzzleFlashT / MUZZLE_FLASH_DUR) * 180);
    drawCircle(sw / 2, sh / 2 + 4, 14, { r: 255, g: 220, b: 120, a: fa });
  }

  // Damage vignette — red screen edges when the player takes a hit.
  if (damageFlashT > 0) {
    const fa = Math.floor((damageFlashT / 0.5) * 120);
    drawRect(0, 0, sw, 60, { r: 200, g: 20, b: 20, a: fa });
    drawRect(0, sh - 60, sw, 60, { r: 200, g: 20, b: 20, a: fa });
    drawRect(0, 0, 60, sh, { r: 200, g: 20, b: 20, a: fa });
    drawRect(sw - 60, 0, 60, sh, { r: 200, g: 20, b: 20, a: fa });
  }

  // Player HP bar — bottom-left.
  const phpW = 220;
  const phpFill = Math.max(0, Math.floor(phpW * (playerHP / PLAYER_HP_MAX)));
  drawRect(10, sh - 68, phpW, 18, { r: 30, g: 10, b: 10, a: 180 });
  drawRect(10, sh - 68, phpFill, 18, { r: 180, g: 60, b: 50, a: 230 });
  drawText('HP ' + playerHP, 18, sh - 65, 14, { r: 240, g: 240, b: 240, a: 255 });

  // Weapon + ammo — bottom-right.
  const isRifleHud = currentWeapon === WEAPON_RIFLE;
  const curAmmo = isRifleHud ? rifleAmmo : blasterAmmo;
  const curMag  = isRifleHud ? RIFLE_MAG : BLASTER_MAG;
  const wtxt = WEAPON_NAMES[currentWeapon] + '  ' + curAmmo + ' / ' + curMag;
  drawRect(sw - 260, sh - 68, 250, 18, { r: 0, g: 0, b: 0, a: 150 });
  drawText(wtxt + '   [1/2 switch  R reload]',
           sw - 252, sh - 65, 13, { r: 240, g: 230, b: 180, a: 255 });

  // Wave HUD — top-center. Shows "WAVE X — enemies K/N" while spawning,
  // or a "NEXT WAVE IN ..." countdown between waves.
  const aliveNow = countAlive();
  if (!gameOver && !gameWon) {
    if (waveBreakTimer > 0 && waveIdx < wavePlan.length) {
      const label = 'WAVE ' + (waveIdx + 1) + ' IN ' + waveBreakTimer.toFixed(1) + 's';
      const lw = measureText(label, 22);
      drawText(label, (sw - lw) / 2, 18, 22, { r: 230, g: 220, b: 160, a: 230 });
    } else if (waveIdx < wavePlan.length) {
      const waveSize = wavePlan[waveIdx];
      const remaining = (waveSize - waveSpawned) + aliveNow;
      const label = 'WAVE ' + (waveIdx + 1) + ' — ' + remaining + ' / ' + waveSize;
      const lw = measureText(label, 20);
      drawText(label, (sw - lw) / 2, 18, 20, { r: 230, g: 220, b: 160, a: 230 });
    }
  }

  // Game over overlay.
  if (gameOver) {
    drawRect(0, 0, sw, sh, { r: 0, g: 0, b: 0, a: 170 });
    const msg = 'YOU DIED';
    const mw = measureText(msg, 56);
    drawText(msg, (sw - mw) / 2, sh * 0.35, 56, { r: 220, g: 60, b: 50, a: 255 });
    const sub = 'Reached wave ' + (waveIdx + 1) + ' — press R to restart';
    const sww = measureText(sub, 22);
    drawText(sub, (sw - sww) / 2, sh * 0.35 + 72, 22, { r: 220, g: 220, b: 220, a: 230 });
  }

  // Victory overlay.
  if (gameWon) {
    drawRect(0, 0, sw, sh, { r: 0, g: 0, b: 0, a: 170 });
    const msg = 'ARENA CLEARED';
    const mw = measureText(msg, 52);
    drawText(msg, (sw - mw) / 2, sh * 0.33, 52, { r: 180, g: 230, b: 180, a: 255 });
    const sub = 'Survived all ' + wavePlan.length + ' waves — press R to play again';
    const sww = measureText(sub, 22);
    drawText(sub, (sw - sww) / 2, sh * 0.33 + 70, 22, { r: 220, g: 220, b: 220, a: 230 });
  }

  // Diagnostic HUD — helps verify input is reaching the game
  const pp = playerPosition();
  const diag1 = 'FPS ' + Math.floor(getFPS())
    + '  world: ' + worldStatus
    + '  WASD:' + input.moveX.toFixed(1) + ',' + input.moveZ.toFixed(1)
    + '  jump:' + (input.jump ? '1' : '0')
    + '  fire:' + (input.fireDown ? '1' : '0')
    + '  mouse:' + (cursorLocked ? 'locked (Tab to free)' : 'free (Tab to lock)');
  const diag2 = 'pos ' + pp.x.toFixed(1) + ',' + pp.y.toFixed(1) + ',' + pp.z.toFixed(1)
    + '  yaw ' + CAM[0].toFixed(2) + '  pitch ' + CAM[1].toFixed(2)
    + '  cam ' + CAM[2].toFixed(1) + ',' + CAM[3].toFixed(1) + ',' + CAM[4].toFixed(1)
    + '  shots ' + shotsHit + '/' + shotsFired;

  drawRect(0, sh - 44, sw, 44, { r: 0, g: 0, b: 0, a: 150 });
  drawText(diag1, 10, sh - 40, 13, { r: 200, g: 210, b: 230, a: 220 });
  drawText(diag2, 10, sh - 20, 13, { r: 180, g: 200, b: 220, a: 220 });

  if (isKeyPressed(Key.ESCAPE)) break;
  endDrawing();
}
